import { Check, ChevronDown, Plus, Power, Search, Star, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { loadDeviceSettings, saveProfessionalDevice, setProfessionalDeviceActive } from '@/src/services/bioimpedance';
import type { CatalogDevice, ProfessionalDevice } from './types';
import type { CatalogMeasurement } from '@/src/services/consultationMeasurements';

type Draft = { catalog_device_id: string; custom: boolean; custom_manufacturer: string; custom_model: string; custom_name: string; alias: string; serial_number: string; internal_id: string; is_default: boolean; capabilityIds: string[] };
const emptyDraft: Draft = { catalog_device_id: '', custom: false, custom_manufacturer: '', custom_model: '', custom_name: '', alias: '', serial_number: '', internal_id: '', is_default: false, capabilityIds: [] };

export function BioimpedanceDevicesSection({ onSaved }: { onSaved: (message: string) => Promise<void> }) {
  const [catalog, setCatalog] = useState<CatalogDevice[]>([]);
  const [devices, setDevices] = useState<ProfessionalDevice[]>([]);
  const [measurements, setMeasurements] = useState<CatalogMeasurement[]>([]);
  const [query, setQuery] = useState('');
  const [draft, setDraft] = useState<Draft | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const reload = async () => { const data = await loadDeviceSettings(); setCatalog(data.catalog); setDevices(data.devices); setMeasurements(data.measurements); };
  useEffect(() => { const timer=window.setTimeout(() => { void loadDeviceSettings().then((data) => { setCatalog(data.catalog); setDevices(data.devices); setMeasurements(data.measurements); }).catch((caught) => setError(caught instanceof Error ? caught.message : 'No pudimos cargar los equipos.')); },0); return () => window.clearTimeout(timer); }, []);
  const filtered = useMemo(() => catalog.filter((item) => `${item.manufacturer} ${item.model} ${item.commercial_name}`.toLowerCase().includes(query.toLowerCase())), [catalog, query]);
  const beginCatalog = (item: CatalogDevice) => setDraft({ ...emptyDraft, catalog_device_id: item.id, alias: item.commercial_name || item.model });
  const submit = async () => {
    if (!draft || !draft.alias.trim() || (draft.custom && (!draft.custom_manufacturer.trim() || !draft.custom_model.trim() || !draft.capabilityIds.length))) { setError('Completa el alias, fabricante, modelo y al menos una variable.'); return; }
    setSaving(true); setError('');
    try {
      await saveProfessionalDevice({ catalog_device_id: draft.custom ? null : draft.catalog_device_id, custom_manufacturer: draft.custom ? draft.custom_manufacturer : null, custom_model: draft.custom ? draft.custom_model : null, custom_name: draft.custom ? draft.custom_name : null, alias: draft.alias, serial_number: draft.serial_number || null, internal_id: draft.internal_id || null, is_active: true, is_default: draft.is_default }, draft.capabilityIds);
      setDraft(null); await reload(); await onSaved('Equipo guardado. Ya está disponible en tus consultas.');
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'No pudimos guardar el equipo.'); }
    finally { setSaving(false); }
  };
  const toggleActive = async (device: ProfessionalDevice) => { setError(''); try { await setProfessionalDeviceActive(device, !device.is_active); await reload(); await onSaved(device.is_active ? 'Equipo desactivado sin borrar su historial.' : 'Equipo activado.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No pudimos actualizar el equipo.'); } };

  return <div className="space-y-8">
    <div><p className="nuth-eyebrow">Equipos de bioimpedancia</p><h2 className="mt-2 text-2xl font-semibold text-[#173d36]">Tus equipos</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#687672]">Registra cada equipo físico. El modelo limita las variables disponibles y cada dato conserva su procedencia histórica.</p></div>
    {error && <div role="alert" className="rounded-2xl border border-[#efd2c8] bg-[#fff7f3] px-4 py-3 text-sm text-[#9a4935]">{error}</div>}
    <div className="grid gap-4 md:grid-cols-2">{devices.map((device) => <article key={device.id} className={`rounded-2xl border p-5 ${device.is_active ? 'border-[#dce4df]' : 'border-[#e6e7e4] bg-[#f7f8f6] opacity-75'}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-[#173d36]">{device.alias}</h3>{device.is_default && <span className="inline-flex items-center gap-1 rounded-full bg-[#fff1cf] px-2 py-1 text-[10px] font-semibold text-[#805c20]"><Star size={11} />Habitual</span>}</div><p className="mt-1 text-sm text-[#687672]">{device.catalog_device ? `${device.catalog_device.manufacturer} · ${device.catalog_device.model}` : `${device.custom_manufacturer} · ${device.custom_model}`}</p>{(device.serial_number || device.internal_id) && <p className="mt-2 text-xs text-[#7c8884]">{device.serial_number && `Serie ${device.serial_number}`}{device.serial_number && device.internal_id && ' · '}{device.internal_id && `ID ${device.internal_id}`}</p>}<p className="mt-3 text-xs text-[#60706a]">{device.capabilities.length} variables disponibles · {device.catalog_device ? 'Catálogo verificado' : 'Equipo personalizado'}</p></div><button type="button" onClick={() => void toggleActive(device)} className="rounded-xl border border-[#d8e0dc] p-2 text-[#52635d]" aria-label={device.is_active ? 'Desactivar equipo' : 'Activar equipo'}><Power size={17} /></button></div></article>)}</div>
    {!draft && <div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setDraft({ ...emptyDraft })} className="nuth-button-primary"><Plus size={16} />Agregar desde catálogo</button><button type="button" onClick={() => setDraft({ ...emptyDraft, custom: true })} className="nuth-button-secondary"><Plus size={16} />Equipo personalizado</button></div>}
    {draft && <div className="rounded-[24px] border border-[#dce4df] bg-[#fbfcfa] p-5 sm:p-6"><div className="flex items-start justify-between"><div><h3 className="text-lg font-semibold text-[#173d36]">{draft.custom ? 'Equipo personalizado' : 'Agregar equipo del catálogo'}</h3><p className="mt-1 text-sm text-[#6b7974]">Agregarlo no crea mediciones del paciente.</p></div><button type="button" onClick={() => setDraft(null)} aria-label="Cerrar"><X size={20} /></button></div>
      {!draft.custom && !draft.catalog_device_id && <div className="mt-5"><label className="relative block"><Search className="absolute left-3 top-3 text-[#81908a]" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar fabricante o modelo" className="w-full rounded-xl border border-[#d8e0dc] bg-white py-2.5 pl-10 pr-3 text-sm" /></label><div className="mt-3 max-h-72 space-y-2 overflow-y-auto">{filtered.map((item) => <button type="button" key={item.id} onClick={() => beginCatalog(item)} className="flex w-full items-center justify-between rounded-xl border border-[#e0e6e2] bg-white p-4 text-left hover:border-[#9eb6ad]"><span><strong className="block text-sm text-[#173d36]">{item.manufacturer} {item.model}</strong><span className="text-xs text-[#71807b]">{item.technology} · {item.is_segmental ? 'Segmental' : 'Cuerpo completo'}</span></span><ChevronDown className="-rotate-90" size={17} /></button>)}</div></div>}
      {draft.custom && <div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Fabricante" value={draft.custom_manufacturer} onChange={(value) => setDraft({ ...draft, custom_manufacturer: value })} /><Field label="Modelo" value={draft.custom_model} onChange={(value) => setDraft({ ...draft, custom_model: value })} /><Field label="Nombre comercial (opcional)" value={draft.custom_name} onChange={(value) => setDraft({ ...draft, custom_name: value })} /></div>}
      {(draft.custom || draft.catalog_device_id) && <><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Alias en tu consultorio" value={draft.alias} onChange={(value) => setDraft({ ...draft, alias: value })} /><Field label="Número de serie (opcional)" value={draft.serial_number} onChange={(value) => setDraft({ ...draft, serial_number: value })} /><Field label="Identificador interno (opcional)" value={draft.internal_id} onChange={(value) => setDraft({ ...draft, internal_id: value })} /></div><label className="mt-4 flex items-center gap-2 text-sm text-[#334b43]"><input type="checkbox" checked={draft.is_default} onChange={(event) => setDraft({ ...draft, is_default: event.target.checked })} />Marcar como equipo habitual</label>
      {draft.custom && <div className="mt-6"><p className="text-sm font-semibold text-[#173d36]">¿Qué variables reporta?</p><p className="mt-1 text-xs text-[#71807b]">Selecciona solo lo que aparece en la pantalla o reporte del equipo.</p><div className="mt-3 grid max-h-72 gap-2 overflow-y-auto sm:grid-cols-2">{measurements.map((measurement) => { const selected=draft.capabilityIds.includes(measurement.id); return <button type="button" key={measurement.id} onClick={() => setDraft({ ...draft, capabilityIds: selected ? draft.capabilityIds.filter((id) => id!==measurement.id) : [...draft.capabilityIds,measurement.id] })} className={`flex items-center justify-between rounded-xl border p-3 text-left text-sm ${selected?'border-[#5a8a78] bg-[#edf5f0]':'border-[#e0e6e2] bg-white'}`}><span>{measurement.display_name} <small className="text-[#73817c]">{measurement.unit}</small></span>{selected && <Check size={15} />}</button>; })}</div></div>}
      <div className="mt-6 flex justify-end"><button type="button" disabled={saving} onClick={() => void submit()} className="nuth-button-primary">{saving ? 'Guardando…' : 'Guardar equipo'}</button></div></>}</div>}
  </div>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-medium text-[#334b43]">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-[#d8e0dc] bg-white px-3 py-2.5 font-normal" /></label>; }
