import { useEffect, useState } from 'react';
import { supportRequest, supportDate } from './api';
type Stats={new:number;in_progress:number;waiting:number;without_reply:number;opened_30d:number;resolved_30d:number;response_minutes:number|null;response_sample:number;resolution_minutes:number|null;as_of:string};
export function elapsedSupportTime(minutes:number|null){if(minutes===null)return 'Sin datos';if(minutes<1)return 'Menos de 1 min';if(minutes<60)return `${Math.round(minutes)} min`;if(minutes<1440)return `${(minutes/60).toLocaleString('es-MX',{maximumFractionDigits:1})} h`;return `${(minutes/1440).toLocaleString('es-MX',{maximumFractionDigits:1})} días`;}
export function SupportStats(){
 const [data,setData]=useState<Stats|null>(null),[error,setError]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;void supportRequest<Stats>('stats',{},true).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[reload]);
 return <section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Atención de soporte</h2><button className="admin-button secondary" onClick={()=>setReload(n=>n+1)}>Actualizar estadísticas</button></div>{error&&<p role="alert" className="mb-4 text-red-700">{error}</p>}{data?<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[
  ['Casos nuevos',data.new],['En atención',data.in_progress],['Esperando al nutriólogo',data.waiting],['Abiertos sin respuesta del equipo',data.without_reply],['Abiertos · últimos 30 días',data.opened_30d],['Resueltos · últimos 30 días',data.resolved_30d],['Primera respuesta promedio',elapsedSupportTime(data.response_minutes)],['Resolución promedio',elapsedSupportTime(data.resolution_minutes)],
 ].map(([label,value])=><div className="admin-card" key={label}><p className="text-sm text-[#63796d]">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div>)}</div><p className="mt-5 text-sm text-[#63796d]">Primera respuesta: {data.response_sample} casos iniciados en los últimos 30 días y respondidos por el equipo. Resolución: casos cerrados en ese período. Los promedios cuentan el tiempo transcurrido, incluyendo fuera del horario de atención.</p><p className="mt-2 text-xs text-[#63796d]">Actualizado: {supportDate(data.as_of)}</p></>:!error&&<p role="status">Cargando estadísticas…</p>}</section>;
}
