import { useEffect, useState } from 'react';
import { agendaApi, agendaDate } from '@/src/services/agenda';
import type { Appointment } from '@/src/services/appointments';
import { AppointmentCalendar, AppointmentStatus } from '@/src/components/agenda/AppointmentCard';
export function AppointmentConfirmationPage(){
 const [token]=useState(()=>window.location.hash.slice(1)),[appointment,setAppointment]=useState<Appointment|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{window.history.replaceState(null,'',window.location.pathname);let active=true;void agendaApi<Appointment>('appointment_info',{token}).then(a=>{if(active)setAppointment(a);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[token]);
 async function confirm(){if(busy)return;setBusy(true);setError('');try{setAppointment(await agendaApi<Appointment>('appointment_confirm',{token}));}catch(e){setError(e instanceof Error?e.message:'Intenta de nuevo.');}finally{setBusy(false);}}
 return <main className="min-h-screen bg-[#f3f6f1] px-4 py-10 text-[#173d36]"><div className="mx-auto max-w-lg rounded-3xl border border-[#dfe7e1] bg-white p-6 sm:p-8"><p className="nuth-eyebrow">Nuthrick · Tu cita</p><h1 className="mt-3 text-2xl font-semibold">Confirma tu asistencia</h1>{appointment?<><p className="mt-5 text-lg">Con {appointment.professional_name}</p><p className="mt-2">{agendaDate(appointment.starts_at,appointment.timezone)}</p><p className="mt-2 text-sm">{appointment.timezone} · {appointment.modality==='online'?'En línea':appointment.location_snapshot?.name}</p>{appointment.location_snapshot?.address&&<p className="mt-1 text-sm">{appointment.location_snapshot.address}</p>}<div className="mt-5"><AppointmentStatus appointment={appointment}/></div>{appointment.patient_confirmed_at?<><p role="status" className="mt-5 font-semibold">Tu asistencia está confirmada.</p><AppointmentCalendar appointment={appointment}/></>:<button className="nuth-button mt-6 w-full justify-center" disabled={busy} onClick={()=>void confirm()}>{busy?'Confirmando…':'Confirmar mi asistencia'}</button>}<p className="mt-5 text-sm text-[#63796d]">Si necesitas cambiar o cancelar el horario, contacta a tu nutriólogo.</p></>:!error&&<p role="status" className="mt-5">Cargando la cita…</p>}{error&&<p role="alert" className="mt-5 text-red-700">{error}</p>}</div></main>;
}
