import { ArrowRight, CalendarDays, CheckCircle2, ClipboardList, ExternalLink, UserRound, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '@/src/features/auth/AuthProvider';

export function DashboardPage() {
  const { profile } = useAuth();
  const fields = [profile?.biography, profile?.avatar_path, profile?.public_slug, profile?.specialties.length, profile?.is_public];
  const completed = fields.filter(Boolean).length;
  const percentage = Math.round((completed / fields.length) * 100);
  return <div><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="nuth-eyebrow">Dashboard</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Bienvenido, {profile?.full_name?.split(' ')[0] || 'profesional'}</h1><p className="mt-3 text-[#687672]">Aquí tienes lo esencial para continuar construyendo tu presencia profesional.</p></div>{profile?.public_slug && <Link to={`/p/${profile.public_slug}`} target="_blank" className="nuth-button-secondary">Ver perfil público <ExternalLink size={16} /></Link>}</div><div className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-[28px] bg-[#173d36] p-7 text-white sm:p-9"><div className="flex items-start justify-between"><div><p className="text-sm text-white/55">Tu perfil profesional</p><h2 className="mt-2 text-3xl font-semibold">{percentage}% completo</h2></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><UserRound size={22} /></span></div><div className="mt-8 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#efbd6b] transition-all" style={{ width: `${percentage}%` }} /></div><p className="mt-4 max-w-lg text-sm leading-6 text-white/60">Agrega tu biografía, foto y especialidades para que tu página pública represente mejor tu trabajo.</p><Link to="/app/profile" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#f2c47a]">Completar perfil <ArrowRight size={16} /></Link></section><section className="rounded-[28px] border border-[#dfe5e1] bg-white p-7 sm:p-9"><p className="text-sm font-semibold text-[#4b7163]">Siguiente paso recomendado</p><h2 className="mt-3 text-2xl font-semibold tracking-[-.03em]">Activa tu página pública</h2><p className="mt-3 text-sm leading-6 text-[#6d7a76]">Elige un slug, revisa qué información mostrarás y comparte un solo enlace.</p><div className="mt-6 flex items-center gap-3 rounded-2xl bg-[#f4f6f2] p-4"><CheckCircle2 className={profile?.is_public ? 'text-[#4e7a68]' : 'text-[#a5b0ab]'} size={21} /><span className="text-sm">{profile?.is_public ? 'Tu página está publicada' : 'Tu página aún no es pública'}</span></div></section></div><div className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Lo que viene después</h2><span className="text-xs text-[#87938e]">Próximamente</span></div><div className="mt-4 grid gap-4 sm:grid-cols-3">{[[UsersRound, 'Pacientes', 'Expedientes y seguimiento'], [CalendarDays, 'Agenda', 'Citas y disponibilidad'], [ClipboardList, 'Consultas', 'Procesos de atención']].map(([Icon, title, text]) => { const C = Icon as typeof UsersRound; return <article key={title as string} className="rounded-2xl border border-dashed border-[#d6ddd8] bg-white/55 p-5 text-[#85918c]"><C size={20} /><h3 className="mt-4 font-semibold text-[#63716c]">{title as string}</h3><p className="mt-1 text-xs">{text as string}</p></article>; })}</div></div></div>;
}
