import {useEffect,useState} from 'react';
import {Trash2} from 'lucide-react';
import {portalAction,type PortalPlan} from '@/src/services/patientPortal';
import type {PublishedPlanSummary} from '@/src/services/planDocuments';
import type {Consultation} from '@/src/types/domain';
import {PortalPlanContent} from './PortalPlan';
import {PlanExport} from './PlanExport';
import {portalDate} from './PortalContentView';
export function PublishedPlanHistory({patientId,consultations=[],onConsultation}:{patientId:string;consultations?:Consultation[];onConsultation?:(id:string)=>void}){
 const [versions,setVersions]=useState<PublishedPlanSummary[]>([]),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<PortalPlan|null>(null),[reading,setReading]=useState(false),[retiring,setRetiring]=useState<PublishedPlanSummary|null>(null),[retireBusy,setRetireBusy]=useState(false);
 useEffect(()=>{let active=true;void portalAction<{versions:PublishedPlanSummary[]}>({patientId},'plan_history').then(r=>{if(active){setVersions(r.versions);setMore(r.versions.length===50);}}).catch(()=>{if(active)setError('No pudimos cargar los planes publicados.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[patientId]);
 async function loadMore(){setLoading(true);try{const r=await portalAction<{versions:PublishedPlanSummary[]}>({patientId},'plan_history',{offset:versions.length});setVersions(old=>[...old,...r.versions]);setMore(r.versions.length===50);}catch{setError('No pudimos cargar los planes publicados.');}finally{setLoading(false);}}
 async function view(id:string){if(reading)return;setReading(true);setError('');try{const r=await portalAction<{plan:PortalPlan}>({patientId},'plan_version',{versionId:id});setSelected(r.plan);}catch{setError('No pudimos abrir esta versión del plan.');}finally{setReading(false);}}
 async function retire(){if(!retiring||retireBusy)return;setRetireBusy(true);setError('');setNotice('');try{const result=await portalAction<{ok:boolean;removedFromSharedPlan:boolean}>({patientId},'plan_history',{retireVersionId:retiring.id});if(!result.ok)throw new Error('No pudimos retirar esta versión. Actualiza la página e inténtalo de nuevo.');setVersions(old=>old.filter(version=>version.id!==retiring.id));setNotice(result.removedFromSharedPlan?'Versión retirada. También se quitó el plan del Super Link del paciente.':'Versión retirada del historial. El registro clínico se conserva para auditoría.');setRetiring(null);if(more){try{const refreshed=await portalAction<{versions:PublishedPlanSummary[]}>({patientId},'plan_history');setVersions(refreshed.versions);setMore(refreshed.versions.length===50);}catch{setError('La versión se retiró, pero no pudimos actualizar la lista completa. Recarga esta sección.');}}else setMore(false);}catch(cause){setError(cause instanceof Error?cause.message:'No pudimos retirar esta versión. Intenta de nuevo.');}finally{setRetireBusy(false);}}
 const events=[...versions.map(v=>({id:v.id,date:v.published_at,version:v,consultation:null as Consultation|null})),...consultations.filter(c=>c.status==='completed'&&!c.deleted_at).map(c=>({id:c.id,date:c.consultation_date,version:null as PublishedPlanSummary|null,consultation:c}))].sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id));
 return <section aria-label="Historial de planes publicados" className="space-y-3">
  {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-xl border border-[#c9dfd5] bg-[#edf6f0] px-3 py-2 text-sm text-[#315d49]">{notice}</p>}
  {loading&&<p role="status">Cargando versiones publicadas…</p>}
  {!loading&&!events.length&&!error&&<p className="text-sm text-[#74817d]">Aún no hay planes publicados. Los borradores permanecen en el Taller.</p>}
  {events.map(event=><article key={event.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#dfe5e1] p-4">
   <div><p className="text-xs text-[#74817d]">{portalDate(event.date)}</p><h3 className="mt-1 font-semibold">{event.version?`Plan nutricional · v${event.version.version_number}`:'Consulta finalizada'}</h3>{event.version&&<p className="mt-1 text-sm text-[#52685d]">{event.version.title}</p>}</div>
   {event.version?<div className="flex flex-wrap gap-2"><button className="nuth-button-secondary !px-3 !py-2 !text-xs" disabled={reading||retireBusy} onClick={()=>void view(event.version!.id)}>Ver</button><PlanExport access={{patientId}} versionId={event.version.id}/><button type="button" aria-label={`Retirar versión ${event.version.version_number} del historial`} className="inline-flex items-center gap-1 rounded-xl border border-[#e7cfca] px-3 py-2 text-xs font-medium text-[#8d493f] hover:bg-[#fbf1ef] disabled:opacity-50" disabled={retireBusy} onClick={()=>setRetiring(event.version)}><Trash2 size={14}/>Retirar</button></div>:<button className="nuth-button-secondary !px-3 !py-2 !text-xs" onClick={()=>onConsultation?.(event.id)}>Ver consulta</button>}
  </article>)}
  {more&&<button className="nuth-button-secondary" disabled={loading} onClick={()=>void loadMore()}>Ver versiones anteriores</button>}
  {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-[#102d27]/50 p-3 sm:p-6" role="dialog" aria-modal="true" aria-label={`Plan publicado v${selected.versionNumber}`}><div className="mx-auto max-w-3xl rounded-3xl bg-white p-4"><div className="mb-3 flex items-center justify-between"><p className="text-sm">Versión histórica · Solo lectura</p><button className="nuth-button-secondary !py-2" onClick={()=>setSelected(null)}>Cerrar plan</button></div><PortalPlanContent plan={selected}/></div></div>}
  {retiring&&<div className="fixed inset-0 z-[60] grid place-items-center bg-[#102d27]/45 p-4" role="dialog" aria-modal="true" aria-labelledby="retire-plan-version-title"><div className="w-full max-w-md rounded-2xl border border-[#dfe5e1] bg-white p-5 shadow-2xl"><h2 id="retire-plan-version-title" className="text-lg font-semibold text-[#173d36]">Retirar versión publicada</h2><p className="mt-2 text-sm text-[#52685d]">La versión {retiring.version_number} de <strong>{retiring.title}</strong> dejará de aparecer en este historial y ya no se podrá abrir ni exportar desde aquí.</p><p className="mt-2 text-sm text-[#52685d]">El registro clínico se conserva para auditoría. Si esta versión está compartida, también se quitará del Super Link del paciente.</p>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" disabled={retireBusy} className="nuth-button-secondary" onClick={()=>setRetiring(null)}>Cancelar</button><button type="button" disabled={retireBusy} className="inline-flex items-center gap-2 rounded-xl bg-[#8d493f] px-4 py-2 text-sm font-semibold text-white hover:bg-[#773b33] disabled:opacity-50" onClick={()=>void retire()}>{retireBusy?'Retirando…':'Retirar versión'}</button></div></div></div>}
 </section>;
}
