// GENERATED by scripts/build-workshop-ai-engine.mjs. Shared existing Workshop engines; do not edit.

// frontend/src/features/exchanges/catalog.ts
var EXCHANGE_SYSTEM_CODE = "SMAE_NOM037_2012";
var EXCHANGE_CATALOG_VERSION = "1.0.0";
var group = (groupCode, groupName, shortName, category, categoryName, displayOrder, energyKcal, carbohydrateG, proteinG, fatG) => ({
  systemCode: EXCHANGE_SYSTEM_CODE,
  catalogVersion: EXCHANGE_CATALOG_VERSION,
  groupCode,
  groupName,
  shortName,
  category,
  categoryName,
  displayOrder,
  energyKcal,
  carbohydrateG,
  proteinG,
  fatG,
  active: true,
  source: "SMAE / NOM-037-SSA2-2012"
});
var exchangeCatalog = [
  group("VEGETABLES", "Verduras", "Verduras", "produce", "Vegetales y frutas", 10, 25, 4, 2, 0),
  group("FRUITS", "Frutas", "Frutas", "produce", "Vegetales y frutas", 20, 60, 15, 0, 0),
  group("CEREALS_NO_FAT", "Cereales y tub\xE9rculos sin grasa", "Cereales sin grasa", "grains", "Cereales y leguminosas", 30, 70, 15, 2, 0),
  group("CEREALS_WITH_FAT", "Cereales y tub\xE9rculos con grasa", "Cereales con grasa", "grains", "Cereales y leguminosas", 40, 115, 15, 2, 5),
  group("LEGUMES", "Leguminosas", "Leguminosas", "grains", "Cereales y leguminosas", 50, 120, 20, 8, 1),
  group("AOA_VERY_LOW_FAT", "AOA \xB7 muy bajos en grasa", "AOA muy bajos", "animal", "Alimentos de origen animal", 60, 40, 0, 7, 1),
  group("AOA_LOW_FAT", "AOA \xB7 bajos en grasa", "AOA bajos", "animal", "Alimentos de origen animal", 70, 55, 0, 7, 3),
  group("AOA_MODERATE_FAT", "AOA \xB7 moderados en grasa", "AOA moderados", "animal", "Alimentos de origen animal", 80, 75, 0, 7, 5),
  group("AOA_HIGH_FAT", "AOA \xB7 altos en grasa", "AOA altos", "animal", "Alimentos de origen animal", 90, 100, 0, 7, 8),
  group("MILK_SKIM", "Leche descremada", "Descremada", "milk", "Leches", 100, 95, 12, 9, 2),
  group("MILK_SEMI_SKIM", "Leche semidescremada", "Semidescremada", "milk", "Leches", 110, 110, 12, 9, 4),
  group("MILK_WHOLE", "Leche entera", "Entera", "milk", "Leches", 120, 150, 12, 9, 8),
  group("MILK_WITH_SUGAR", "Leche con az\xFAcar", "Con az\xFAcar", "milk", "Leches", 130, 200, 30, 8, 8),
  group("FATS_NO_PROTEIN", "Aceites y grasas sin prote\xEDna", "Sin prote\xEDna", "fats", "Grasas", 140, 45, 0, 0, 5),
  group("FATS_WITH_PROTEIN", "Aceites y grasas con prote\xEDna", "Con prote\xEDna", "fats", "Grasas", 150, 70, 3, 3, 5),
  group("SUGARS_NO_FAT", "Az\xFAcares sin grasa", "Sin grasa", "sugars", "Az\xFAcares", 160, 40, 10, 0, 0),
  group("SUGARS_WITH_FAT", "Az\xFAcares con grasa", "Con grasa", "sugars", "Az\xFAcares", 170, 85, 10, 0, 5)
];
var exchangeCatalogCategories = [...new Map(exchangeCatalog.map((item) => [item.category, item.categoryName])).entries()].map(([category, label]) => ({ category, label }));
function getExchangeGroup(code) {
  const result = exchangeCatalog.find((group2) => group2.groupCode === code);
  if (!result) throw new Error(`Grupo de equivalentes no encontrado: ${code}`);
  return result;
}

// frontend/src/features/exchanges/model.ts
var zeroTotals = () => ({ energy_kcal: 0, carbohydrate_g: 0, protein_g: 0, fat_g: 0 });
var currentTime = () => (/* @__PURE__ */ new Date()).toISOString();
function calculateExchangeTotals(groups) {
  return groups.reduce((totals, item) => {
    const catalog = getExchangeGroup(item.group_code);
    return {
      energy_kcal: totals.energy_kcal + item.portions * catalog.energyKcal,
      carbohydrate_g: totals.carbohydrate_g + item.portions * catalog.carbohydrateG,
      protein_g: totals.protein_g + item.portions * catalog.proteinG,
      fat_g: totals.fat_g + item.portions * catalog.fatG
    };
  }, zeroTotals());
}
function calculateExchangeDifferences(actual, target) {
  return {
    energy_kcal: actual.energy_kcal - target.energy_kcal,
    carbohydrate_g: actual.carbohydrate_g - target.carbohydrate_g,
    protein_g: actual.protein_g - target.protein_g,
    fat_g: actual.fat_g - target.fat_g
  };
}
function createExchangePrescription(target) {
  const groups = exchangeCatalog.map((group2) => ({ group_code: group2.groupCode, portions: 0 }));
  const totals = calculateExchangeTotals(groups);
  return {
    schema_version: 1,
    exchange_system_code: EXCHANGE_SYSTEM_CODE,
    catalog_version: EXCHANGE_CATALOG_VERSION,
    target_snapshot: target,
    confirmed_target_snapshot: null,
    groups,
    derived_totals: totals,
    differences: calculateExchangeDifferences(totals, target),
    status: "not_started",
    confirmed_at: null,
    updated_at: currentTime()
  };
}
function buildPrescription(prescription, target, groups = prescription.groups, status = prescription.status, confirmedAt = prescription.confirmed_at) {
  const totals = calculateExchangeTotals(groups);
  return {
    ...prescription,
    exchange_system_code: EXCHANGE_SYSTEM_CODE,
    catalog_version: EXCHANGE_CATALOG_VERSION,
    target_snapshot: target,
    groups,
    derived_totals: totals,
    differences: calculateExchangeDifferences(totals, target),
    status,
    confirmed_at: confirmedAt,
    updated_at: currentTime()
  };
}
function applyExchangeSuggestion(prescription, target, suggestion) {
  const suggestionByCode = new Map(suggestion.groups.map((group2) => [group2.groupCode, group2.portions]));
  const groups = prescription.groups.map((group2) => ({
    ...group2,
    portions: suggestionByCode.get(group2.group_code) ?? group2.portions
  }));
  return {
    ...buildPrescription(prescription, target, groups, groups.some((group2) => group2.portions > 0) ? "editing" : "not_started", null),
    suggestion_source: "automatic",
    suggestion_algorithm: suggestion.metadata.algorithmVersion,
    suggestion_applied_at: currentTime()
  };
}

// frontend/src/features/meal-distribution/model.ts
var MEAL_DISTRIBUTION_SCHEMA_VERSION = 1;
var EPSILON = 1e-7;
var now = () => (/* @__PURE__ */ new Date()).toISOString();
var round = (value) => Math.round((value + Number.EPSILON) * 1e6) / 1e6;
var zeroTotals2 = () => ({ energy_kcal: 0, carbohydrate_g: 0, protein_g: 0, fat_g: 0 });
var makeId = () => globalThis.crypto?.randomUUID?.() ?? `meal-${Date.now()}-${Math.random().toString(36).slice(2)}`;
function inferMealType(name) {
  const normalized = name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  if (normalized.includes("desay")) return "BREAKFAST";
  if (normalized.includes("colac") || normalized.includes("snack") || normalized.includes("preent") || normalized.includes("postent") || normalized.includes("merienda")) return "SNACK";
  if (normalized.includes("comida") || normalized.includes("almuerzo")) return "MAIN_MEAL";
  if (normalized.includes("cena")) return "DINNER";
  return "CUSTOM";
}
function createMealTime(displayName, displayOrder, time = null, id = makeId()) {
  return { id, meal_type: inferMealType(displayName), display_name: displayName, time, display_order: displayOrder };
}
function createDefaultMealTimes(idFactory = makeId) {
  return ["Desayuno", "Comida", "Cena"].map((name, index) => createMealTime(name, index, null, idFactory()));
}
function calculateGroupDistribution(distribution, groupCode) {
  return round(distribution.filter((entry) => entry.group_code === groupCode).reduce((sum, entry) => sum + entry.portions, 0));
}
function calculateRemainingExchanges(distribution, prescription, groupCode) {
  const available = prescription.groups.find((group2) => group2.group_code === groupCode)?.portions ?? 0;
  const assigned = calculateGroupDistribution(distribution, groupCode);
  return { available, assigned, remaining: round(available - assigned) };
}
function calculateMealNutrition(distribution, mealTimeId) {
  const total = distribution.filter((entry) => entry.meal_time_id === mealTimeId).reduce((sum, entry) => {
    const group2 = getExchangeGroup(entry.group_code);
    return {
      energy_kcal: sum.energy_kcal + entry.portions * group2.energyKcal,
      carbohydrate_g: sum.carbohydrate_g + entry.portions * group2.carbohydrateG,
      protein_g: sum.protein_g + entry.portions * group2.proteinG,
      fat_g: sum.fat_g + entry.portions * group2.fatG
    };
  }, zeroTotals2());
  return { meal_time_id: mealTimeId, ...Object.fromEntries(Object.entries(total).map(([key, value]) => [key, round(value)])) };
}
function calculateDerivedMealTotals(distribution, mealTimes) {
  return [...mealTimes].sort((a, b) => a.display_order - b.display_order).map((meal) => calculateMealNutrition(distribution, meal.id));
}
function calculateDistributionStatus(distribution, prescription) {
  const groups = exchangeCatalog.map((catalog) => {
    const values = calculateRemainingExchanges(distribution, prescription, catalog.groupCode);
    const state = values.remaining < -EPSILON ? "excess" : values.remaining > EPSILON ? "pending" : "complete";
    return { group_code: catalog.groupCode, ...values, state };
  }).filter((group2) => group2.available > EPSILON || group2.assigned > EPSILON);
  const complete = groups.filter((group2) => group2.state === "complete").length;
  const pending = groups.filter((group2) => group2.state === "pending").length;
  const excess = groups.filter((group2) => group2.state === "excess").length;
  return {
    groups,
    complete,
    pending,
    excess,
    canConfirm: groups.length > 0 && pending === 0 && excess === 0,
    availablePortions: round(groups.reduce((sum, group2) => sum + group2.available, 0)),
    assignedPortions: round(groups.reduce((sum, group2) => sum + group2.assigned, 0)),
    remainingPortions: round(groups.reduce((sum, group2) => sum + group2.remaining, 0))
  };
}
function rebuild(base, distribution = base.distribution, mealTimes = base.meal_times, status = base.status, confirmedAt = base.confirmed_at) {
  return {
    ...base,
    meal_times: [...mealTimes].sort((a, b) => a.display_order - b.display_order).map((meal, index) => ({ ...meal, display_order: index })),
    distribution: distribution.filter((entry) => entry.portions > EPSILON),
    derived_meal_totals: calculateDerivedMealTotals(distribution, mealTimes),
    status,
    confirmed_at: confirmedAt,
    updated_at: now()
  };
}
function createMealDistribution(idFactory = makeId) {
  const mealTimes = createDefaultMealTimes(idFactory);
  return {
    schema_version: MEAL_DISTRIBUTION_SCHEMA_VERSION,
    source_exchange_snapshot: null,
    meal_times: mealTimes,
    distribution: [],
    derived_meal_totals: calculateDerivedMealTotals([], mealTimes),
    status: "not_started",
    confirmed_at: null,
    updated_at: now()
  };
}
function applyMealDistributionSuggestion(current, suggestion) {
  return {
    ...rebuild(current, suggestion.distribution, current.meal_times, suggestion.distribution.length ? "editing" : "not_started", null),
    suggestion_metadata: { source: "automatic", ...suggestion.metadata }
  };
}

// frontend/src/features/menu/model.ts
var DIET_MENU_SCHEMA_VERSION = 1;
var MENU_COMPARISON_TOLERANCE = 0.1;
var MENU_NUMERIC_EPSILON = 1e-6;
var practicalSteps = {
  g: 10,
  ml: 10,
  piece: 0.5,
  half: 1,
  cup: 0.25,
  tablespoon: 0.5,
  teaspoon: 0.5,
  slice: 0.5,
  tortilla: 0.5,
  glass: 0.5,
  serving: 0.5,
  unit: 0.5
};
var now2 = () => (/* @__PURE__ */ new Date()).toISOString();
var roundMenuNumber = (value) => Math.round((value + Number.EPSILON) * 1e6) / 1e6;
var round2 = roundMenuNumber;
var makeId2 = (prefix) => globalThis.crypto?.randomUUID?.() ?? `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
function createFoodSnapshot(food) {
  return {
    id: food.id,
    name: food.name,
    group_code: food.group_code,
    portion_amount: Number(food.portion_amount),
    portion_unit: food.portion_unit,
    portion_description: food.portion_description,
    exchange_system_code: food.exchange_system_code,
    exchange_catalog_version: food.exchange_catalog_version,
    source: food.source,
    source_version: food.source_version,
    is_custom: food.is_custom,
    attributes: { ...food.attributes }
  };
}
function exchangeContributionForFood(food, amount) {
  const portions = Number(food.portion_amount) > 0 ? round2(amount / Number(food.portion_amount)) : 0;
  return portions > MENU_NUMERIC_EPSILON ? [{ group_code: food.group_code, portions }] : [];
}
function practicalFoodQuantity(value, unit, minimum = practicalSteps[unit]) {
  if (["piece", "cup", "slice", "tortilla"].includes(unit) && value > 0 && Math.abs(value * 3 - Math.round(value * 3)) < 5e-3 && Math.round(value * 3) > 0) return round2(Math.round(value * 3) / 3);
  const step = practicalSteps[unit];
  const quantized = Math.round(value / step) * step;
  return round2(Math.max(minimum, quantized));
}
function aggregateContributions(contributions) {
  const totals = /* @__PURE__ */ new Map();
  for (const item of contributions) totals.set(item.group_code, round2((totals.get(item.group_code) ?? 0) + item.portions));
  return [...totals.entries()].map(([group_code, portions]) => ({ group_code, portions })).filter((item) => item.portions > MENU_NUMERIC_EPSILON);
}
function recipeExchangeContributions(recipe, servings = 1) {
  const factor = servings / Number(recipe.servings || 1);
  return aggregateContributions(recipe.items.flatMap((item) => item.exchange_contribution.map((value) => ({
    group_code: value.group_code,
    portions: round2(value.portions * factor)
  }))));
}
function createDietMenu(mealDistribution, idFactory = makeId2) {
  const activeMenuId = idFactory("menu");
  return {
    schema_version: DIET_MENU_SCHEMA_VERSION,
    source_meal_distribution_snapshot: null,
    menus: [{
      id: activeMenuId,
      name: "Men\xFA principal",
      display_order: 0,
      meal_menus: mealDistribution.meal_times.map((meal) => ({ meal_time_id: meal.id, entries: [] }))
    }],
    active_menu_id: activeMenuId,
    derived_exchange_usage: [],
    status: "not_started",
    confirmed_at: null,
    updated_at: now2()
  };
}
function activeMenu(menu) {
  return menu.menus.find((variant) => variant.id === menu.active_menu_id) ?? menu.menus[0];
}
function withVariant(menu, variant) {
  const menus = menu.menus.map((item) => item.id === variant.id ? variant : item);
  const next = { ...menu, menus, confirmed_at: null, updated_at: now2() };
  const usage = calculateMenuUsage(next);
  return {
    ...next,
    derived_exchange_usage: usage,
    status: usage.length ? "editing" : "not_started"
  };
}
function ensureMealMenus(variant, mealDistribution) {
  const validIds = new Set(mealDistribution.meal_times.map((meal) => meal.id));
  const existing = variant.meal_menus.filter((meal) => validIds.has(meal.meal_time_id));
  for (const meal of mealDistribution.meal_times) {
    if (!existing.some((item) => item.meal_time_id === meal.id)) existing.push({ meal_time_id: meal.id, entries: [] });
  }
  return { ...variant, meal_menus: existing };
}
function addFoodToMenu(menu, mealDistribution, mealTimeId, food, quantity, id = makeId2("entry")) {
  if (!Number.isFinite(quantity) || quantity <= 0) return menu;
  const entry = {
    id,
    type: "food",
    source_id: food.id,
    name_snapshot: food.name,
    quantity: round2(quantity),
    unit: food.portion_unit,
    food_snapshot: createFoodSnapshot(food),
    exchange_contributions: exchangeContributionForFood(food, quantity)
  };
  const variant = ensureMealMenus(activeMenu(menu), mealDistribution);
  return withVariant(menu, { ...variant, meal_menus: variant.meal_menus.map((meal) => meal.meal_time_id === mealTimeId ? { ...meal, entries: [...meal.entries, entry] } : meal) });
}
function addRecipeToMenu(menu, mealDistribution, mealTimeId, recipe, servings = 1, id = makeId2("entry")) {
  if (!Number.isFinite(servings) || servings <= 0) return menu;
  const verifiedWater = recipe.id === "nuthrick-water-v1" && recipe.source === "CDC_PLAIN_WATER" && recipe.tags?.includes("nuthrick:drink");
  if (!Number.isFinite(Number(recipe.servings)) || Number(recipe.servings) <= 0 || !recipe.items.length && !verifiedWater || recipe.items.some((item) => !Number.isFinite(Number(item.amount)) || Number(item.amount) <= 0 || !item.exchange_contribution.length)) return menu;
  const entry = {
    id,
    type: "recipe",
    source_id: recipe.id,
    name_snapshot: recipe.name,
    quantity: round2(servings),
    unit: "recipe_serving",
    culinary_role: recipe.tags?.includes("nuthrick:drink") ? "drink" : void 0,
    recipe_snapshot: {
      recipe_id: recipe.id,
      name: recipe.name,
      servings: recipe.servings,
      instructions: recipe.instructions,
      tags: [...recipe.tags ?? []],
      substitution_notes: recipe.substitution_notes,
      source_reference: recipe.source_reference,
      source: recipe.source,
      items: recipe.items.map((item) => ({
        amount: Number(item.amount),
        unit: item.unit,
        food_snapshot: structuredClone(item.food_snapshot),
        exchange_contribution: item.exchange_contribution.map((value) => ({ ...value }))
      }))
    },
    exchange_contributions: recipeExchangeContributions(recipe, servings)
  };
  const variant = ensureMealMenus(activeMenu(menu), mealDistribution);
  return withVariant(menu, { ...variant, meal_menus: variant.meal_menus.map((meal) => meal.meal_time_id === mealTimeId ? { ...meal, entries: [...meal.entries, entry] } : meal) });
}
function adjustRecipeIngredients(recipe, amounts) {
  return {
    ...recipe,
    items: recipe.items.map((item) => {
      const amount = Number(amounts[item.id] ?? item.amount);
      if (!Number.isFinite(amount) || amount <= 0) return item;
      return {
        ...item,
        amount: round2(amount),
        exchange_contribution: exchangeContributionForFood(item.food_snapshot, amount)
      };
    })
  };
}
function recipeIngredientsChanged(original, adjusted) {
  return original.items.length !== adjusted.items.length || original.name !== adjusted.name || original.instructions !== adjusted.instructions || original.substitution_notes !== adjusted.substitution_notes || original.items.some((item) => {
    const next = adjusted.items.find((candidate) => candidate.id === item.id);
    return !next || (next.food_item_id ?? next.food_snapshot.id) !== (item.food_item_id ?? item.food_snapshot.id) || next.unit !== item.unit || Math.abs(Number(next.amount) - Number(item.amount)) > MENU_NUMERIC_EPSILON;
  });
}
function removeMenuEntry(menu, mealDistribution, entryId) {
  const variant = activeMenu(menu);
  return withVariant(menu, { ...variant, meal_menus: variant.meal_menus.map((meal) => ({ ...meal, entries: meal.entries.filter((entry) => entry.id !== entryId) })) });
}
function calculateMenuUsage(menu) {
  const variant = activeMenu(menu);
  if (!variant) return [];
  const totals = /* @__PURE__ */ new Map();
  for (const meal of variant.meal_menus) for (const entry of meal.entries) for (const contribution of entry.exchange_contributions) {
    const key = `${meal.meal_time_id}:${contribution.group_code}`;
    const previous = totals.get(key);
    totals.set(key, { meal_time_id: meal.meal_time_id, group_code: contribution.group_code, portions: round2((previous?.portions ?? 0) + contribution.portions) });
  }
  return [...totals.values()];
}
function calculateMenuStatus(menu, mealDistribution) {
  const usage = calculateMenuUsage(menu);
  const rows = mealDistribution.distribution.filter((item) => item.portions > 0).map((required) => {
    const used = usage.find((item) => item.meal_time_id === required.meal_time_id && item.group_code === required.group_code)?.portions ?? 0;
    const remaining = round2(required.portions - used);
    return {
      ...required,
      used,
      remaining,
      state: remaining > MENU_COMPARISON_TOLERANCE ? "pending" : remaining < -MENU_COMPARISON_TOLERANCE ? "excess" : "complete"
    };
  });
  for (const used of usage) {
    if (!rows.some((row) => row.meal_time_id === used.meal_time_id && row.group_code === used.group_code) && used.portions > MENU_COMPARISON_TOLERANCE) {
      rows.push({ ...used, portions: 0, used: used.portions, remaining: -used.portions, state: "excess" });
    }
  }
  return {
    rows,
    complete: rows.filter((row) => row.state === "complete").length,
    pending: rows.filter((row) => row.state === "pending").length,
    excess: rows.filter((row) => row.state === "excess").length,
    canConfirm: rows.length > 0 && rows.every((row) => row.state === "complete")
  };
}
function scoreRecipeCompatibility({ pendingExchanges: required, recipe, mealType, restrictions }) {
  const contributions = recipeExchangeContributions(recipe);
  const codes = /* @__PURE__ */ new Set([...required.map((item) => item.group_code), ...contributions.map((item) => item.group_code)]);
  let covered = 0;
  let missing = 0;
  let excess = 0;
  let groupsCovered = 0;
  const coveredGroups = [];
  const missingGroups = [];
  const excessGroups = [];
  for (const code of codes) {
    const needed = required.find((item) => item.group_code === code)?.portions ?? 0;
    const supplied = contributions.find((item) => item.group_code === code)?.portions ?? 0;
    covered += Math.min(needed, supplied);
    const groupMissing = Math.max(0, needed - supplied);
    const groupExcess = Math.max(0, supplied - needed);
    missing += groupMissing > MENU_COMPARISON_TOLERANCE ? groupMissing : 0;
    excess += groupExcess > MENU_COMPARISON_TOLERANCE ? groupExcess : 0;
    if (needed > MENU_COMPARISON_TOLERANCE && supplied > MENU_COMPARISON_TOLERANCE) {
      groupsCovered += 1;
      coveredGroups.push(code);
    }
    if (groupMissing > MENU_COMPARISON_TOLERANCE) missingGroups.push({ group_code: code, portions: round2(groupMissing) });
    if (groupExcess > MENU_COMPARISON_TOLERANCE) excessGroups.push({ group_code: code, portions: round2(groupExcess) });
  }
  const excludedFoodIds = new Set(restrictions?.excludedFoodIds ?? []);
  const excludedGroupCodes = new Set(restrictions?.excludedGroupCodes ?? []);
  const excludedAttributes = new Set(restrictions?.excludedAttributes ?? []);
  const blocked = recipe.items.some((item) => excludedFoodIds.has(item.food_item_id ?? item.food_snapshot.id) || excludedGroupCodes.has(item.food_snapshot.group_code) || Object.entries(item.food_snapshot.attributes ?? {}).some(([attribute, value]) => value === "contains" && excludedAttributes.has(attribute)));
  const desiredTotal = required.reduce((sum, item) => sum + item.portions, 0);
  const coverageRatio = desiredTotal > MENU_COMPARISON_TOLERANCE ? covered / desiredTotal : 0;
  const mealAffinity = !mealType ? 0 : recipe.meal_types.includes(mealType) ? 1 : recipe.meal_types.length ? -0.5 : 0;
  const score = round2(
    covered * 8 + groupsCovered * 3 + mealAffinity * 4 - missing * 1.5 - excess * 10 - (blocked ? 1e3 : 0)
  );
  const label = blocked ? "No compatible con restricciones" : excess <= MENU_COMPARISON_TOLERANCE && missing <= MENU_COMPARISON_TOLERANCE ? "Dentro de tolerancia" : excess <= MENU_COMPARISON_TOLERANCE && coverageRatio >= 0.65 ? "Buena coincidencia" : covered > MENU_COMPARISON_TOLERANCE && excess < covered ? "Coincidencia parcial" : "Poco compatible";
  return {
    score,
    covered: round2(covered),
    missing: round2(missing),
    excess: round2(excess),
    coverageRatio: round2(coverageRatio),
    groupsCovered,
    coveredGroups,
    missingGroups,
    excessGroups,
    mealAffinity,
    blocked,
    label,
    contributions
  };
}

// frontend/src/features/menu/composition.ts
function ingredientsKey(items, factor, ratios = false) {
  const amounts = /* @__PURE__ */ new Map();
  for (const item of items) {
    const key = `${item.food_snapshot.id}:${item.unit}`;
    amounts.set(key, (amounts.get(key) ?? 0) + Number(item.amount) * factor / Number(item.food_snapshot.portion_amount));
  }
  const total = ratios ? [...amounts.values()].reduce((a, b) => a + b, 0) || 1 : 1;
  return [...amounts].sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => [key, Math.round(value / total * (ratios ? 1e3 : 20))]);
}
function preparationKey(recipe) {
  return JSON.stringify(ingredientsKey(recipe.items, 1, true));
}
function entryComposition(entry) {
  if (entry.recipe_snapshot) return ["recipe", ingredientsKey(entry.recipe_snapshot.items, entry.quantity / entry.recipe_snapshot.servings)];
  return ["food", entry.food_snapshot?.id ?? entry.source_id, entry.unit, Math.round(entry.quantity / (Number(entry.food_snapshot?.portion_amount) || 1) * 20)];
}

// frontend/src/features/menu/mesa.ts
var isDrink = (recipe) => recipe.tags?.includes("nuthrick:drink") ?? false;
var isVerifiedWater = (recipe) => recipe.id === "nuthrick-water-v1" && recipe.source === "CDC_PLAIN_WATER" && isDrink(recipe) && recipe.items.length === 0;
var recipeHasKnownContributions = (recipe) => isVerifiedWater(recipe) || recipe.items.length > 0 && Number(recipe.servings) > 0 && recipe.items.every((item) => Number(item.amount) > 0 && Number(item.food_snapshot.portion_amount) > 0 && item.exchange_contribution.length > 0 && item.exchange_contribution.every((c) => Number.isFinite(c.portions) && c.portions > 0));
function menuRestrictions(menu) {
  const rows = Object.entries(menu.food_preferences ?? {});
  return { excludedFoodIds: rows.filter(([, v]) => v === "exclude").map(([id]) => id), likedFoodIds: rows.filter(([, v]) => v === "like").map(([id]) => id), avoidedFoodIds: rows.filter(([, v]) => v === "avoid").map(([id]) => id) };
}
function menuSignature(menu, mealId) {
  return JSON.stringify(activeMenu(menu).meal_menus.filter((m) => !mealId || m.meal_time_id === mealId).sort((a, b) => a.meal_time_id.localeCompare(b.meal_time_id)).map((meal) => [meal.meal_time_id, meal.entries.map(entryComposition).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b)))]));
}

// frontend/src/features/menu/planner.ts
var MENU_PLANNER_WEIGHTS = {
  repetition: 1,
  recipeAdjustment: 3,
  extraComponent: 1.25,
  duplicateGroup: 0,
  sameFamily: 0,
  impracticalQuantity: 2
};
var practicalQuantity = practicalFoodQuantity;
function curatedDailyRecipeBonus(recipe) {
  if (recipe.source === "NUTHRICK_EDITORIAL_PREPARATIONS") return 2;
  if (recipe.source === "NUTHRICK_STARTER_RECIPES") return 1;
  return 0;
}
var familyByGroup = {
  CEREALS_NO_FAT: "cereals",
  CEREALS_WITH_FAT: "cereals",
  AOA_VERY_LOW_FAT: "aoa",
  AOA_LOW_FAT: "aoa",
  AOA_MODERATE_FAT: "aoa",
  AOA_HIGH_FAT: "aoa",
  MILK_SKIM: "milk",
  MILK_SEMI_SKIM: "milk",
  MILK_WHOLE: "milk",
  MILK_WITH_SUGAR: "milk",
  FATS_NO_PROTEIN: "fats",
  FATS_WITH_PROTEIN: "fats"
};
function exchangeGroupFamily(groupCode) {
  return familyByGroup[groupCode] ?? groupCode;
}
function isFoodRestricted(food, restrictions) {
  if (restrictions.excludedFoodIds?.includes(food.id)) return true;
  if (restrictions.excludedGroupCodes?.includes(food.group_code)) return true;
  const excludedAttributes = new Set(restrictions.excludedAttributes ?? []);
  return Object.entries(food.attributes ?? {}).some(([attribute, value]) => value === "contains" && excludedAttributes.has(attribute));
}
function adjustRecipeToPending(recipe, pending) {
  const recipeGroups = new Map(recipeExchangeContributions(recipe).map((item) => [item.group_code, item.portions]));
  const pendingGroups = new Map(pending.map((item) => [item.group_code, item.portions]));
  const amounts = {};
  const factors = [...recipeGroups].map(([code, supplied]) => supplied > 0 ? (pendingGroups.get(code) ?? 0) / supplied : 1).sort((a, b) => a - b);
  const factor = Math.min(2, Math.max(0.5, factors[Math.floor(factors.length / 2)] ?? 1));
  for (const item of recipe.items) {
    amounts[item.id] = Number(item.amount) * factor;
  }
  return adjustRecipeIngredients(recipe, amounts);
}
function recipeAdjustmentPenalty(original, adjusted) {
  return adjusted.items.reduce((penalty, item) => {
    const base = original.items.find((candidate) => candidate.id === item.id);
    if (!base || Number(base.amount) <= 0 || Number(item.amount) <= 0) return penalty;
    return penalty + Math.abs(Math.log(Number(item.amount) / Number(base.amount))) * MENU_PLANNER_WEIGHTS.recipeAdjustment;
  }, 0);
}
function duplicateGroupPenalty(recipe) {
  const counts = /* @__PURE__ */ new Map();
  for (const item of recipe.items) counts.set(item.food_snapshot.group_code, (counts.get(item.food_snapshot.group_code) ?? 0) + 1);
  return [...counts.values()].reduce((sum, count) => sum + Math.max(0, count - 1) * MENU_PLANNER_WEIGHTS.duplicateGroup, 0);
}
function sameFamilyPenalty(recipe) {
  const codesByFamily = /* @__PURE__ */ new Map();
  for (const contribution of recipeExchangeContributions(recipe)) {
    const family2 = exchangeGroupFamily(contribution.group_code);
    const codes = codesByFamily.get(family2) ?? /* @__PURE__ */ new Set();
    codes.add(contribution.group_code);
    codesByFamily.set(family2, codes);
  }
  return [...codesByFamily.values()].reduce((sum, codes) => sum + Math.max(0, codes.size - 1) * MENU_PLANNER_WEIGHTS.sameFamily, 0);
}
function impracticalQuantityPenalty(recipe) {
  return recipe.items.reduce((sum, item) => {
    const practical = practicalQuantity(Number(item.amount), item.unit);
    const reference = Math.max(Number(item.amount), practical, 1e-3);
    return sum + Math.abs(practical - Number(item.amount)) / reference * MENU_PLANNER_WEIGHTS.impracticalQuantity;
  }, 0);
}
function entriesForMeal(menu, mealTimeId) {
  return activeMenu(menu).meal_menus.find((meal) => meal.meal_time_id === mealTimeId)?.entries ?? [];
}
function clearMeal(menu, distribution, mealTimeId, fixedEntryIds) {
  return entriesForMeal(menu, mealTimeId).filter((entry) => !fixedEntryIds.includes(entry.id)).reduce(
    (next, entry) => removeMenuEntry(next, distribution, entry.id),
    menu
  );
}
function pendingForMeal(menu, distribution, mealTimeId) {
  return calculateMenuStatus(menu, distribution).rows.filter((row) => row.meal_time_id === mealTimeId && row.remaining > MENU_COMPARISON_TOLERANCE).map((row) => ({ group_code: row.group_code, portions: row.remaining, used: row.used })).sort((a, b) => Number(a.used > MENU_COMPARISON_TOLERANCE) - Number(b.used > MENU_COMPARISON_TOLERANCE));
}
function rankRecipes(recipes, pending, mealType, restrictions, usedRecipeIds) {
  return recipes.filter((recipe) => recipe.active && !isDrink(recipe) && recipeHasKnownContributions(recipe)).map((original) => {
    const recipe = adjustRecipeToPending(original, pending);
    const match = scoreRecipeCompatibility({ pendingExchanges: pending, recipe, mealType, restrictions });
    const repetitionPenalty = usedRecipeIds.has(original.id) ? MENU_PLANNER_WEIGHTS.repetition : 0;
    const adjustmentPenalty = recipeIngredientsChanged(original, recipe) ? recipeAdjustmentPenalty(original, recipe) : 0;
    const remainingComponents = match.missingGroups.length * MENU_PLANNER_WEIGHTS.extraComponent;
    const practicalityPenalty = duplicateGroupPenalty(recipe) + sameFamilyPenalty(recipe) + impracticalQuantityPenalty(recipe) + remainingComponents;
    const preference = recipe.items.reduce((sum, item) => sum + (restrictions.likedFoodIds?.includes(item.food_snapshot.id) ? 2 : 0) - (restrictions.avoidedFoodIds?.includes(item.food_snapshot.id) ? 3 : 0), 0);
    return { original, recipe, match, score: match.score - repetitionPenalty - adjustmentPenalty - practicalityPenalty + preference + curatedDailyRecipeBonus(original) };
  }).filter((candidate) => !candidate.match.blocked).sort((a, b) => b.score - a.score || a.original.name.localeCompare(b.original.name, "es-MX"));
}
function chooseFood(foods, groupCode, neededPortions, restrictions, usedFoodIds, alternative) {
  const candidates = foods.filter((food) => food.active && food.group_code === groupCode && !isFoodRestricted(food, restrictions)).map((food) => {
    const quantity = practicalQuantity(neededPortions * Number(food.portion_amount), food.portion_unit);
    const supplied = quantity / Number(food.portion_amount);
    return { food, quantity, excess: Math.max(0, supplied - neededPortions), mismatch: Math.abs(supplied - neededPortions) };
  }).sort((a, b) => a.mismatch - b.mismatch || Number(restrictions.avoidedFoodIds?.includes(a.food.id) ?? false) - Number(restrictions.avoidedFoodIds?.includes(b.food.id) ?? false) || Number(restrictions.likedFoodIds?.includes(b.food.id) ?? false) - Number(restrictions.likedFoodIds?.includes(a.food.id) ?? false) || Number(usedFoodIds.has(a.food.id)) - Number(usedFoodIds.has(b.food.id)) || Number(b.food.is_custom) - Number(a.food.is_custom) || b.food.use_count - a.food.use_count || a.food.name.localeCompare(b.food.name, "es-MX"));
  const comparable = candidates.filter((c) => c.mismatch <= (candidates[0]?.mismatch ?? 0) + MENU_COMPARISON_TOLERANCE);
  return comparable[alternative % Math.max(1, comparable.length)];
}
function proposeMeal(menu, distribution, mealTimeId, foods, recipes, restrictions, usedRecipeIds, usedFoodIds, alternative) {
  const meal = distribution.meal_times.find((item) => item.id === mealTimeId);
  if (!meal) return menu;
  let next = menu;
  let pending = pendingForMeal(next, distribution, mealTimeId);
  if (!pending.length) return next;
  const ranked = rankRecipes(recipes, pending, meal.meal_type, restrictions, usedRecipeIds);
  const viable = ranked.filter((candidate) => candidate.match.covered >= 1 && candidate.match.excess <= 0.25 && candidate.score > 0 && candidate.match.label !== "Poco compatible");
  const comparable = viable.filter((candidate) => candidate.score >= (viable[0]?.score ?? 0) - 5);
  const best = alternative % 4 === 3 ? void 0 : comparable[alternative % Math.max(1, comparable.length)];
  if (best) {
    next = addRecipeToMenu(next, distribution, mealTimeId, best.recipe, 1, `proposal-recipe-${mealTimeId}-${entriesForMeal(next, mealTimeId).length}`);
    usedRecipeIds.add(best.original.id);
    for (const item of best.recipe.items) usedFoodIds.add(item.food_item_id ?? item.food_snapshot.id);
    pending = pendingForMeal(next, distribution, mealTimeId);
  }
  let remainingSeed = alternative;
  for (const missing of pending) {
    const selection = chooseFood(foods, missing.group_code, missing.portions, restrictions, usedFoodIds, remainingSeed);
    if (!selection) continue;
    const radix = Math.max(1, foods.filter((food) => food.active && food.group_code === missing.group_code && !isFoodRestricted(food, restrictions)).length);
    remainingSeed = Math.floor(remainingSeed / radix);
    next = addFoodToMenu(next, distribution, mealTimeId, selection.food, selection.quantity, `proposal-food-${mealTimeId}-${missing.group_code}-${entriesForMeal(next, mealTimeId).length}`);
    usedFoodIds.add(selection.food.id);
  }
  if (best) {
    const direct = proposeMeal(menu, distribution, mealTimeId, foods, [], restrictions, new Set(usedRecipeIds), new Set(usedFoodIds), alternative);
    const error = (value) => calculateMenuStatus(value, distribution).rows.filter((row) => row.meal_time_id === mealTimeId).reduce((sum, row) => sum + Math.abs(row.remaining), 0);
    const hasExcess = calculateMenuStatus(next, distribution).rows.some((row) => row.meal_time_id === mealTimeId && row.state === "excess");
    if (error(direct) + (hasExcess ? MENU_COMPARISON_TOLERANCE : 0.25) < error(next)) return direct;
  }
  return next;
}
function proposeDietMenu({
  menu,
  distribution,
  foods,
  recipes,
  mealTimeId = null,
  mode = "complete",
  restrictions = {},
  alternative = 0,
  fixedEntryIds = [],
  fixedMealIds = [],
  rejectedFoodIds = [],
  rejectedPreparations = []
}) {
  const targets = distribution.meal_times.filter((meal) => !mealTimeId || meal.id === mealTimeId).filter((meal) => !fixedMealIds.includes(meal.id)).sort((a, b) => a.display_order - b.display_order);
  let next = menu;
  if (mode === "replace") for (const meal of targets) next = clearMeal(next, distribution, meal.id, fixedEntryIds);
  const usedRecipeIds = new Set(activeMenu(next).meal_menus.flatMap((meal) => meal.entries.filter((entry) => entry.type === "recipe").map((entry) => entry.source_id)));
  const usedFoodIds = new Set(activeMenu(next).meal_menus.flatMap((meal) => meal.entries.flatMap((entry) => entry.type === "food" ? [entry.source_id] : entry.recipe_snapshot?.items.map((item) => item.food_snapshot.id) ?? [])));
  const beforeEntries = new Map(activeMenu(next).meal_menus.flatMap((meal) => meal.entries.map((entry) => [entry.id, JSON.stringify(entry)])));
  const eligibleFoods = foods.filter((food) => !rejectedFoodIds.includes(food.id));
  const eligibleRecipes = recipes.filter((recipe) => !rejectedPreparations.includes(preparationKey(recipe)) && !recipe.items.some((item) => rejectedFoodIds.includes(item.food_snapshot.id)));
  for (const meal of targets) next = proposeMeal(next, distribution, meal.id, eligibleFoods, eligibleRecipes, restrictions, usedRecipeIds, usedFoodIds, alternative);
  const status = calculateMenuStatus(next, distribution);
  const meals = targets.map((meal) => {
    const rows = status.rows.filter((row) => row.meal_time_id === meal.id);
    return {
      mealTimeId: meal.id,
      mealName: meal.display_name,
      addedEntries: entriesForMeal(next, meal.id).filter((entry) => beforeEntries.get(entry.id) !== JSON.stringify(entry)),
      pending: rows.filter((row) => row.remaining > MENU_COMPARISON_TOLERANCE).map((row) => ({ group_code: row.group_code, portions: row.remaining })),
      excess: rows.filter((row) => row.remaining < -MENU_COMPARISON_TOLERANCE).map((row) => ({ group_code: row.group_code, portions: -row.remaining })),
      complete: rows.length > 0 && rows.every((row) => row.state === "complete")
    };
  });
  return {
    menu: next,
    mode,
    mealTimeId,
    meals,
    exact: meals.every((meal) => meal.complete),
    algorithm: "deterministic-menu-planner-v4"
  };
}

// frontend/src/features/exchanges/suggestion.ts
var EXCHANGE_SUGGESTION_ALGORITHM_VERSION = "EXCHANGE_SUGGESTION_V3";
var EXCHANGE_SUGGESTION_INCREMENT = 0.5;
var EXCHANGE_SUGGESTION_WEIGHTS = {
  energyKcal: 0.5,
  carbohydrateG: 1,
  proteinG: 1,
  fatG: 1
};
var EXCHANGE_SUGGESTION_GROUP_TIERS = {
  VEGETABLES: "priority",
  FRUITS: "priority",
  CEREALS_NO_FAT: "priority",
  CEREALS_WITH_FAT: "secondary",
  LEGUMES: "priority",
  AOA_VERY_LOW_FAT: "priority",
  AOA_LOW_FAT: "priority",
  AOA_MODERATE_FAT: "priority",
  AOA_HIGH_FAT: "secondary",
  MILK_SKIM: "complementary",
  MILK_SEMI_SKIM: "complementary",
  MILK_WHOLE: "secondary",
  MILK_WITH_SUGAR: "discretionary",
  FATS_NO_PROTEIN: "complementary",
  FATS_WITH_PROTEIN: "secondary",
  SUGARS_NO_FAT: "discretionary",
  SUGARS_WITH_FAT: "discretionary"
};
var EXCHANGE_SUGGESTION_LIMITS = {
  VEGETABLES: 10,
  FRUITS: 10,
  CEREALS_NO_FAT: 16,
  CEREALS_WITH_FAT: 8,
  LEGUMES: 8,
  AOA_VERY_LOW_FAT: 14,
  AOA_LOW_FAT: 12,
  AOA_MODERATE_FAT: 10,
  AOA_HIGH_FAT: 8,
  MILK_SKIM: 8,
  MILK_SEMI_SKIM: 8,
  MILK_WHOLE: 6,
  MILK_WITH_SUGAR: 5,
  FATS_NO_PROTEIN: 12,
  FATS_WITH_PROTEIN: 8,
  SUGARS_NO_FAT: 8,
  SUGARS_WITH_FAT: 6
};
var EXCHANGE_SUGGESTION_SCORE_WEIGHTS = {
  foodPriorityPerPortion: { priority: 2e-4, complementary: 3e-3, secondary: 0.18, discretionary: 0.24 },
  avoidedGroupPerPortion: 0.18,
  missingIncludedGroup: 0.09,
  diversityShortfall: 0.08,
  legumeOpportunity: 0.018,
  activePriorityShortfall: 8e-3,
  discretionaryUnlockNutritionError: 0.14,
  discretionaryMinimumImprovement: 0.04,
  concentrationStart: 0.4,
  concentrationWeight: 0.35,
  diversityWeight: 0.012,
  highPortionWeight: 4e-3,
  improvementEpsilon: 1e-9
};
var round3 = (value) => Math.round(value * 1e8) / 1e8;
var normalizedError = (actual, target) => Math.abs(actual - target) / Math.max(Math.abs(target), 1);
function totalsFor(portions, catalog) {
  return portions.reduce((total, portion, index) => {
    const group2 = catalog[index];
    return {
      energy_kcal: total.energy_kcal + portion * group2.energyKcal,
      carbohydrate_g: total.carbohydrate_g + portion * group2.carbohydrateG,
      protein_g: total.protein_g + portion * group2.proteinG,
      fat_g: total.fat_g + portion * group2.fatG
    };
  }, { energy_kcal: 0, carbohydrate_g: 0, protein_g: 0, fat_g: 0 });
}
function scoreFor(portions, catalog, targets, weights, limits, preferences) {
  const totals = totalsFor(portions, catalog);
  const fit = normalizedError(totals.energy_kcal, targets.energy_kcal) * weights.energyKcal + normalizedError(totals.carbohydrate_g, targets.carbohydrate_g) * weights.carbohydrateG + normalizedError(totals.protein_g, targets.protein_g) * weights.proteinG + normalizedError(totals.fat_g, targets.fat_g) * weights.fatG;
  const totalPortions = portions.reduce((sum, portion) => sum + portion, 0);
  let practicalityPenalty = 0;
  let foodPriorityPenalty = 0;
  let preferencePenalty = 0;
  let concentration = 0;
  portions.forEach((portion, index) => {
    const code = catalog[index].groupCode;
    const preference = preferences[code];
    if (preference === "include") {
      if (portion <= 0) preferencePenalty += EXCHANGE_SUGGESTION_SCORE_WEIGHTS.missingIncludedGroup;
    } else if (preference === "avoid") {
      preferencePenalty += portion * EXCHANGE_SUGGESTION_SCORE_WEIGHTS.avoidedGroupPerPortion;
    } else {
      foodPriorityPenalty += portion * EXCHANGE_SUGGESTION_SCORE_WEIGHTS.foodPriorityPerPortion[EXCHANGE_SUGGESTION_GROUP_TIERS[code]];
    }
    const softCeiling = limits[code] * 0.65;
    if (portion > softCeiling) practicalityPenalty += (portion - softCeiling) ** 2 * EXCHANGE_SUGGESTION_SCORE_WEIGHTS.highPortionWeight;
    if (totalPortions >= 4 && portion > 0) {
      const share = portion / totalPortions;
      concentration += share ** 2 * EXCHANGE_SUGGESTION_SCORE_WEIGHTS.diversityWeight;
      if (share > EXCHANGE_SUGGESTION_SCORE_WEIGHTS.concentrationStart)
        concentration += (share - EXCHANGE_SUGGESTION_SCORE_WEIGHTS.concentrationStart) ** 2 * EXCHANGE_SUGGESTION_SCORE_WEIGHTS.concentrationWeight;
    }
  });
  const portionFor = (code) => {
    const index = catalog.findIndex((group2) => group2.groupCode === code);
    return index >= 0 ? portions[index] : 0;
  };
  const catalogCodes = new Set(catalog.map((group2) => group2.groupCode));
  const canUse = (codes) => codes.some((code) => catalogCodes.has(code) && preferences[code] !== "exclude");
  const shortfall = (actual, minimum) => Math.max(0, minimum - actual) ** 2 * EXCHANGE_SUGGESTION_SCORE_WEIGHTS.diversityShortfall;
  let diversityPenalty = 0;
  if (canUse(["VEGETABLES"])) diversityPenalty += shortfall(portionFor("VEGETABLES"), 1);
  if (canUse(["FRUITS"])) diversityPenalty += shortfall(portionFor("FRUITS"), 1);
  if (canUse(["CEREALS_NO_FAT", "CEREALS_WITH_FAT"])) diversityPenalty += shortfall(portionFor("CEREALS_NO_FAT") + portionFor("CEREALS_WITH_FAT"), 1);
  const proteinCodes = ["LEGUMES", "AOA_VERY_LOW_FAT", "AOA_LOW_FAT", "AOA_MODERATE_FAT", "AOA_HIGH_FAT"];
  if (canUse(proteinCodes)) diversityPenalty += shortfall(proteinCodes.reduce((sum, code) => sum + portionFor(code), 0), 1);
  if (preferences.LEGUMES === "auto" && targets.carbohydrate_g >= 80 && targets.protein_g >= 40 && portionFor("LEGUMES") === 0) {
    diversityPenalty += EXCHANGE_SUGGESTION_SCORE_WEIGHTS.legumeOpportunity;
  }
  const activePriorityGroups = catalog.filter((group2, index) => EXCHANGE_SUGGESTION_GROUP_TIERS[group2.groupCode] === "priority" && preferences[group2.groupCode] !== "exclude" && portions[index] > 0).length;
  diversityPenalty += Math.max(0, 4 - activePriorityGroups) ** 2 * EXCHANGE_SUGGESTION_SCORE_WEIGHTS.activePriorityShortfall;
  return {
    score: fit + diversityPenalty + practicalityPenalty + foodPriorityPenalty + preferencePenalty + concentration,
    nutritionError: fit,
    totals
  };
}
function snap(value, increment, maximum) {
  if (!Number.isFinite(value) || value <= 0) return 0;
  return Math.min(maximum, round3(Math.round(value / increment) * increment));
}
function suggestExchangePrescription({
  targets,
  exchangeCatalog: exchangeCatalog2 = exchangeCatalog,
  currentPortions = [],
  options = {}
}) {
  const increment = options.increment && options.increment > 0 ? options.increment : EXCHANGE_SUGGESTION_INCREMENT;
  const maxIterations = options.maxIterations ?? 500;
  const weights = { ...EXCHANGE_SUGGESTION_WEIGHTS, ...options.weights };
  const configuredLimits = { ...EXCHANGE_SUGGESTION_LIMITS, ...options.limits };
  const preferences = Object.fromEntries(exchangeCatalog.map((group2) => [group2.groupCode, options.groupPreferences?.[group2.groupCode] ?? "auto"]));
  const current = new Map(currentPortions.map((item) => [item.groupCode ?? item.group_code, item.portions]));
  const locked = new Map(Object.entries(options.lockedGroups ?? {}));
  for (const group2 of exchangeCatalog2) if (preferences[group2.groupCode] === "exclude") locked.set(group2.groupCode, 0);
  const conservativeLimits = { ...configuredLimits };
  for (const group2 of exchangeCatalog2) {
    const currentValue = current.get(group2.groupCode) ?? 0;
    if (EXCHANGE_SUGGESTION_GROUP_TIERS[group2.groupCode] === "discretionary" && preferences[group2.groupCode] === "auto" && !(options.startFromCurrent && currentValue > 0)) {
      conservativeLimits[group2.groupCode] = 0;
    }
  }
  const initialPortions = exchangeCatalog2.map((group2) => {
    const lockedValue = locked.get(group2.groupCode);
    if (lockedValue !== void 0) return lockedValue;
    return options.startFromCurrent ? snap(current.get(group2.groupCode) ?? 0, increment, conservativeLimits[group2.groupCode]) : 0;
  });
  const optimize = (startingPortions, limits, iterationLimit, searchPreferences = preferences) => {
    let portions2 = [...startingPortions];
    let evaluated2 = scoreFor(portions2, exchangeCatalog2, targets, weights, limits, searchPreferences);
    let iterations2 = 0;
    while (iterations2 < iterationLimit) {
      let bestScore = evaluated2.score;
      let bestPortions = null;
      const consider = (candidate) => {
        const result = scoreFor(candidate, exchangeCatalog2, targets, weights, limits, searchPreferences);
        if (result.score < bestScore - EXCHANGE_SUGGESTION_SCORE_WEIGHTS.improvementEpsilon) {
          bestScore = result.score;
          bestPortions = candidate;
        }
      };
      for (let index = 0; index < exchangeCatalog2.length; index += 1) {
        const code = exchangeCatalog2[index].groupCode;
        if (locked.has(code)) continue;
        if (portions2[index] + increment <= limits[code]) {
          const candidate = [...portions2];
          candidate[index] = round3(candidate[index] + increment);
          consider(candidate);
        }
        if (portions2[index] >= increment) {
          const candidate = [...portions2];
          candidate[index] = round3(candidate[index] - increment);
          consider(candidate);
        }
      }
      for (let from = 0; from < exchangeCatalog2.length; from += 1) {
        if (locked.has(exchangeCatalog2[from].groupCode) || portions2[from] < increment) continue;
        for (let to = 0; to < exchangeCatalog2.length; to += 1) {
          const toCode = exchangeCatalog2[to].groupCode;
          if (from === to || locked.has(toCode) || portions2[to] + increment > limits[toCode]) continue;
          const candidate = [...portions2];
          candidate[from] = round3(candidate[from] - increment);
          candidate[to] = round3(candidate[to] + increment);
          consider(candidate);
        }
      }
      if (!bestPortions) break;
      portions2 = bestPortions;
      evaluated2 = scoreFor(portions2, exchangeCatalog2, targets, weights, limits, searchPreferences);
      iterations2 += 1;
    }
    return { portions: portions2, evaluated: evaluated2, iterations: iterations2 };
  };
  let optimized = optimize(initialPortions, conservativeLimits, maxIterations);
  const hasLockedAutoDiscretionary = exchangeCatalog2.some((group2) => conservativeLimits[group2.groupCode] === 0 && configuredLimits[group2.groupCode] > 0);
  if (hasLockedAutoDiscretionary && optimized.evaluated.nutritionError > EXCHANGE_SUGGESTION_SCORE_WEIGHTS.discretionaryUnlockNutritionError) {
    const unlockedPreferences = { ...preferences };
    for (const group2 of exchangeCatalog2) if (EXCHANGE_SUGGESTION_GROUP_TIERS[group2.groupCode] === "discretionary" && preferences[group2.groupCode] === "auto") unlockedPreferences[group2.groupCode] = "include";
    const unlocked = optimize(optimized.portions, configuredLimits, Math.max(1, maxIterations - optimized.iterations), unlockedPreferences);
    const relevantImprovement = optimized.evaluated.nutritionError - unlocked.evaluated.nutritionError >= EXCHANGE_SUGGESTION_SCORE_WEIGHTS.discretionaryMinimumImprovement;
    if (relevantImprovement) {
      optimized = { portions: unlocked.portions, evaluated: scoreFor(unlocked.portions, exchangeCatalog2, targets, weights, configuredLimits, preferences), iterations: optimized.iterations + unlocked.iterations };
    }
  }
  const { portions, evaluated, iterations } = optimized;
  const totals = Object.fromEntries(Object.entries(evaluated.totals).map(([key, value]) => [key, round3(value)]));
  const differences = {
    energy_kcal: round3(totals.energy_kcal - targets.energy_kcal),
    carbohydrate_g: round3(totals.carbohydrate_g - targets.carbohydrate_g),
    protein_g: round3(totals.protein_g - targets.protein_g),
    fat_g: round3(totals.fat_g - targets.fat_g)
  };
  return {
    groups: exchangeCatalog2.map((group2, index) => ({ groupCode: group2.groupCode, portions: portions[index] })),
    totals,
    differences,
    score: evaluated.score,
    metadata: { algorithmVersion: EXCHANGE_SUGGESTION_ALGORITHM_VERSION, increment, iterations }
  };
}

// frontend/src/features/diet-workshop/proposals.ts
var PROPOSAL_POLICY = { comparableError: 0.035, maximumError: 0.15, inventoryEpsilon: 1e-7, candidates: 18 };
var family = (code) => code.startsWith("AOA_") ? "AOA" : code.startsWith("MILK_") ? "MILK" : code.startsWith("CEREALS_") ? "CEREALS" : code;
var priority = (code) => family(code) === "AOA" ? 0 : family(code) === "CEREALS" ? 1 : code === "LEGUMES" ? 2 : code === "FRUITS" ? 3 : 4;
var round4 = (n) => Math.round(n * 1e8) / 1e8;
var exchangeKey = (p) => JSON.stringify(p.groups.map((g) => [g.groupCode, g.portions]).sort());
var mealKey = (p) => JSON.stringify(p.distribution.filter((e) => e.portions > 0).map((e) => [e.meal_time_id, e.group_code, e.portions]).sort());
var maxError = (p, targets) => Math.max(...Object.entries(p.differences).map(([key, value]) => Math.abs(value) / Math.max(1, targets[key])));
function everydayRecipePriority(recipe, meal) {
  const groups = new Set(recipeExchangeContributions(recipe).map((item) => item.group_code));
  const has = (code) => groups.has(code);
  const hasAoa = [...groups].some((code) => code.startsWith("AOA_"));
  const hasMilk = [...groups].some((code) => code.startsWith("MILK_"));
  let score = recipe.source === "NUTHRICK_EDITORIAL_PREPARATIONS" ? 8 : recipe.source === "NUTHRICK_STARTER_RECIPES" ? 5 : 0;
  score += recipe.meal_types.includes(meal.meal_type) ? 6 : -20;
  if (meal.meal_type === "BREAKFAST") score += (has("CEREALS_NO_FAT") ? 3 : 0) + (hasAoa ? 3 : 0) + (has("FRUITS") ? 2 : 0) + (hasMilk ? 1 : 0);
  if (meal.meal_type === "MAIN_MEAL") score += (hasAoa ? 3 : 0) + (has("VEGETABLES") ? 3 : 0) + (has("CEREALS_NO_FAT") || has("LEGUMES") ? 2 : 0);
  if (meal.meal_type === "DINNER") score += (hasAoa ? 3 : 0) + (has("CEREALS_NO_FAT") || has("LEGUMES") ? 2 : 0) + (has("VEGETABLES") ? 2 : 0);
  return score;
}
function preparationQuality(groups, catalog) {
  const active = groups.filter((g) => g.portions > 0);
  const milk = active.filter((g) => family(g.groupCode) === "MILK").length;
  const families = new Set(active.map((g) => family(g.groupCode)));
  let penalty = active.length * 0.1 + Math.max(0, milk - 1) * 3;
  for (const g of active) {
    const comfortable = family(g.groupCode) === "CEREALS" || family(g.groupCode) === "AOA" ? 8 : 4;
    penalty += Math.max(0, g.portions - comfortable) ** 2 * 0.15;
  }
  penalty += active.filter((g) => g.portions < 0.5).length;
  penalty += Math.max(0, active.filter((g) => family(g.groupCode) === "AOA").length - 2) * 0.8;
  if (catalog?.foods.length) penalty += active.filter((g) => !catalog.foods.some((f) => f.active && f.group_code === g.groupCode)).length * 4;
  if (catalog?.foods.length) for (const g of active) {
    const foods = catalog.foods.filter((f) => f.active && f.group_code === g.groupCode && f.portion_amount > 0);
    if (foods.length && !foods.some((f) => Math.abs(practicalQuantity(g.portions * f.portion_amount, f.portion_unit) / f.portion_amount - g.portions) <= 0.1)) penalty += 0.5;
  }
  if (families.has("AOA") && families.has("CEREALS")) penalty -= 0.2;
  if (families.has("LEGUMES") && families.has("CEREALS")) penalty -= 0.2;
  if (catalog?.recipes.some((recipe) => recipe.active && recipeExchangeContributions(recipe).every((c) => (active.find((g) => g.groupCode === c.group_code)?.portions ?? 0) >= c.portions))) penalty -= 0.5;
  return penalty;
}
function exchangeAlternatives(input, catalog, configuredMeals) {
  const options = input.options ?? {};
  for (const [code, value] of Object.entries(options.lockedGroups ?? {})) {
    if (!Number.isFinite(value) || value < 0) throw new Error(`Revisa la cantidad fijada de ${getExchangeGroup(code).shortName}.`);
    if (value > 0 && options.groupPreferences?.[code] === "exclude") throw new Error(`${getExchangeGroup(code).shortName} est\xE1 fijado y excluido. Libera su cantidad o cambia la exclusi\xF3n.`);
  }
  const found = /* @__PURE__ */ new Map();
  const codes = [...exchangeCatalog].sort((a, b) => priority(a.groupCode) - priority(b.groupCode));
  const base = suggestExchangePrescription(input);
  found.set(exchangeKey(base), base);
  for (let i = 0; i < PROPOSAL_POLICY.candidates; i++) {
    const seed = codes[i % codes.length].groupCode;
    const preferences = { ...options.groupPreferences };
    if (i < 4) for (const g of codes.filter((g2) => family(g2.groupCode) === "MILK")) {
      if (!preferences[g.groupCode] && options.lockedGroups?.[g.groupCode] === void 0 && (i === 0 || g.groupCode !== ["MILK_SKIM", "MILK_SEMI_SKIM", "MILK_WHOLE"][i - 1])) preferences[g.groupCode] = "exclude";
    }
    const limits = { ...options.limits };
    if (i >= 4 && i < 10 && options.lockedGroups?.LEGUMES === void 0 && preferences.LEGUMES !== "include") limits.LEGUMES = Math.min(limits.LEGUMES ?? Infinity, i % 2 ? 4 : 3);
    if (i >= 4 && i < 10) for (const g of codes.filter((g2) => family(g2.groupCode) === "MILK")) {
      if (options.lockedGroups?.[g.groupCode] === void 0 && preferences[g.groupCode] !== "include") limits[g.groupCode] = Math.min(limits[g.groupCode] ?? Infinity, i % 3);
    }
    if (i >= 10) {
      for (const [code, cap] of [["FRUITS", 3 + i % 3], ["LEGUMES", 2 + i % 3], ["MILK_SKIM", i % 3], ["MILK_SEMI_SKIM", i % 3], ["MILK_WHOLE", i % 3]]) {
        if (options.lockedGroups?.[code] === void 0 && preferences[code] !== "include") limits[code] = Math.min(limits[code] ?? Infinity, cap);
      }
    }
    const p = suggestExchangePrescription({ ...input, currentPortions: options.startFromCurrent ? input.currentPortions : [{ groupCode: seed, portions: 2 }], options: { ...options, limits, startFromCurrent: true, groupPreferences: preferences } });
    found.set(exchangeKey(p), p);
  }
  const all = [...found.values()];
  const best = Math.min(...all.map((p) => maxError(p, input.targets)));
  if (best > PROPOSAL_POLICY.maximumError) throw new Error("No encontramos una propuesta cercana a los objetivos con estas condiciones. Revisa las cantidades fijadas, las exclusiones o ajusta manualmente el cuadro.");
  const meals = configuredMeals ?? createMealDistribution();
  const candidates = all.filter((p) => maxError(p, input.targets) <= Math.min(PROPOSAL_POLICY.maximumError, best + PROPOSAL_POLICY.comparableError));
  const quality = new Map(candidates.map((p) => {
    const prescription = applyExchangeSuggestion(createExchangePrescription(input.targets), input.targets, p);
    const distribution = mealAlternatives(meals, prescription, [], false, catalog)[0];
    return [p, preparationQuality(p.groups, catalog) + (distribution ? distributionQuality(distribution, meals, catalog) * 0.2 : 10)];
  }));
  return candidates.sort((a, b) => quality.get(a) - quality.get(b) || maxError(a, input.targets) - maxError(b, input.targets));
}
function mealAlternatives(current, prescription, lockedIds, startFromCurrent, catalog) {
  const meals = [...current.meal_times].sort((a, b) => a.display_order - b.display_order);
  const fixed = current.distribution.filter((e) => lockedIds.includes(e.meal_time_id));
  const free = meals.filter((m) => !lockedIds.includes(m.id));
  for (const entry of fixed) {
    if (!Number.isFinite(entry.portions) || entry.portions < 0) throw new Error("Revisa las cantidades del tiempo conservado.");
    const available = prescription.groups.find((g) => g.group_code === entry.group_code)?.portions ?? 0;
    const used = fixed.filter((e) => e.group_code === entry.group_code).reduce((s, e) => s + e.portions, 0);
    if (used > available + PROPOSAL_POLICY.inventoryEpsilon) throw new Error(`${getExchangeGroup(entry.group_code).shortName} excede el inventario en los tiempos conservados. Libera uno de esos tiempos o revisa Equivalentes.`);
  }
  const found = /* @__PURE__ */ new Map();
  for (let variant = 0; variant < PROPOSAL_POLICY.candidates; variant++) {
    const entries = fixed.map((e) => ({ ...e }));
    const put = (code, id, n) => {
      if (n <= 0) return;
      const e = entries.find((e2) => e2.group_code === code && e2.meal_time_id === id);
      if (e) e.portions = round4(e.portions + n);
      else entries.push({ group_code: code, meal_time_id: id, portions: n });
    };
    const inventory = new Map(prescription.groups.map((g) => [g.group_code, round4(g.portions - fixed.filter((e) => e.group_code === g.group_code).reduce((s, e) => s + e.portions, 0))]));
    if (!free.length && [...inventory.values()].some((n) => n > PROPOSAL_POLICY.inventoryEpsilon)) throw new Error("Todos los tiempos est\xE1n conservados y quedan porciones pendientes. Libera un tiempo para distribuirlas.");
    const recipeCandidates = (catalog?.recipes ?? []).filter((recipe) => recipe.active && !recipe.tags.includes("nuthrick:drink") && recipeExchangeContributions(recipe).length > 1 && recipeExchangeContributions(recipe).every((c) => (inventory.get(c.group_code) ?? 0) >= c.portions)).flatMap((recipe) => free.filter((meal) => recipe.meal_types.includes(meal.meal_type)).map((meal) => ({ recipe, meal, score: everydayRecipePriority(recipe, meal) }))).sort((a, b) => b.score - a.score || a.recipe.name.localeCompare(b.recipe.name, "es-MX") || a.meal.display_order - b.meal.display_order);
    if (recipeCandidates.length) {
      const selected = recipeCandidates[variant % recipeCandidates.length];
      for (const contribution of recipeExchangeContributions(selected.recipe)) {
        put(contribution.group_code, selected.meal.id, contribution.portions);
        inventory.set(contribution.group_code, round4((inventory.get(contribution.group_code) ?? 0) - contribution.portions));
      }
    }
    for (const [code, total] of [...inventory].sort(([a], [b]) => priority(a) - priority(b))) {
      if (total <= PROPOSAL_POLICY.inventoryEpsilon || !free.length) continue;
      const ranked = [...free].sort((a, b) => {
        const score = (m) => {
          const present = entries.filter((e) => e.meal_time_id === m.id && e.portions > 0);
          const has = (f) => present.some((e) => family(e.group_code) === f);
          let s = m.meal_type === "SNACK" ? -3 : 0;
          if (code === "FRUITS" || family(code) === "MILK") s += m.meal_type === "SNACK" || m.meal_type === "BREAKFAST" ? 3 : 0;
          if (code === "AOA_MODERATE_FAT" && m.meal_type === "BREAKFAST") s += 3;
          if ((code === "LEGUMES" || family(code) === "CEREALS") && has("AOA")) s += 3;
          if (code === "LEGUMES" && has("CEREALS")) s += 2;
          if (family(code) === "MILK" && present.some((e) => family(e.group_code) === "MILK" && e.group_code !== code)) s -= 10;
          if (startFromCurrent && current.distribution.some((e) => e.meal_time_id === m.id && e.group_code === code && e.portions > 0)) s += 1;
          s += (m.display_order + variant) % Math.max(free.length, 1) * 1.2;
          s -= present.reduce((sum, e) => sum + e.portions, 0) * 0.4;
          return s;
        };
        return score(b) - score(a) || a.display_order - b.display_order;
      });
      const count = Math.min(ranked.length, Math.max(1, Math.ceil(total / (variant % 2 ? 4 : 3))));
      let remaining = total;
      for (let i = 0; i < count; i++) {
        const n = i === count - 1 ? remaining : Math.floor(remaining / (count - i) * 2) / 2;
        put(code, ranked[i].id, n);
        remaining = round4(remaining - n);
      }
    }
    const p = { distribution: entries, derived_meal_totals: calculateDerivedMealTotals(entries, meals), metadata: { algorithm: "MEAL_PREPARATION_V2", generated_at: (/* @__PURE__ */ new Date()).toISOString(), base: startFromCurrent ? "current" : "zero" } };
    found.set(mealKey(p), p);
  }
  return [...found.values()].sort((a, b) => distributionQuality(a, current, catalog) - distributionQuality(b, current, catalog));
}
function distributionQuality(p, current, catalog) {
  const total = p.distribution.reduce((s, e) => s + e.portions, 0);
  return current.meal_times.reduce((sum, m) => {
    const entries = p.distribution.filter((e) => e.meal_time_id === m.id);
    const amount = entries.reduce((s, e) => s + e.portions, 0);
    const emptyMeal = m.meal_type !== "SNACK" && !entries.length && total >= current.meal_times.length ? 5 : 0;
    const concentration = Math.max(0, amount / Math.max(total, 1) - 0.5) * 15;
    return sum + preparationQuality(entries.map((e) => ({ groupCode: e.group_code, portions: e.portions })), catalog) + emptyMeal + concentration;
  }, 0);
}

// frontend/src/features/diet-workshop/aiEngine.ts
function workshopTargets(plan) {
  const m = plan.macro_distribution?.macros;
  const t = { energy_kcal: plan.target_calories ?? 0, carbohydrate_g: m?.CARBOHYDRATE?.grams ?? -1, protein_g: m?.PROTEIN?.grams ?? -1, fat_g: m?.FAT?.grams ?? -1 };
  if (!Object.values(t).every((n) => Number.isFinite(n) && n > 0)) throw new Error("targets_required");
  return t;
}
function buildWorkshopOptions(plan, rawFoods, rawRecipes, rejectedFoodIds = [], rejectedSignatures = []) {
  const targets = workshopTargets(plan);
  const distribution = plan.meal_distribution ?? createMealDistribution();
  const restrictions = plan.diet_menu ? menuRestrictions(plan.diet_menu) : {};
  const validCodes = new Set(exchangeCatalog.map((g) => g.groupCode));
  const foods = rawFoods.filter((f) => f.active && validCodes.has(f.group_code) && f.portion_amount > 0 && !rejectedFoodIds.includes(f.id) && !isFoodRestricted(f, restrictions));
  const recipes = rawRecipes.filter((r) => r.active && r.items?.length && r.items.every((i) => foods.some((f) => f.id === i.food_item_id && f.portion_unit === i.unit) && i.amount > 0)).map((r) => ({ ...r, items: r.items.map((i) => {
    const f = foods.find((f2) => f2.id === i.food_item_id);
    return { ...i, food_snapshot: createFoodSnapshot(f), exchange_contribution: exchangeContributionForFood(f, i.amount) };
  }) }));
  const groupPreferences = Object.fromEntries(exchangeCatalog.filter((g) => !foods.some((f) => f.group_code === g.groupCode)).map((g) => [g.groupCode, "exclude"]));
  const inventory = exchangeAlternatives({ targets, options: { groupPreferences } }, { foods, recipes }, distribution);
  const options = [];
  for (const exchange of inventory.slice(0, 3)) {
    const prescription = applyExchangeSuggestion(createExchangePrescription(targets), targets, exchange);
    for (const meal of mealAlternatives(distribution, prescription, [], false, { foods, recipes }).slice(0, 3)) {
      const meals = applyMealDistributionSuggestion(distribution, meal);
      if (!calculateDistributionStatus(meals.distribution, prescription).canConfirm) continue;
      const proposal = proposeDietMenu({ menu: createDietMenu(meals), distribution: meals, foods, recipes, restrictions, mode: "replace", rejectedFoodIds, alternative: rejectedSignatures.length });
      if (!proposal.exact || !calculateMenuStatus(proposal.menu, meals).canConfirm) continue;
      const signature = menuSignature(proposal.menu);
      if (rejectedSignatures.includes(signature) || options.some((o) => o.signature === signature)) continue;
      options.push({ exchange_prescription: prescription, meal_distribution: meals, diet_menu: { ...proposal.menu, food_preferences: plan.diet_menu?.food_preferences }, signature });
      if (options.length === 3) return options;
    }
  }
  return options;
}
function compactWorkshopOption(option, index) {
  return {
    option: index,
    exchanges: option.exchange_prescription.groups.filter((g) => g.portions > 0),
    totals: option.exchange_prescription.derived_totals,
    meals: activeMenu(option.diet_menu).meal_menus.map((m) => ({
      name: option.meal_distribution.meal_times.find((t) => t.id === m.meal_time_id)?.display_name,
      foods: m.entries.map((e) => ({ name: e.name_snapshot, quantity: e.quantity, unit: e.unit }))
    }))
  };
}
export {
  buildWorkshopOptions,
  compactWorkshopOption,
  workshopTargets
};
