import type { Campaign, MyBilling, Subscription } from '../../src/features/billing/api';
import type { Catalog } from '../../src/features/admin/api';
export const owner='ba000000-0000-4000-8000-000000000002';
export const useAuth=()=>({user:{id:owner},profile:{full_name:'Profesional de prueba',onboarding_completed:true},loading:false,signOut:async()=>{}});
const essential='bd000000-0000-4000-8000-000000000001',professional='bd000000-0000-4000-8000-000000000002';
const entries=[['patients.limit','Pacientes activos','limit'],['ai.monthly_credits','Créditos IA mensuales','limit'],['consultations','Consultas','boolean'],['diet_workshop','Taller manual','boolean'],['ai.diet_draft','Taller con IA','boolean'],['exports','PDF de planes','boolean'],['diet_library.full','Biblioteca completa','boolean']];
const catalog:Catalog={entitlements:entries.map(([key,label,kind],i)=>({key,label,value_type:kind as 'limit'|'boolean',category:'Plan',display_order:i})),plans:[{id:essential,code:'esencial',name:'Esencial',description:'Para comenzar con herramientas clínicas y 30 pacientes activos.',monthly_price:349,annual_price:3490,currency:'MXN',active:true,internal_only:false,display_order:0,values:{'patients.limit':30,'ai.monthly_credits':10,consultations:true,diet_workshop:true,exports:true}},{id:professional,code:'profesional',name:'Profesional',description:'Para una consulta activa, con pacientes ilimitados y Taller IA.',monthly_price:499,annual_price:4990,currency:'MXN',active:true,internal_only:false,display_order:1,values:{'patients.limit':'unlimited','ai.monthly_credits':50,consultations:true,diet_workshop:true,exports:true,'diet_library.full':true,'ai.diet_draft':true}}]};
const campaign:Campaign={id:'bb000000-0000-4000-8000-000000000001',version:1,code:'UAZ2026',name:'Convenio Universidad UAZ',audience:'university',audience_note:'Cohorte de septiembre · solo datos ficticios',visibility:'private',active:true,starts_at:'2026-09-01T00:00:00Z',ends_at:'2026-12-31T23:59:59Z',eligible_plan_ids:[essential],plan_names:['Esencial'],intervals:['monthly'],benefits:[{type:'custom_price',amount:249,duration:{kind:'months',months:12}},{type:'initial_ai_credits',amount:20,duration:{kind:'invoice'}}],max_redemptions:100,max_per_professional:1,new_customers_only:false,fallback:'normal_plan',redeemed:12,reserved:2,redemptions:[{id:'fixture-redemption',professional_id:owner,professional_name:'Profesional de prueba',subscription_id:'fixture-sub',redeemed_at:'2026-09-24T12:00:00Z',audience:'university'}],mappings:[{version:1,provider_coupon_id:'coupon_test_fixture',price_mapping_id:'price_test_fixture',end_at:null}]};
const influencer={...campaign,id:'bb000000-0000-4000-8000-000000000002',code:'NUTRIMARIA',name:'Comunidad de María',audience:'influencer',eligible_plan_ids:[professional],plan_names:['Profesional'],benefits:[{type:'percentage_discount' as const,amount:20,duration:{kind:'months' as const,months:3}}],max_redemptions:50,redeemed:8,reserved:0};
const state=new URLSearchParams(location.search).get('state')??'active';
const subscription:Subscription={id:'fixture-sub',professional_id:owner,professional_name:'Profesional de prueba',plan_name:'Esencial',plan_id:essential,interval:'monthly',amount:34900,currency:'MXN',state,period_start:'2026-09-24T12:00:00Z',period_end:'2026-10-24T12:00:00Z',paid_through:'2026-10-24T12:00:00Z',cancel_at_period_end:false,grace_until:'2026-10-31T12:00:00Z',manual_hold:false,pending_plan_id:null,pending_interval:null,provider:'stripe',campaign_id:campaign.id,campaign_snapshot:campaign,provider_subscription_id:'sub_test_fixture',last_payment:'2026-09-24T12:00:00Z'};
const summary:MyBilling={mode:'test',enabled:true,test_eligible:true,access:{plan_id:essential,plan_name:'Esencial',status:state,starts_at:'2026-09-24T12:00:00Z',ends_at:'2026-10-24T12:00:00Z',allowed:true,read_only:state==='suspended',values:catalog.plans[0].values,sources:{}},subscription,credits:{included:8,additional:20},payments:[{provider_invoice_id:'invoice_test_fixture',professional_id:owner,professional_name:'Profesional de prueba',plan_name:'Esencial',provider:'stripe',amount_due:24900,amount_paid:24900,currency:'MXN',status:'paid',issued_at:'2026-09-24T12:00:00Z',paid_at:'2026-09-24T12:00:00Z',hosted_url:'https://invoice.stripe.com/i/test_fixture'}]};
export const useAccess=()=>({data:{is_admin:true,access:summary.access},refresh:async()=>{}});
let campaigns:Campaign[]=[campaign,influencer];
export const supabase={rpc:async(name:string,args?:{p_action?:string;p_data?:Record<string,unknown>})=>{
 const action=args?.p_action,input=args?.p_data;let data:unknown=null;
 if(name==='plan_catalog')data=catalog.plans;
 if(name==='my_billing')data=summary;
 if(name==='admin_api')data=action==='catalog'?catalog:{items:[{id:owner,name:'Profesional de prueba',email:'prueba@example.test'}],total:1};
 if(name==='billing_admin_api'){
 if(action==='campaigns')data=campaigns;
 if(action==='campaign')data=campaigns.find(c=>c.id===input?.id);
 if(action==='save_campaign'){data={...input,version:Number(input?.version??0)+1};campaigns=[...campaigns.filter(c=>c.id!==input?.id),data as Campaign];}
 if(action==='disable_campaign'){campaigns=campaigns.map(c=>c.id===input?.id?{...c,active:false}:c);data={saved:true};}
 if(action==='subscriptions')data=[subscription,{...subscription,id:'fixture-sub-2',professional_name:'Otra cuenta de prueba',plan_name:'Profesional',interval:'annual',amount:499000,state:'grace'}];
 if(action==='payments')data=summary.payments;
 if(action==='overview')data={settings:{enabled:true,grace_days:7},test_accounts:[{id:owner,name:'Profesional de prueba'}],professionals:[{id:owner,name:'Profesional de prueba',email:'prueba@example.test'}],plans:catalog.plans,mappings:catalog.plans.flatMap(p=>['monthly','annual'].map(interval=>({id:p.id+interval,plan_id:p.id,plan_name:p.name,interval,amount:(interval==='monthly'?p.monthly_price!:p.annual_price!)*100,currency:'MXN',provider_price_id:'price_test_'+p.code+'_'+interval})))};
 }
 return {data:structuredClone(data),error:null};},functions:{invoke:async(_name:string,{body}:{body:Record<string,unknown>})=>({data:body.action==='preview'?{price:{amount:34900,currency:'MXN'},campaign:campaigns.find(c=>c.code===body.code)??null}:{requested:true,timing:'period_end'},error:null})}};
