import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.MESA_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({headless:true,channel:'chrome'});
const page = await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const output = new URL('../../../output/mesa-refinement/',import.meta.url).pathname;
const faults=[];
page.on('pageerror',e=>faults.push(e.message));
await mkdir(output,{recursive:true});
const saves=async()=>Number((await page.getByRole('status').filter({hasText:'Caso ficticio'}).innerText()).match(/Guardados de menú: (\d+)/)[1]);
const article=name=>page.getByRole('article').filter({has:page.getByRole('heading',{name,exact:true})});
const remove=async name=>{await article(name).getByText('Revisar o ajustar',{exact:true}).click();await article(name).getByRole('button',{name:`Eliminar ${name}`,exact:true}).click();};
try {
  await page.goto('http://127.0.0.1:4175/tests/visual/menu.html?exploration');
  await page.getByRole('button',{name:'Agregar opción',exact:true}).click();
  assert.equal(await saves(),1);
  await page.getByRole('button',{name:'Proponer opción',exact:true}).click();
  await remove('Guayaba');
  await page.getByRole('button',{name:'Otra propuesta',exact:true}).click();
  await page.getByRole('heading',{name:'Manzana',exact:true}).waitFor();
  await remove('Manzana');
  await page.getByRole('button',{name:'Deshacer edición de propuesta'}).click();
  await page.getByRole('heading',{name:'Manzana',exact:true}).waitFor();
  await remove('Manzana');
  await page.getByRole('button',{name:'Otra propuesta',exact:true}).click();
  await page.getByRole('heading',{name:'Pera',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Cantidad de Huevo cocido').inputValue(),'1');
  assert.equal(await page.getByLabel('Cantidad de Tortilla de maíz').inputValue(),'2');
  await page.getByRole('tab',{name:/^Comida /}).click();
  assert.equal(await page.getByRole('button',{name:'Aplicar propuesta'}).count(),0);
  await page.getByRole('tab',{name:/^Desayuno /}).click();
  await page.getByRole('heading',{name:'Pera',exact:true}).waitFor();
  const bank=page.getByRole('region',{name:'Opciones de este tiempo'});
  await bank.getByRole('button',{name:/Desayuno · opción 1.*Borrador/}).click();
  assert.equal(await page.getByRole('heading',{name:'Pera',exact:true}).count(),0);
  await bank.getByRole('button',{name:/Desayuno · opción 2.*Borrador/}).click();
  await page.getByRole('heading',{name:'Pera',exact:true}).waitFor();
  assert.equal(await saves(),1);
  for(const width of [1440,768,390,320]) {
    await page.setViewportSize({width,height:950});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${width}`);
    await page.screenshot({path:output+`preview-${width}.png`,fullPage:true});
  }
  await page.getByRole('button',{name:'Agregar alimento',exact:true}).click();
  await page.getByRole('dialog').waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(),0);
  assert.equal(await page.getByRole('button',{name:'Agregar alimento',exact:true}).evaluate(el=>el===document.activeElement),true);
  await page.getByRole('button',{name:'Aplicar propuesta'}).click();
  assert.equal(await saves(),2);
  await page.getByRole('button',{name:'Confirmar opción',exact:true}).click();
  assert.equal(await saves(),3);
  assert.equal(await page.getByLabel('Nombre de la opción').inputValue(),'Desayuno · opción 2');
  assert.equal(await page.getByRole('button',{name:'Agregar otra opción de desayuno',exact:true}).count(),1);
  assert.deepEqual(faults,[]);
  console.log(JSON.stringify({result:'passed',checks:['guava to apple to pear','undo rejection','egg and tortilla quantities','time and option isolation','no preview saves','confirm stays on option','responsive 1440/768/390/320','reduced motion','Escape restores focus'],screenshots:output}));
} finally {await browser.close();}
