import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.MESA_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({headless:true, channel:'chrome'});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const faults=[];
page.on('pageerror',error=>faults.push(error.message));
const output = new URL('../../../output/mesa/',import.meta.url).pathname;
await mkdir(output,{recursive:true});
const saveCount=async()=>Number((await page.getByRole('status').filter({hasText:'Caso ficticio'}).innerText()).match(/Guardados de menú: (\d+)/)[1]);
try {
  await page.goto('http://127.0.0.1:4175/tests/visual/menu.html');
  await page.getByRole('heading',{name:'Nuthrick a la Mesa',exact:true}).waitFor();
  await page.getByRole('button',{name:'Agregar alimento',exact:true}).click();
  await page.getByPlaceholder('Buscar alimento', {exact:true}).fill('tortilla');
  await page.getByRole('button',{name:'Agregar',exact:true}).click();
  assert.equal(await saveCount(),1);
  await page.getByRole('article').filter({has:page.getByRole('heading',{name:'Tortilla de maíz',exact:true})}).getByText('Revisar o ajustar',{exact:true}).click();
  await page.getByRole('button',{name:'Intercambiar Tortilla de maíz',exact:true}).click();
  await page.getByRole('option',{name:/Pan integral/}).click();
  assert.equal(await saveCount(),2);
  await page.getByRole('button',{name:'Crear receta',exact:true}).click();
  const selector=page.getByRole('dialog',{name:'Selecciona qué forma la preparación'});
  assert.equal(await selector.getByRole('checkbox').evaluateAll(nodes=>nodes.filter(n=>n.checked).length),0);
  await selector.getByRole('checkbox',{name:/Pan integral/}).check();
  await page.getByRole('button',{name:'Continuar con selección'}).click();
  await page.getByLabel('Nombre',{exact:true}).fill('Preparación ficticia de pan');
  await page.getByLabel('Rendimiento (porciones)',{exact:true}).fill('2');
  await page.getByRole('button',{name:'Guardar en mi biblioteca'}).click();
  await page.getByRole('dialog',{name:'Preparación guardada'}).waitFor();
  assert.equal(await saveCount(),2);
  await page.getByRole('button',{name:'Sí',exact:true}).click();
  assert.equal(await saveCount(),3);
  await page.getByRole('article').filter({has:page.getByRole('heading',{name:'Preparación ficticia de pan',exact:true})}).getByText('Revisar o ajustar',{exact:true}).click();
  assert.equal(await page.getByRole('spinbutton',{name:'Cantidad de Preparación ficticia de pan',exact:true}).inputValue(),'2');
  assert.equal(await page.getByRole('heading',{name:'Papaya preparada',exact:true}).count(),1);
  await page.getByRole('button',{name:'Agregar bebida',exact:true}).click();
  await page.getByPlaceholder('Buscar receta', {exact:true}).fill('agua natural');
  await page.getByRole('button',{name:'Revisar',exact:true}).click();
  await page.getByRole('button',{name:'Agregar al menú',exact:true}).click();
  assert.equal(await saveCount(),4);
  await page.getByRole('button',{name:'Proponer opción',exact:true}).click();
  await page.getByRole('button',{name:'Aplicar propuesta',exact:true}).waitFor();
  assert.equal(await saveCount(),4);
  await page.screenshot({path:output+'desktop-preview.png',fullPage:true});
  const first=await page.getByRole('spinbutton').evaluateAll(nodes=>nodes.map(n=>[n.getAttribute('aria-label'),n.value]));
  await page.getByRole('button',{name:'Otra propuesta',exact:true}).click();
  if(await page.getByRole('button',{name:'Propuesta anterior'}).isEnabled()) {
    await page.getByRole('button',{name:'Propuesta anterior'}).click();
    const again=await page.getByRole('spinbutton').evaluateAll(nodes=>nodes.map(n=>[n.getAttribute('aria-label'),n.value]));
    assert.deepEqual(again,first);
  }
  await page.getByRole('button',{name:'Descartar',exact:true}).click();
  assert.equal(await saveCount(),4);
  await page.getByRole('button',{name:'Proponer opción',exact:true}).click();
  // The exploration may have exhausted its finite alternatives; recover a previously shown option.
  if(!(await page.getByRole('button',{name:'Aplicar propuesta'}).count())) await page.getByRole('button',{name:'Recuperar propuestas'}).click();
  await page.getByRole('button',{name:'Aplicar propuesta',exact:true}).click();
  assert.equal(await saveCount(),5);
  await page.getByRole('button',{name:'Deshacer aplicación'}).click();
  assert.equal(await saveCount(),6);
  await page.getByRole('button',{name:'Vista clásica',exact:true}).click();
  assert.equal(await saveCount(),6);
  await page.screenshot({path:output+'classic.png',fullPage:true});
  await page.getByRole('button',{name:'Volver a la mesa'}).click();
  await page.getByRole('button',{name:'Comparar opciones activas',exact:true}).click();
  for(const width of [1440,768,390]) {
    await page.setViewportSize({width,height:900});
    await page.screenshot({path:output+`mesa-${width}.png`,fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),`overflow at ${width}`);
  }
  await page.getByRole('button',{name:'Agregar bebida',exact:true}).click();
  await page.screenshot({path:output+'mobile-pantry.png',fullPage:true});
  assert.ok(await page.getByRole('dialog',{name:'Despensa'}).evaluate(el=>el.scrollWidth<=el.clientWidth+1),'mobile dialog overflow');
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(),0);
  await page.getByRole('button',{name:'Agregar bebida',exact:true}).click();
  await page.getByPlaceholder('Buscar receta',{exact:true}).fill('licuado');
  await page.getByRole('button',{name:'Revisar',exact:true}).click();
  assert.ok(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'mobile recipe adjustment overflow');
  await page.getByRole('button',{name:'Agregar al menú',exact:true}).click();
  assert.equal(await saveCount(),7);
  await page.getByRole('heading',{name:'Licuado de papaya con leche',exact:true}).waitFor();
  await page.getByRole('button',{name:'Crear bebida personal',exact:true}).click();
  await page.getByRole('button',{name:'Crear desde cero',exact:true}).click();
  await page.getByLabel('Nombre',{exact:true}).fill('Bebida ficticia personal');
  await page.getByLabel('Alimento de la receta',{exact:true}).selectOption({label:'Leche descremada'});
  await page.getByRole('button',{name:'Añadir',exact:true}).click();
  await page.getByRole('button',{name:'Guardar en mi biblioteca'}).click();
  await page.getByRole('dialog',{name:'Preparación guardada'}).waitFor();
  assert.equal(await saveCount(),7);
  await page.getByRole('button',{name:'Sí',exact:true}).click();
  assert.equal(await saveCount(),8);
  await page.getByRole('heading',{name:'Bebida ficticia personal',exact:true}).waitFor();
  assert.deepEqual(faults,[]);
  console.log(JSON.stringify({result:'passed',flows:['add','exchange','create selected recipe, yield 2','library separate from menu','add water','preview A-B-A','discard','apply','undo','classic shared state','day review','1440/768/390 widths','mobile pantry and recipe editor','Escape','nutrient beverage','personal beverage'],screenshots:output}));
} finally {await browser.close();}
