import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.MESA_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
const faults = [];
page.on('pageerror', e => faults.push(e.message));
const output = new URL('../../../output/mesa-week/', import.meta.url).pathname;
await mkdir(output, { recursive: true });
const saves = async () => Number((await page.getByRole('status').filter({ hasText: 'Caso ficticio' }).innerText()).match(/Guardados de menú: (\d+)/)[1]);
try {
  await page.goto('http://127.0.0.1:4175/tests/visual/menu.html?weekly');
  await page.getByRole('button', { name: 'Plan por días', exact: true }).click();
  assert.equal(await saves(), 0);
  await page.getByText('Se organizarán 5 días a partir de tus opciones.').waitFor();
  await page.getByRole('button', { name: 'Organizar días', exact: true }).click();
  assert.equal(await saves(), 0);
  assert.equal(await page.getByRole('table').getByRole('row').count(), 6);
  const monday = page.getByRole('table').getByLabel('Opción de Desayuno para Lunes', { exact: true });
  await monday.selectOption('breakfast-1');
  const lock = page.getByRole('table').getByLabel('Fijar Lunes Desayuno', { exact: true });
  await lock.focus(); await page.keyboard.press('Space');
  await page.getByRole('button', { name: 'Volver a organizar', exact: true }).click();
  assert.equal(await monday.inputValue(), 'breakfast-1');
  assert.equal(await saves(), 0);
  await page.screenshot({ path: output + 'desktop-preview.png', fullPage: true });
  await page.getByRole('button', { name: 'Aplicar calendario', exact: true }).click();
  assert.equal(await saves(), 1);
  await page.getByRole('button', { name: 'Organizar días', exact: true }).click();
  await page.getByRole('button', { name: 'Descartar calendario', exact: true }).click();
  assert.equal(await saves(), 1);
  const detailButton = page.getByRole('table').getByRole('button', { name: /^Ver .* del Lunes$/ }).first();
  await detailButton.click();
  await page.getByRole('dialog').waitFor();
  assert.ok((await page.getByRole('dialog').innerText()).includes('240 ml'));
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(), 0);
  for (const width of [1440, 1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 950 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), `page overflow at ${width}`);
    await page.screenshot({ path: output + `calendar-${width}.png`, fullPage: true });
  }
  await page.getByRole('button', { name: 'Día siguiente', exact: true }).click();
  assert.equal(await page.getByLabel('Día del calendario', { exact: true }).inputValue(), 'tue');
  await page.getByRole('button', { name: /^Ver .* del Martes$/ }).first().click();
  assert.ok(await page.getByRole('dialog').evaluate(d => d.scrollWidth <= d.clientWidth + 1));
  await page.keyboard.press('Escape');
  assert.equal(await page.getByLabel('Día del calendario', { exact: true }).inputValue(), 'tue');
  assert.equal(await saves(), 1);
  await page.getByRole('button', { name: 'Opciones por tiempo', exact: true }).click();
  await page.screenshot({ path: output + 'mobile-options.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'option bank overflow at 320');
  await page.getByRole('button', { name: 'Agregar otra opción de desayuno', exact: true }).click();
  assert.equal(await page.getByRole('spinbutton').count(), 0);
  assert.equal(await saves(), 2);
  await page.getByRole('button', { name: 'Eliminar opción', exact: true }).click();
  await page.getByRole('button', { name: 'Deshacer eliminación de opción', exact: true }).click();
  assert.equal(await saves(), 4);
  assert.deepEqual(faults, []);
  console.log(JSON.stringify({ result: 'passed', screenshots: output, checks: ['3/5/1 => five days', 'preview no save', 'keyboard fixed assignment', 'regenerate preserves locks', 'apply once', 'discard no save', 'details and Escape', '1440/1024/768/390/320 no overflow', 'mobile day retains position', 'create independent option', 'delete and undo'] }));
} finally { await browser.close(); }
