import { useEffect, useRef, useState, type FormEvent } from "react";
import { adminRpc, emailWorker } from "../legal/api";
import "../legal/legal.css";
type Message = {id: string; template_key: string; mode: string; status: string; delivery_status: string; attempts: number; last_error: string | null; next_attempt_at: string; provider_message_id: string | null; observed_at: string | null; is_test_delivery: boolean};
type Overview = {
  ready: boolean; contacts: {support_email: string | null; privacy_email: string | null};
  settings: {delivery_mode: string; from_email: string; domain_name: string | null; domain_id: string | null; verified_at: string | null; runtime_verified_at: string | null; webhook_verified_at: string | null; last_worker_at: string | null; configuration_revision: number; domain_evidence: {spf?: boolean; dkim?: boolean; dmarc?: boolean; records?: unknown[]}};
  test_recipients: string[]; counts: Record<string, number>; messages: Message[];
};
const labels: Record<string,string> = {pending:"Pendientes", accepted:"Aceptados por proveedor", delivered:"Entregados al servidor", observed:"Recibidos y revisados", failed:"Fallidos", bounced:"Rebotados", simulated:"Simulados"};
function Field({label, name, value = "", type = "text"}: {label: string; name: string; value?: string; type?: string}) { return <label className="admin-field">{label}<input name={name} type={type} defaultValue={value} required autoComplete="off" /></label>; }
export function EmailOperationsPanel() {
  const [data, setData] = useState<Overview | null>(null);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [recipient, setRecipient] = useState(""); const [observing, setObserving] = useState<string | null>(null);
  const operation = useRef(crypto.randomUUID());
  useEffect(() => {let active = true; void adminRpc<Overview>("email_admin_api", "overview").then(next => {if(active) setData(next);}).catch(e => {if(active) setError(e.message);}); return () => {active = false;};}, []);
  const run = async (action: string, input: Record<string, unknown> = {}) => {
    setBusy(true); setError(""); setNotice("");
    try {
      if (action === "verify" || action === "worker") {await emailWorker(action); setData(await adminRpc<Overview>("email_admin_api", "overview"));}
      else setData(await adminRpc<Overview>("email_admin_api", action, input));
      setNotice(action === "queue_tests" ? "Cinco mensajes en cola. Repetir esta acción conserva la misma clave de envío." : action === "worker" ? "Procesamiento terminado. Revisa los estados y la bandeja." : "Operación guardada.");
      if(action === "observed") setObserving(null);
    } catch(e) {setError(e instanceof Error ? e.message : "No pudimos completar la acción.");} finally {setBusy(false);}
  };
  const submit = (action: string) => (event: FormEvent<HTMLFormElement>) => {event.preventDefault(); void run(action, Object.fromEntries(new FormData(event.currentTarget)));};
  return <section className="admin-card billing-section"><h2>Correo transaccional real</h2><p className="admin-note">Conservamos las 15 plantillas y la outbox. Solo se envían cinco pruebas a bandejas autorizadas. La aceptación del proveedor, la entrega y la revisión de la bandeja son evidencias distintas.</p>
    {error && <p role="alert" className="admin-error">{error}</p>}{notice && <p role="status" className="admin-success">{notice}</p>}
    {data && <>
      <p><strong>{data.ready ? "Verificado" : "Pendiente de verificación real"}</strong> · {data.settings.delivery_mode === "simulated" ? "Modo simulado" : "Pruebas controladas"}</p>
      <div className="email-status">{Object.entries(data.counts).map(([key, count]) => <span key={key}>{labels[key] ?? key}: <strong>{count}</strong></span>)}</div>
      <p>Remitente: {data.settings.from_email || "Sin configurar"} · Soporte: {data.contacts.support_email || "Sin confirmar"}</p>
      <p>SPF: {data.settings.domain_evidence.spf ? "Verificado" : "Pendiente"} · DKIM: {data.settings.domain_evidence.dkim ? "Verificado" : "Pendiente"} · DMARC: {data.settings.domain_evidence.dmarc ? "Verificado" : "Pendiente"}</p>
      <p className="admin-note">Webhook firmado: {data.settings.webhook_verified_at ? "Recibido" : "Pendiente"} · Último worker: {data.settings.last_worker_at ? new Date(data.settings.last_worker_at).toLocaleString("es-MX") : "Sin ejecución real"}</p>
      <details><summary>Contactos reales de soporte y privacidad</summary><form key={`contacts-${data.settings.configuration_revision}`} className="email-form" onSubmit={submit("contacts")}><Field label="Soporte" name="support_email" type="email" value={data.contacts.support_email ?? ""} /><Field label="Privacidad" name="privacy_email" type="email" value={data.contacts.privacy_email ?? ""} /><Field label="Escribe CONFIRMAR CONTACTOS REALES" name="confirmation" /><p className="admin-note">Cambiar contactos requiere volver a verificar el correo. Las versiones legales aprobadas conservan su texto.</p><button className="admin-button secondary" disabled={busy}>Guardar contactos</button></form></details>
      <details><summary>Configurar dominio y remitente</summary><form className="email-form" onSubmit={submit("configure")}><p>Proveedor preparado: Resend. Necesitas un dominio propio y DNS verificado. No introduzcas claves aquí.</p><Field label="Dominio" name="domain_name" value={data.settings.domain_name ?? ""} /><Field label="ID del dominio en Resend" name="domain_id" value={data.settings.domain_id ?? ""} /><Field label="Correo remitente" name="from_email" type="email" value={data.settings.from_email} /><Field label="Escribe SOLO CORREOS DE PRUEBA CONTROLADOS" name="confirmation" /><button className="admin-button secondary" disabled={busy}>Guardar configuración</button></form><button className="admin-button secondary" disabled={busy || !data.settings.domain_id} onClick={() => void run("verify")}>Verificar proveedor y DNS</button>{data.settings.domain_evidence.records && <pre className="email-records">{JSON.stringify(data.settings.domain_evidence, null, 2)}</pre>}</details>
      <details><summary>Bandejas y cinco pruebas</summary><form className="email-form" onSubmit={submit("authorize_recipient")}><p>Máximo dos bandejas bajo tu control.</p><Field label="Bandeja controlada" name="email" type="email" /><Field label="Escribe CONTROLO ESTA BANDEJA Y AUTORIZO LAS PRUEBAS" name="confirmation" /><button className="admin-button secondary" disabled={busy}>Autorizar bandeja</button></form><label className="admin-field">Destino de pruebas<select value={recipient} onChange={e => {setRecipient(e.target.value); operation.current = crypto.randomUUID();}}><option value="">Selecciona una bandeja</option>{data.test_recipients.map(email => <option key={email}>{email}</option>)}</select></label><div className="legal-actions"><button className="admin-button secondary" disabled={busy || !recipient || !data.settings.verified_at || !data.settings.runtime_verified_at} onClick={() => void run("queue_tests", {email: recipient, operation_key: operation.current})}>Preparar cinco pruebas</button><button className="admin-button secondary" disabled={busy || !data.settings.verified_at} onClick={() => void run("worker")}>Procesar cola controlada</button></div></details>
      <details open={data.messages.some(m => m.status === "failed")}><summary>Mensajes y reintentos</summary>{data.messages.map(m => <div className="email-message" key={m.id}><strong>{m.template_key} · {labels[m.delivery_status] ?? m.delivery_status}</strong><small>{m.mode.toUpperCase()} · {m.attempts}/5 intentos · {m.id}</small>{m.last_error && <p className="admin-error">{m.last_error}</p>}<small>{m.status === "pending" ? `Siguiente intento: ${new Date(m.next_attempt_at).toLocaleString("es-MX")}` : m.provider_message_id ? `ID proveedor: ${m.provider_message_id}` : "Sin envío real confirmado"}</small>{m.status === "failed" && !m.provider_message_id && <button className="admin-button secondary" disabled={busy} onClick={() => void run("retry", {id: m.id})}>Reintentar con auditoría</button>}{m.is_test_delivery && m.provider_message_id && !m.observed_at && ["accepted", "delivered"].includes(m.delivery_status) && <button className="admin-button secondary" onClick={() => setObserving(m.id)}>Registrar recepción y revisión</button>}{m.observed_at && <small>Revisado: {new Date(m.observed_at).toLocaleString("es-MX")}</small>}{observing === m.id && <form className="email-form" onSubmit={submit("observed")}><input type="hidden" name="id" value={m.id} /><p>Revisa remitente, asunto, acentos, vista móvil, enlaces, footer y spam.</p><label className="admin-field">Resultado, sin datos clínicos<textarea name="note" minLength={12} maxLength={500} required /></label><Field label="Escribe: Confirmo que recibí y revisé este correo." name="confirmation" /><button className="admin-button secondary" disabled={busy}>Guardar evidencia</button></form>}</div>)}</details>
    </>}
  </section>;
}
