do $$ declare owner_id uuid:='00000000-0000-0000-0000-000000000001'; pid uuid:='20000000-0000-0000-0000-000000000001';
 stamp timestamptz:=((now() at time zone 'America/Mexico_City')::date+25+time '10:00') at time zone 'America/Mexico_City';
 data jsonb; result jsonb; eid uuid; link jsonb; other_id uuid; begin
 update private.agenda_google_connections set active=false;
 update public.patients set full_name='Paciente sintético manual',email=null,country_code='+52',phone='4920000000',portal_access_enabled=true where id=pid;
 if has_function_privilege('anon','public.agenda_appointment_action(text,jsonb)','execute') or has_function_privilege('authenticated','public.agenda_appointment_action(text,jsonb)','execute') then raise exception 'Unsafe grants'; end if;
 data:=jsonb_build_object('owner',owner_id,'patientId',pid,'start',stamp,'modality','online','locationId',null,'allowOutsideSchedule',false,'operationKey',gen_random_uuid());
 perform pg_temp.expect_error(format('select public.agenda_appointment_action(''create'',%L)',data||'{"owner":"00000000-0000-0000-0000-000000000002"}'),'invalid_patient');
 result:=public.agenda_appointment_action('create',data);
 eid:=(result->>'id')::uuid;
 if eid is null or result->>'patient_confirmed_at' is not null or result->>'professional_confirmed_at' is not null then raise exception 'Invalid manual confirmation'; end if;
 if public.agenda_appointment_action('create',data)<>result or public.agenda_appointment_action('replay_create',data)<>result then raise exception 'Idempotency failure'; end if;
 if exists(select 1 from private.agenda_outbox where subject_id=eid) then raise exception 'Premature notification'; end if;
 perform pg_temp.expect_error(format('select public.agenda_appointment_action(''create'',%L)',data||jsonb_build_object('operationKey',gen_random_uuid())),'slot_taken');
 perform pg_temp.expect_error(format('select public.agenda_appointment_action(''create'',%L)',data||jsonb_build_object('start',stamp+interval '12 hours','operationKey',gen_random_uuid())),'outside_schedule');
 link:=public.agenda_appointment_action('link',jsonb_build_object('owner',owner_id,'id',eid,'tokenHash','fixture-token','encryptedToken','encrypted-fixture'));
 if public.agenda_appointment_action('info','{"tokenHash":"fixture-token"}')->>'patient_confirmed_at' is not null then raise exception 'GET confirmed appointment'; end if;
 result:=public.agenda_appointment_action('patient_confirm','{"tokenHash":"fixture-token"}');
 if result->>'patient_confirmed_at' is null or result->>'professional_confirmed_at' is not null then raise exception 'Patient confirmation'; end if;
 if public.agenda_appointment_action('patient_confirm','{"tokenHash":"fixture-token"}')<>result then raise exception 'Patient replay'; end if;
 perform public.agenda_confirm_reservation(owner_id,gen_random_uuid(),jsonb_build_object('action','confirm_reservation','id',eid));
 if not exists(select 1 from public.agenda_entries where id=eid and patient_confirmed_at is not null and professional_confirmed_at is not null and notification_status='not_required') then raise exception 'Both confirmations'; end if;
 insert into private.patient_portals values(pid,'current-link',now()+interval '1 day',null,null);
 insert into private.portal_sessions values('session-fixture',pid,now()+interval '1 hour','current-link',null);
 result:=public.agenda_appointment_action('list','{"sessionHash":"session-fixture"}');
 if jsonb_array_length(result->'appointments')<1 or result::text like '%contact_phone%' then raise exception 'Portal list projection'; end if;
 update private.patient_portals set link_hash='rotated';
 perform pg_temp.expect_error('select public.agenda_appointment_action(''list'',''{"sessionHash":"session-fixture"}'')','portal_unavailable');
 update private.patient_portals set link_hash='current-link';
 -- Professional may confirm first without impersonating the patient.
 data:=data||jsonb_build_object('operationKey',gen_random_uuid(),'start',stamp+interval '1 hour');
 other_id:=(public.agenda_appointment_action('create',data)->>'id')::uuid;
 perform public.agenda_confirm_reservation(owner_id,gen_random_uuid(),jsonb_build_object('action','confirm_reservation','id',other_id));
 if exists(select 1 from public.agenda_entries where id=other_id and patient_confirmed_at is not null) then raise exception 'False patient confirmation'; end if;
 perform public.agenda_appointment_action('patient_confirm',jsonb_build_object('sessionHash','session-fixture','id',other_id));
 if (select count(*) from public.professional_notifications where dedupe_key='patient-confirmed:'||eid)<>1 then raise exception 'Duplicate notification'; end if;
 perform public.agenda_manage(owner_id,gen_random_uuid(),jsonb_build_object('action','cancel','id',eid));
 perform pg_temp.expect_error('select public.agenda_appointment_action(''info'',''{"tokenHash":"fixture-token"}'')','invalid_token');
 -- Expired links and unrelated patients cannot confirm.
 perform pg_temp.expect_error('select public.agenda_appointment_action(''info'',''{"tokenHash":"unknown"}'')','invalid_token');
 perform pg_temp.expect_error('select public.agenda_appointment_action(''patient_confirm'',''{"sessionHash":"session-fixture","id":"ffffffff-ffff-ffff-ffff-ffffffffffff"}'')','not_found');
 perform public.agenda_appointment_action('link',jsonb_build_object('owner',owner_id,'id',other_id,'tokenHash','expired-token','encryptedToken','encrypted-fixture'));
 update private.appointment_links set expires_at=now()-interval '1 second' where entry_id=other_id;
 perform pg_temp.expect_error('select public.agenda_appointment_action(''info'',''{"tokenHash":"expired-token"}'')','invalid_token');
 update public.agenda_entries set starts_at=now()+interval '3 hours',ends_at=now()+interval '4 hours' where id=other_id;
 perform public.agenda_upcoming_notifications();perform public.agenda_upcoming_notifications();
 if (select count(*) from public.professional_notifications where resource_id=other_id and metadata->>'upcoming'='true')<>1 then raise exception 'Upcoming reminder idempotency'; end if;
end $$;
select 'PASS manual booking, conflicts, both confirmation orders, token and portal authorization, idempotency, notifications, cancellation and no-email patients';
