create function pg_temp.assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'ASSERTION: %',label;end if;end$$;
create function pg_temp.reject(query text,code text) returns void language plpgsql as $$begin begin execute query;exception when others then if position(code in sqlerrm)>0 then return;end if;raise;end;raise exception 'Expected rejection: %',code;end$$;
select set_config('nuthrick.billing_environment','test',false);
create temp table access_before as select to_jsonb(s) snapshot from private.billing_subscriptions s where provider_subscription_id='sub_local_mail';
select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[{"id":"re_localconfirmed","amount":12300,"currency":"MXN"}]}');
select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[{"id":"re_localconfirmed","amount":12300,"currency":"MXN"}]}');
select pg_temp.assert((select refunded_amount=12300 and amount_paid=34900 and status='paid' from private.billing_payments where provider_invoice_id='in_local_mail'),'Partial refund preserves original invoice');
select pg_temp.assert((select count(*)=1 from private.transactional_email_outbox where event_key='refund:test:re_localconfirmed'),'Replay does not duplicate email');
select private.queue_subscription_refunds('{"id":"in_local_mail"}');
select pg_temp.assert((select refunded_amount=12300 from private.billing_payments where provider_invoice_id='in_local_mail'),'Missing refund snapshot cannot erase history');
select pg_temp.reject($q$select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[{"id":"re_a","amount":20000,"currency":"MXN"},{"id":"re_b","amount":20000,"currency":"MXN"}]}')$q$,'invalid_refund_notice');
select pg_temp.reject($q$select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[{"id":"re_a","amount":100,"currency":"MXN"},{"id":"re_a","amount":100,"currency":"MXN"}]}')$q$,'invalid_refund_notice');
select pg_temp.reject($q$select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[{"amount":100,"currency":"MXN"}]}')$q$,'invalid_refund_notice');
select pg_temp.reject($q$select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[{"id":"re_a","amount":100,"currency":"USD"}]}')$q$,'invalid_refund_notice');
select pg_temp.reject($q$select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[{"id":"re_a","amount":-100,"currency":"MXN"}]}')$q$,'invalid_refund_notice');
select pg_temp.reject($q$select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":null}')$q$,'invalid_refund_notice');
select pg_temp.assert((select refunded_amount=12300 from private.billing_payments where provider_invoice_id='in_local_mail'),'Rejected snapshots are atomic');
select set_config('nuthrick.billing_environment','live',false);
select pg_temp.reject($q$select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[]}')$q$,'unknown_refund_invoice');
select set_config('nuthrick.billing_environment','test',false);
select private.queue_subscription_refunds('{"id":"in_local_mail","refunds":[{"id":"re_localconfirmed","amount":12300,"currency":"MXN"},{"id":"re_second","amount":22600,"currency":"MXN"}]}');
select pg_temp.assert((select refunded_amount=34900 and jsonb_array_length(refunds)=2 from private.billing_payments where provider_invoice_id='in_local_mail'),'Separate refunds accumulate to full original payment');
select pg_temp.assert((select snapshot=(select to_jsonb(s) from private.billing_subscriptions s where provider_subscription_id='sub_local_mail') from access_before),'Refund never changes access or cancellation');
select pg_temp.assert(not has_function_privilege('authenticated','private.queue_subscription_refunds(jsonb)','EXECUTE'),'Browser cannot write refund state');
select pg_temp.assert(not has_table_privilege('authenticated','private.billing_payments','SELECT'),'Private payment table remains inaccessible');
select set_config('request.jwt.claim.sub','ab000000-0000-4000-8000-000000000002',false);
select pg_temp.assert((select (p->>'refunded_amount')::bigint=34900 and not p ? 'refunds' from jsonb_array_elements(public.my_billing()->'payments') p where p->>'provider_invoice_id'='in_local_mail'),'Owner sees verified total without private refund IDs');
select set_config('request.jwt.claim.sub','ba000000-0000-4000-8000-000000000003',false);
select pg_temp.assert(not exists(select 1 from jsonb_array_elements(public.my_billing()->'payments') p where p->>'provider_invoice_id'='in_local_mail'),'Other professionals cannot read this refund');
