-- Synthetic local schema. The runner rolls back ALL objects and data.
create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;
create schema private;
grant usage on schema public,private to service_role;
create table public.professional_profiles(id uuid primary key,full_name text,professional_title text);
create table public.patients(id uuid primary key,professional_id uuid,full_name text,email text,portal_access_enabled boolean default false,status text default 'active',deleted_at timestamptz);
create table public.consultations(id uuid primary key,professional_id uuid,patient_id uuid,status text,deleted_at timestamptz,summary text);
create table public.nutrition_plans(id uuid primary key,professional_id uuid,patient_id uuid,status text,current_version_id uuid);
create table public.nutrition_plan_versions(id uuid primary key,plan_id uuid,professional_id uuid,patient_id uuid,version_number integer,published_at timestamptz,snapshot jsonb);
grant all on public.professional_profiles,public.patients,public.consultations to service_role;
insert into public.professional_profiles values ('00000000-0000-0000-0000-000000000001','Nutrióloga ficticia','Nutrición'),('00000000-0000-0000-0000-000000000002','Ajeno','Nutrición');
insert into public.patients(id,professional_id,full_name,email) values
 ('10000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001','Paciente sintético','patient@example.invalid'),
 ('10000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000002','Otro','other@example.invalid');
insert into public.consultations values
 ('20000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','completed',null,'PRIVATE CLINICAL SUMMARY'),
 ('20000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','draft',null,'PRIVATE DRAFT'),
 ('20000000-0000-0000-0000-000000000003','00000000-0000-0000-0000-000000000002','10000000-0000-0000-0000-000000000002','completed',null,'OTHER PATIENT');
alter table public.professional_profiles add column license_number text, add column storage_key uuid default gen_random_uuid();
alter table public.consultations add column consultation_date timestamptz default now();
create table public.consultation_snapshots(consultation_id uuid,patient_id uuid,professional_id uuid,revision integer,structure jsonb);
create table public.consultation_answers(consultation_id uuid,patient_id uuid,professional_id uuid,revision integer,question_key text,response_area text,value jsonb);
create table public.professional_businesses(professional_id uuid,establishment_name text,address text,logo_path text);
create table public.professional_contacts(id uuid,professional_id uuid,display_order integer,label text,country_code text,contact_value text);
create table public.professional_locations(id uuid,professional_id uuid,is_active boolean,address text,display_order integer);
-- MIGRATION INSERTION POINT --
create function pg_temp.assert(value boolean,message text) returns void language plpgsql as $$ begin if value is distinct from true then raise exception '%',message; end if; end $$;
create function pg_temp.reject(q text) returns void language plpgsql as $$ begin begin execute q; exception when others then return; end; raise exception 'Expected rejection'; end $$;
select pg_temp.assert(not has_function_privilege('anon','public.patient_portal(text,jsonb)','execute'),'Anon RPC leak');
select pg_temp.assert(not has_function_privilege('authenticated','public.patient_portal(text,jsonb)','execute'),'Authenticated RPC leak');
select pg_temp.assert(not has_table_privilege('authenticated','private.portal_notes','select'),'Private notes leak');
select pg_temp.assert((select bool_and(relrowsecurity) from pg_class where oid in ('private.patient_portals'::regclass,'private.portal_challenges'::regclass,'private.portal_sessions'::regclass,'private.portal_messages'::regclass,'private.portal_notes'::regclass)),'RLS missing');
select pg_temp.assert(not (select prosecdef from pg_proc where oid='public.patient_portal(text,jsonb)'::regprocedure),'RPC must be invoker');
do $$
declare owner jsonb:='{"owner":"00000000-0000-0000-0000-000000000001","patientId":"10000000-0000-0000-0000-000000000001"}';
  actor jsonb:='{"sessionHash":"session-1"}'; result jsonb; cid uuid:='30000000-0000-0000-0000-000000000001'; data jsonb; msg jsonb;
begin
  perform pg_temp.assert(public.patient_portal('view',owner)->>'patientName'='Paciente sintético','Owner view');
  perform pg_temp.assert(public.patient_portal('view',owner||'{"owner":"00000000-0000-0000-0000-000000000002"}')->>'error'='portal_unavailable','Cross-owner leak');
  perform pg_temp.assert(public.patient_portal('view',actor)->>'error'='portal_unavailable','No session leaked');
  perform public.patient_portal('link',owner||'{"linkHash":"link-one","encryptedLink":"encrypted-fixture"}');
  perform pg_temp.assert(public.patient_portal('view',actor)->>'error'='portal_unavailable','Link without OTP leaked');
  perform pg_temp.assert(public.patient_portal('challenge','{"linkHash":"link-one","email":"wrong@example.invalid"}')->>'error'='portal_unavailable','Wrong recipient');
  data:=jsonb_build_object('id',cid,'linkHash','link-one','email','patient@example.invalid','codeHash','correct');
  perform public.patient_portal('challenge',data);
  perform pg_temp.assert(public.patient_portal('verify',data||'{"codeHash":"wrong","newSessionHash":"bad"}')->>'error'='invalid_code','Wrong code');
  perform pg_temp.assert((select attempts=1 from private.portal_challenges where id=cid),'Attempts not persisted');
  perform pg_temp.assert(public.patient_portal('verify',data||'{"newSessionHash":"session-1"}')->>'verified'='true','Verify failed');
  perform pg_temp.assert(public.patient_portal('verify',data||'{"newSessionHash":"session-2"}')->>'error'='invalid_code','Code replay allowed');
  result:=public.patient_portal('view',actor);
  perform pg_temp.assert(not(result ? 'encryptedLink') and not(result ? 'link') and result::text not like '%PRIVATE%' and result::text not like '%@%','Patient DTO leak');
  data:='{"goal":"Caminar","instructions":"Indicaciones visibles","results":[],"consultations":[{"id":"20000000-0000-0000-0000-000000000001","date":"2026-09-16","title":"Consulta","summary":"Resumen para paciente"}]}';
  perform public.patient_portal('publish',owner||jsonb_build_object('revision',0,'shared',data));
  perform pg_temp.assert(public.patient_portal('view',actor)->'shared'->>'goal'='Caminar','Share invisible');
  perform pg_temp.assert(public.patient_portal('publish',owner||jsonb_build_object('revision',0,'shared',data))->>'error'='stale_revision','Lost update');
  perform pg_temp.assert(public.patient_portal('publish',actor||jsonb_build_object('revision',1,'shared',data))->>'error'='invalid_action','Patient published');
  perform pg_temp.reject(format('select public.patient_portal(%L,%L)','publish',owner||jsonb_build_object('revision',1,'shared',replace(data::text,'20000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000002')::jsonb)));
  perform pg_temp.reject(format('select public.patient_portal(%L,%L)','publish',owner||jsonb_build_object('revision',1,'shared',replace(data::text,'20000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000003')::jsonb)));
  msg:='{"clientId":"40000000-0000-0000-0000-000000000001","body":"Hola"}';
  result:=public.patient_portal('message',owner||msg);
  perform pg_temp.assert(public.patient_portal('message',owner||msg)=result,'Message retry');
  perform pg_temp.assert(public.patient_portal('message',owner||msg||'{"body":"Different"}')->>'error'='idempotency_mismatch','Message overwrite');
  perform pg_temp.assert(public.patient_portal('view',actor)->>'unread'='1','Unread missing');
  perform pg_temp.assert(jsonb_array_length(public.patient_portal('inbox',owner||'{"search":"","offset":0}')->'patients')=1,'Inbox missing own patient');
  perform pg_temp.assert(jsonb_array_length(public.patient_portal('inbox',owner||'{"owner":"00000000-0000-0000-0000-000000000002","search":"","offset":0}')->'patients')=0,'Inbox cross-owner leak');
  perform public.patient_portal('message',actor||msg);
  perform pg_temp.assert(jsonb_array_length(public.patient_portal('messages',actor)->'messages')=2,'Conversation missing');
  perform public.patient_portal('read',actor||result);
  perform pg_temp.assert(public.patient_portal('view',actor)->>'unread'='0','Read cursor');
  perform public.patient_portal('note',actor||'{"id":"50000000-0000-0000-0000-000000000001","body":"Mi duda privada"}');
  perform pg_temp.assert(public.patient_portal('notes',owner)->>'error'='invalid_action','Professional read personal notes');
  perform pg_temp.assert(public.patient_portal('view',owner)::text not like '%duda privada%','Notes leak into owner overview');
  perform pg_temp.assert(jsonb_array_length(public.patient_portal('notes',actor)->'notes')=1,'Note missing');
  perform public.patient_portal('note',actor||'{"id":"50000000-0000-0000-0000-000000000001","body":"Editada","done":true}');
  perform pg_temp.assert(public.patient_portal('notes',actor)->'notes'->0->>'done'='true','Note edit');
  update private.portal_sessions set expires_at=now()-interval '1 second' where token_hash='session-1';
  perform pg_temp.assert(public.patient_portal('view',actor)->>'error'='portal_unavailable','Expired session works');
  update private.portal_sessions set expires_at=now()+interval '2 hours' where token_hash='session-1';
  update private.patient_portals set link_expires_at=now()-interval '1 second' where patient_id=(owner->>'patientId')::uuid;
  perform pg_temp.assert(public.patient_portal('message',owner||msg)->>'error'='portal_unavailable','Expired link accepts professional messages');
  update private.patient_portals set link_expires_at=now()+interval '90 days' where patient_id=(owner->>'patientId')::uuid;
  update public.consultations set deleted_at=now() where id='20000000-0000-0000-0000-000000000001';
  perform pg_temp.assert(jsonb_array_length(public.patient_portal('view',actor)->'shared'->'consultations')=0,'Deleted consultation still shared');
  update public.consultations set deleted_at=null where id='20000000-0000-0000-0000-000000000001';
  update public.patients set portal_access_enabled=false where id=(owner->>'patientId')::uuid;
  perform pg_temp.assert(public.patient_portal('messages',actor)->>'error'='portal_unavailable','Disabled session works');
  update public.patients set portal_access_enabled=true,email='changed@example.invalid' where id=(owner->>'patientId')::uuid;
  perform pg_temp.assert(public.patient_portal('notes',actor)->>'error'='portal_unavailable','Changed email session works');
  update public.patients set email='patient@example.invalid',status='archived' where id=(owner->>'patientId')::uuid;
  perform pg_temp.assert(public.patient_portal('view',actor)->>'error'='portal_unavailable','Archived access');
  update public.patients set status='active' where id=(owner->>'patientId')::uuid;
  perform public.patient_portal('revoke',owner);
  perform pg_temp.assert(public.patient_portal('view',actor)->>'error'='portal_unavailable','Revoked access');
  perform pg_temp.assert((select count(*)=2 from private.portal_messages),'Revocation deleted chat');
  perform pg_temp.assert((select count(*)=1 from private.portal_notes),'Revocation deleted notes');
  perform public.patient_portal('link',owner||'{"linkHash":"link-two","encryptedLink":"encrypted-fixture"}');
  cid:=gen_random_uuid(); data:=jsonb_build_object('id',cid,'linkHash','link-two','email','patient@example.invalid','codeHash','correct');
  perform public.patient_portal('challenge',data);
  for i in 1..5 loop perform public.patient_portal('verify',data||'{"codeHash":"wrong","newSessionHash":"bad"}'); end loop;
  perform pg_temp.assert(public.patient_portal('verify',data||'{"newSessionHash":"bad"}')->>'error'='invalid_code','Bruteforce unlocked');
  cid:=gen_random_uuid(); data:=data||jsonb_build_object('id',cid); perform public.patient_portal('challenge',data);
  update private.portal_challenges set expires_at=now()-interval '1 second' where id=cid;
  perform pg_temp.assert(public.patient_portal('verify',data||'{"newSessionHash":"bad"}')->>'error'='invalid_code','Expired code');
end $$;
-- Exercise the exact runtime role, including invoker permissions and keyset paging.
set local role service_role;
do $$
declare owner jsonb:='{"owner":"00000000-0000-0000-0000-000000000001","patientId":"10000000-0000-0000-0000-000000000001"}';
  page jsonb; older jsonb; cursor jsonb;
begin
  if public.patient_portal('view',owner)->>'patientName'<>'Paciente sintético' then raise exception 'Service role cannot read'; end if;
  for i in 1..55 loop
    perform public.patient_portal('message',owner||jsonb_build_object('clientId',gen_random_uuid(),'body','Paging '||i));
  end loop;
  page:=public.patient_portal('messages',owner);
  if jsonb_array_length(page->'messages')<>50 then raise exception 'First page size'; end if;
  older:=public.patient_portal('messages',owner||jsonb_build_object('before',page->'before'));
  if jsonb_array_length(older->'messages')<>7 then raise exception 'Older page missing'; end if;
  cursor:=jsonb_build_object('at',older->'messages'->6->>'created_at','id',older->'messages'->6->>'id');
  page:=public.patient_portal('messages',owner||jsonb_build_object('after',cursor));
  if jsonb_array_length(page->'messages')<>50 then raise exception 'Incremental page missing'; end if;
end $$;
reset role;
do $$
declare owner jsonb:='{"owner":"00000000-0000-0000-0000-000000000001","patientId":"10000000-0000-0000-0000-000000000001"}';
  actor jsonb:='{"sessionHash":"manual-session"}';
  code jsonb:='{"id":"60000000-0000-0000-0000-000000000001","linkHash":"no-email-link","codeHash":"manual-hash","identityConfirmed":true}';
  plan_id uuid:='70000000-0000-0000-0000-000000000001'; result jsonb;
begin
  update public.patients set email=null where id=(owner->>'patientId')::uuid;
  perform public.patient_portal('link',owner||'{"linkHash":"no-email-link","encryptedLink":"fixture"}');
  perform pg_temp.assert(public.patient_portal('view',owner)->>'enabled'='true','No-email link disabled');
  perform pg_temp.assert(public.patient_portal('issue_code',owner||code||'{"identityConfirmed":false}')->>'error'='identity_confirmation_required','Unverified issue allowed');
  perform public.patient_portal('issue_code',owner||code);
  perform pg_temp.assert(public.patient_portal('verify',code||'{"newSessionHash":"wrong-channel"}')->>'error'='invalid_code','Manual code accepted as email code');
  perform pg_temp.assert(public.patient_portal('verify_professional',code||'{"codeHash":"wrong","newSessionHash":"wrong"}')->>'error'='invalid_code','Wrong manual code');
  perform pg_temp.assert(public.patient_portal('verify_professional',code||'{"newSessionHash":"manual-session"}')->>'verified'='true','Manual login failed without email');
  perform pg_temp.assert(public.patient_portal('verify_professional',code||'{"newSessionHash":"replay"}')->>'error'='invalid_code','Manual replay');
  perform pg_temp.assert(public.patient_portal('view',actor)->>'patientName'='Paciente sintético','Manual session failed');
  perform pg_temp.assert(public.patient_portal('issue_code',actor||code)->>'error'='invalid_action','Patient issued code');
  perform pg_temp.assert(public.patient_portal('plan_options',actor)->>'error'='invalid_action','Patient enumerated plans');
  insert into public.nutrition_plans values(plan_id,(owner->>'owner')::uuid,(owner->>'patientId')::uuid,'draft',null);
  perform pg_temp.assert(jsonb_array_length(public.patient_portal('plan_options',owner)->'plans')=0,'Draft offered');
  perform pg_temp.assert(public.patient_portal('share_plan',owner||jsonb_build_object('planId',plan_id))->>'error'='invalid_plan','Draft shared');
  insert into public.nutrition_plan_versions values('80000000-0000-0000-0000-000000000001',plan_id,(owner->>'owner')::uuid,(owner->>'patientId')::uuid,1,now(),'{"plan":{"title":"PUBLICADO"},"private":"SERVER ONLY"}');
  update public.nutrition_plans set current_version_id='80000000-0000-0000-0000-000000000001' where id=plan_id;
  perform pg_temp.assert(public.patient_portal('plan',actor)->'plan'='null'::jsonb,'Plan automatically shared');
  perform public.patient_portal('share_plan',owner||jsonb_build_object('planId',plan_id));
  perform pg_temp.assert(public.patient_portal('plan',actor)->'plan'->>'versionNumber'='1','Published plan missing');
  perform pg_temp.assert(public.patient_portal('share_plan',actor||jsonb_build_object('planId',plan_id))->>'error'='invalid_action','Patient changed plan');
  update public.nutrition_plan_versions set patient_id='10000000-0000-0000-0000-000000000002' where id='80000000-0000-0000-0000-000000000001';
  perform pg_temp.assert(public.patient_portal('plan',actor)->'plan'='null'::jsonb,'Cross-patient snapshot leak');
  update public.nutrition_plan_versions set patient_id=(owner->>'patientId')::uuid where id='80000000-0000-0000-0000-000000000001';
  update public.nutrition_plans set status='archived' where id=plan_id;
  perform pg_temp.assert(public.patient_portal('plan',actor)->'plan'='null'::jsonb,'Archived plan leak');
  update public.nutrition_plans set status='active' where id=plan_id;
  perform public.patient_portal('share_plan',owner||'{"planId":null}');
  perform pg_temp.assert(public.patient_portal('plan',actor)->'plan'='null'::jsonb,'Plan not withdrawn');
  perform public.patient_portal('issue_code',owner||code||'{"id":"60000000-0000-0000-0000-000000000002"}');
  for i in 1..5 loop perform public.patient_portal('verify_professional',code||'{"codeHash":"wrong","newSessionHash":"blocked"}'); end loop;
  perform pg_temp.assert(public.patient_portal('verify_professional',code||'{"newSessionHash":"blocked"}')->>'error'='invalid_code','Manual attempts not bounded');
  perform public.patient_portal('issue_code',owner||code||'{"id":"60000000-0000-0000-0000-000000000003"}');
  update private.portal_challenges set expires_at=now()-interval '1 second' where channel='professional';
  perform pg_temp.assert(public.patient_portal('verify_professional',code||'{"newSessionHash":"expired"}')->>'error'='invalid_code','Expired manual code');
  perform public.patient_portal('revoke',owner);
  perform pg_temp.assert(public.patient_portal('view',actor)->>'error'='portal_unavailable','Manual session not revoked');
end $$;
do $$
declare owner jsonb:='{"owner":"00000000-0000-0000-0000-000000000001","patientId":"10000000-0000-0000-0000-000000000001"}';
 actor jsonb:='{"sessionHash":"export-session"}'; goals jsonb; shared jsonb; rev integer; result jsonb;
begin
 insert into public.consultation_snapshots select id,patient_id,professional_id,1,'{"sections":[{"questions":[{"question_key":"objectives","response_area":"professional_assessment"}]}]}' from public.consultations;
 insert into public.consultation_answers select id,patient_id,professional_id,1,'objectives','professional_assessment','[{"objetivo":"Acuerdo inicial","prioridad":"Principal","private":"SECRET"}]' from public.consultations;
 update public.consultations set consultation_date='2026-09-01' where id='20000000-0000-0000-0000-000000000001';
 update public.consultations set consultation_date='2026-09-21' where id='20000000-0000-0000-0000-000000000002';
 goals:=public.patient_portal('goal_candidates',owner)->'goals';
 perform pg_temp.assert(jsonb_array_length(goals)=1 and goals->0->>'content'='Acuerdo inicial','Draft or foreign objective leaked');
 perform pg_temp.assert(goals::text not like '%SECRET%','Objective included private repeatable fields');
 shared:=jsonb_build_object('goal',goals->0->>'content','goalSource',(goals->0)-'content'-'date','instructions','','results','[]'::jsonb,'consultations','[]'::jsonb);
 rev:=(public.patient_portal('view',owner)->>'revision')::integer;
 perform public.patient_portal('publish',owner||jsonb_build_object('revision',rev,'shared',shared));
 perform public.patient_portal('link',owner||'{"linkHash":"export-link","encryptedLink":"fixture"}');
 insert into private.portal_sessions(token_hash,patient_id,link_hash,email) values('export-session',(owner->>'patientId')::uuid,'export-link',null);
 perform pg_temp.assert(public.patient_portal('view',actor)->'shared'->>'goal'='Acuerdo inicial','Objective unavailable');
 perform pg_temp.assert(not (public.patient_portal('view',actor)->'shared' ? 'goalSource'),'Objective internal reference exposed');
 update public.consultations set status='completed' where id='20000000-0000-0000-0000-000000000002';
 update public.consultation_answers set value='[{"objetivo":"Nuevo acuerdo"}]' where consultation_id='20000000-0000-0000-0000-000000000002';
 goals:=public.patient_portal('goal_candidates',owner)->'goals';
 perform pg_temp.assert(goals->0->>'content'='Nuevo acuerdo','Newest goal not offered');
 perform pg_temp.assert(public.patient_portal('view',actor)->'shared'->>'goal'='Acuerdo inicial','Objective silently republished');
 perform pg_temp.assert((select value->0->>'objetivo'='Acuerdo inicial' from public.consultation_answers where consultation_id='20000000-0000-0000-0000-000000000001'),'History overwritten');
 rev:=(public.patient_portal('view',owner)->>'revision')::integer;
 perform pg_temp.assert(public.patient_portal('publish',owner||jsonb_build_object('revision',rev,'shared',jsonb_set(shared,'{goal}','"Injected"')))->>'error'='invalid_goal','Unverified goal source accepted');
 perform public.patient_portal('publish',owner||jsonb_build_object('revision',rev,'shared',shared||'{"goal":"","goalSource":null}'));
 perform pg_temp.assert(public.patient_portal('view',actor)->'shared'->>'goal'='','Objective cannot be hidden');
 update public.consultations set deleted_at=now() where id='20000000-0000-0000-0000-000000000002';
 perform pg_temp.assert(jsonb_array_length(public.patient_portal('goal_candidates',owner)->'goals')=1,'Deleted objective offered');
 insert into public.nutrition_plan_versions values('80000000-0000-0000-0000-000000000002','70000000-0000-0000-0000-000000000001',(owner->>'owner')::uuid,(owner->>'patientId')::uuid,2,now(),'{"plan":{"title":"VERSIÓN DOS"}}');
 update public.nutrition_plans set current_version_id='80000000-0000-0000-0000-000000000002' where id='70000000-0000-0000-0000-000000000001';
 insert into public.nutrition_plans values('70000000-0000-0000-0000-000000000003',(owner->>'owner')::uuid,(owner->>'patientId')::uuid,'draft',null);
 perform pg_temp.assert(jsonb_array_length(public.patient_portal('plan_history',owner)->'versions')=2,'Draft counted as a published version');
 result:=public.patient_portal('export_plan',owner||'{"format":"pdf","versionId":"80000000-0000-0000-0000-000000000001"}');
 perform pg_temp.assert(result->'plan'->>'versionNumber'='1','v1 export replaced by v2');
 perform pg_temp.assert(public.patient_portal('plan_version',owner||'{"versionId":"80000000-0000-0000-0000-000000000002"}')->'plan'->>'versionNumber'='2','v2 view mismatch');
 perform pg_temp.assert(public.patient_portal('export_plan',owner||'{"format":"pdf","versionId":"70000000-0000-0000-0000-000000000003"}')->>'error'='invalid_plan','Draft exported');
 perform pg_temp.assert(public.patient_portal('export_plan',owner||'{"format":"pdf","owner":"00000000-0000-0000-0000-000000000002","versionId":"80000000-0000-0000-0000-000000000001"}')->>'error'='portal_unavailable','Foreign professional exported');
 perform pg_temp.assert(public.patient_portal('export_plan',actor||'{"format":"pdf"}')->>'error'='invalid_plan','Unshared plan exported');
 perform public.patient_portal('share_plan',owner||'{"planId":"70000000-0000-0000-0000-000000000001"}');
 perform pg_temp.assert(public.patient_portal('export_plan',actor||'{"format":"pdf"}')->'plan'->>'versionNumber'='2','Shared current version unavailable');
 perform pg_temp.assert(public.patient_portal('export_plan',actor||'{"format":"tex"}')->>'error'='invalid_action','Patient exported TEX');
 perform pg_temp.assert(public.patient_portal('export_plan',actor||'{"format":"pdf","versionId":"80000000-0000-0000-0000-000000000001"}')->>'error'='invalid_action','Patient chose historical version');
 perform pg_temp.assert(public.patient_portal('plan_history',actor)->>'error'='invalid_action','Patient enumerated versions');
 perform public.patient_portal('revoke',owner);
 perform pg_temp.assert(public.patient_portal('export_plan',actor||'{"format":"pdf"}')->>'error'='portal_unavailable','Revoked patient exported');
end $$;
select 'Portal isolation, goals, immutable exports, OTP, chat and notes: OK';
