-- Objective 5A: turn the existing interactive catalogue into the single,
-- traceable mathematical specification. Complex methods intentionally remain
-- not_implemented; validation status is independent from runtime status.

update public.calculation_definitions as c
set method_version = v.method_version,
    definition = v.definition,
    updated_at = now()
from (values
  ('bmi', '1.1.0', $json${
    "catalogVersion":2,"resultKey":"bmi","resultName":"Índice de masa corporal","methodName":"IMC","method":"Índice de Quetelet","variant":"peso/talla²","summary":"Relaciona el peso medido en la consulta con la estatura del expediente.","unit":"kg/m²","decimalPlaces":1,
    "inputs":[{"key":"weight","label":"Peso","source":"consultation_measurement","measurementCode":"weight","expectedUnit":"kg"},{"key":"height","label":"Estatura","source":"patient_record","patientField":"height_cm","expectedUnit":"cm"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"IMC = peso_kg / (estatura_cm / 100)²","variables":{"peso_kg":"Peso de la consulta en kg","estatura_cm":"Estatura del expediente en cm"},"transformations":["Convertir estatura de cm a m antes de elevar al cuadrado"]},"variants":[],
    "applicability":{"population":"Índice descriptivo para adultos; este contrato no aplica clasificación clínica.","notes":["La interpretación depende del contexto clínico y no forma parte de este objetivo."]},
    "references":[{"authors":"World Health Organization","year":2000,"title":"Obesity: preventing and managing the global epidemic","source":"WHO Technical Report Series 894","url":"https://iris.who.int/handle/10665/42330","evidence":"technical_manual"}],
    "validationStatus":"validated","validationNote":"Ecuación, unidades y fuentes de datos confirmadas.","methodologicalNotes":["La estatura procede del expediente y el peso debe existir en la consulta."],"limitations":"Es un índice descriptivo; no representa composición corporal ni diagnóstico."
  }$json$::jsonb),
  ('waist_hip_ratio', '1.1.0', $json${
    "catalogVersion":2,"resultKey":"waist_hip_ratio","resultName":"Índice cintura/cadera","methodName":"Relación cintura/cadera","method":"Waist-to-hip ratio","variant":"cintura ÷ cadera","summary":"Relaciona la circunferencia de cintura con la circunferencia máxima de cadera/glúteo de la misma consulta.","unit":"razón","decimalPlaces":2,
    "inputs":[{"key":"waist","label":"Circunferencia de cintura","source":"consultation_measurement","measurementCode":"waist_circumference","expectedUnit":"cm"},{"key":"hip","label":"Circunferencia de cadera/glúteo","source":"consultation_measurement","measurementCode":"hip_circumference","expectedUnit":"cm"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"ICC = cintura_cm / cadera_cm","variables":{"cintura_cm":"Circunferencia de cintura en cm","cadera_cm":"Circunferencia máxima de cadera/glúteo en cm"}},"variants":[],
    "applicability":{"population":"Adultos medidos con sitios anatómicos consistentes.","notes":["No equivale a circunferencia abdominal."]},
    "references":[{"authors":"World Health Organization","year":2008,"title":"Waist circumference and waist-hip ratio: report of a WHO expert consultation","source":"WHO","url":"https://iris.who.int/handle/10665/44583","evidence":"technical_manual"}],
    "validationStatus":"validated","validationNote":"Razón y sitios anatómicos definidos.","methodologicalNotes":["Ambas circunferencias deben pertenecer a la consulta actual."],"limitations":"No se aplican puntos de corte ni interpretación clínica en este objetivo."
  }$json$::jsonb),
  ('waist_height_ratio', '1.1.0', $json${
    "catalogVersion":2,"resultKey":"waist_height_ratio","resultName":"Índice cintura/talla","methodName":"Relación cintura/talla","method":"Waist-to-height ratio","variant":"cintura ÷ talla","summary":"Relaciona la circunferencia de cintura de la consulta con la estatura del expediente.","unit":"razón","decimalPlaces":2,
    "inputs":[{"key":"waist","label":"Circunferencia de cintura","source":"consultation_measurement","measurementCode":"waist_circumference","expectedUnit":"cm"},{"key":"height","label":"Estatura","source":"patient_record","patientField":"height_cm","expectedUnit":"cm"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"ICT = cintura_cm / estatura_cm","variables":{"cintura_cm":"Circunferencia de cintura en cm","estatura_cm":"Estatura en cm"}},"variants":[],
    "applicability":{"population":"Índice antropométrico descriptivo; mediciones expresadas en la misma unidad."},
    "references":[{"authors":"Ashwell M, Hsieh SD","year":2005,"title":"Six reasons why the waist-to-height ratio is a rapid and effective global indicator for health risks of obesity","source":"International Journal of Food Sciences and Nutrition","doi":"10.1080/09637480500195066","url":"https://pubmed.ncbi.nlm.nih.gov/16236591/","evidence":"original"}],
    "validationStatus":"validated","validationNote":"Razón, unidades y fuentes de datos definidas.","methodologicalNotes":["No se aplican umbrales clínicos."],"limitations":"No se aplican puntos de corte ni interpretación clínica en este objetivo."
  }$json$::jsonb),
  ('density_jackson_pollock_3', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_density","resultName":"Densidad corporal","methodName":"Jackson & Pollock 3","method":"Jackson-Pollock generalizado","variant":"Tres pliegues, específica por sexo","summary":"Estima densidad corporal mediante tres pliegues seleccionados según el sexo para ecuaciones y la edad en la consulta.","unit":"g/cm³","decimalPlaces":5,
    "inputs":[{"key":"sex","label":"Sexo para ecuaciones","source":"patient_record","patientField":"equation_sex","expectedUnit":"categoría"},{"key":"age","label":"Edad en esta consulta","source":"patient_derived","derivation":"age_at_consultation","expectedUnit":"años"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"La ecuación activa depende del sexo para ecuaciones; S3 es la suma de tres pliegues en mm."},
    "variants":[
      {"code":"male","name":"Masculina · pectoral, abdominal y muslo anterior","appliesWhen":{"equationSex":"male"},"inputs":[{"key":"chest","label":"Pliegue pectoral","source":"consultation_measurement","measurementCode":"chest_skinfold","expectedUnit":"mm"},{"key":"abdominal","label":"Pliegue abdominal","source":"consultation_measurement","measurementCode":"abdominal_skinfold","expectedUnit":"mm"},{"key":"thigh","label":"Pliegue de muslo anterior","source":"consultation_measurement","measurementCode":"thigh_skinfold","expectedUnit":"mm"}],"equation":{"expression":"D = 1.10938 − 0.0008267·S3 + 0.0000016·S3² − 0.0002574·edad","coefficients":{"constant":1.10938,"linear":-0.0008267,"quadratic":0.0000016,"age":-0.0002574}},"applicability":{"sexes":["male"],"ageMin":18,"ageMax":61,"population":"Hombres adultos del estudio generalizado original."}},
      {"code":"female","name":"Femenina · tríceps, suprailíaco y muslo anterior","appliesWhen":{"equationSex":"female"},"inputs":[{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"suprailiac","label":"Pliegue suprailíaco","source":"consultation_measurement","measurementCode":"suprailiac_skinfold","expectedUnit":"mm"},{"key":"thigh","label":"Pliegue de muslo anterior","source":"consultation_measurement","measurementCode":"thigh_skinfold","expectedUnit":"mm"}],"equation":{"expression":"D = 1.0994921 − 0.0009929·S3 + 0.0000023·S3² − 0.0001392·edad","coefficients":{"constant":1.0994921,"linear":-0.0009929,"quadratic":0.0000023,"age":-0.0001392}},"applicability":{"sexes":["female"],"ageMin":18,"ageMax":55,"population":"Mujeres adultas del estudio generalizado original; cautela en mayores de 40 años según la publicación."}}
    ],
    "applicability":{"sexes":["male","female"],"ageMin":18,"ageMax":61,"population":"Adultos de los estudios generalizados originales; los límites específicos cambian por sexo.","exclusions":["No extrapolar a menores, gestación u otras poblaciones sin validación."]},
    "references":[{"authors":"Jackson AS, Pollock ML","year":1978,"title":"Generalized equations for predicting body density of men","source":"British Journal of Nutrition","doi":"10.1079/BJN19780152","url":"https://www.cambridge.org/core/journals/british-journal-of-nutrition/article/generalized-equations-for-predicting-body-density-of-men/EAB21B1CF3A8360E5F5D43FDB8D4DD17","evidence":"original"},{"authors":"Jackson AS, Pollock ML, Ward A","year":1980,"title":"Generalized equations for predicting body density of women","source":"Medicine and Science in Sports and Exercise","url":"https://pubmed.ncbi.nlm.nih.gov/7402053/","evidence":"original"}],
    "validationStatus":"validated","validationNote":"Ambas variantes, coeficientes, sitios, unidades y rangos quedaron definidos para 5B.","methodologicalNotes":["Suprailíaco no se sustituye por supraespinal ni por cresta ilíaca.","La edad se calcula a la fecha histórica de la consulta."],"limitations":"La estimación depende de la técnica de pliegues y de la similitud con la población de derivación."
  }$json$::jsonb),
  ('density_jackson_pollock_7', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_density","resultName":"Densidad corporal","methodName":"Jackson & Pollock 7","method":"Jackson-Pollock generalizado","variant":"Siete pliegues, específica por sexo","summary":"Estima densidad corporal con siete pliegues, sexo para ecuaciones y edad histórica.","unit":"g/cm³","decimalPlaces":5,
    "inputs":[{"key":"chest","label":"Pliegue pectoral","source":"consultation_measurement","measurementCode":"chest_skinfold","expectedUnit":"mm"},{"key":"midaxillary","label":"Pliegue axilar medio","source":"consultation_measurement","measurementCode":"midaxillary_skinfold","expectedUnit":"mm"},{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"subscapular","label":"Pliegue subescapular","source":"consultation_measurement","measurementCode":"subscapular_skinfold","expectedUnit":"mm"},{"key":"suprailiac","label":"Pliegue suprailíaco","source":"consultation_measurement","measurementCode":"suprailiac_skinfold","expectedUnit":"mm"},{"key":"abdominal","label":"Pliegue abdominal","source":"consultation_measurement","measurementCode":"abdominal_skinfold","expectedUnit":"mm"},{"key":"thigh","label":"Pliegue de muslo anterior","source":"consultation_measurement","measurementCode":"thigh_skinfold","expectedUnit":"mm"},{"key":"sex","label":"Sexo para ecuaciones","source":"patient_record","patientField":"equation_sex","expectedUnit":"categoría"},{"key":"age","label":"Edad en esta consulta","source":"patient_derived","derivation":"age_at_consultation","expectedUnit":"años"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"La ecuación activa depende del sexo; S7 = pectoral + axilar medio + tríceps + subescapular + suprailíaco + abdominal + muslo anterior, en mm."},
    "variants":[{"code":"male","name":"Masculina","appliesWhen":{"equationSex":"male"},"equation":{"expression":"D = 1.112 − 0.00043499·S7 + 0.00000055·S7² − 0.00028826·edad","coefficients":{"constant":1.112,"linear":-0.00043499,"quadratic":0.00000055,"age":-0.00028826}},"applicability":{"sexes":["male"],"ageMin":18,"ageMax":61,"population":"Hombres del estudio generalizado original."}},{"code":"female","name":"Femenina","appliesWhen":{"equationSex":"female"},"equation":{"expression":"D = 1.097 − 0.00046971·S7 + 0.00000056·S7² − 0.00012828·edad","coefficients":{"constant":1.097,"linear":-0.00046971,"quadratic":0.00000056,"age":-0.00012828}},"applicability":{"sexes":["female"],"ageMin":18,"ageMax":55,"population":"Mujeres del estudio generalizado original; cautela en mayores de 40 años."}}],
    "applicability":{"sexes":["male","female"],"ageMin":18,"ageMax":61,"population":"Adultos de los estudios generalizados originales; límite femenino 55 años.","exclusions":["No extrapolar a menores, gestación u otras poblaciones sin validación."]},
    "references":[{"authors":"Jackson AS, Pollock ML","year":1978,"title":"Generalized equations for predicting body density of men","source":"British Journal of Nutrition","doi":"10.1079/BJN19780152","url":"https://www.cambridge.org/core/journals/british-journal-of-nutrition/article/generalized-equations-for-predicting-body-density-of-men/EAB21B1CF3A8360E5F5D43FDB8D4DD17","evidence":"original"},{"authors":"Jackson AS, Pollock ML, Ward A","year":1980,"title":"Generalized equations for predicting body density of women","source":"Medicine and Science in Sports and Exercise","url":"https://pubmed.ncbi.nlm.nih.gov/7402053/","evidence":"original"}],
    "validationStatus":"validated","validationNote":"Sitios, ecuaciones por sexo, coeficientes, unidades y rangos definidos para 5B.","methodologicalNotes":["El código suprailíaco se conserva distinto de supraespinal y cresta ilíaca."],"limitations":"La estimación depende de la técnica de pliegues y de la población de derivación."
  }$json$::jsonb),
  ('density_durnin_womersley', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_density","resultName":"Densidad corporal","methodName":"Durnin & Womersley","method":"Durnin-Womersley","variant":"Cuatro pliegues con coeficientes por sexo y edad","summary":"Estima densidad corporal a partir del logaritmo decimal de cuatro pliegues y una tabla de coeficientes por sexo y edad.","unit":"g/cm³","decimalPlaces":5,
    "inputs":[{"key":"biceps","label":"Pliegue bicipital","source":"consultation_measurement","measurementCode":"biceps_skinfold","expectedUnit":"mm"},{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"subscapular","label":"Pliegue subescapular","source":"consultation_measurement","measurementCode":"subscapular_skinfold","expectedUnit":"mm"},{"key":"suprailiac","label":"Pliegue suprailíaco","source":"consultation_measurement","measurementCode":"suprailiac_skinfold","expectedUnit":"mm"},{"key":"sex","label":"Sexo para ecuaciones","source":"patient_record","patientField":"equation_sex","expectedUnit":"categoría"},{"key":"age","label":"Edad en esta consulta","source":"patient_derived","derivation":"age_at_consultation","expectedUnit":"años"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"D = c − m·log10(S4), donde S4 = bíceps + tríceps + subescapular + suprailíaco (mm).","variables":{"c":"Intercepto según sexo y grupo etario","m":"Pendiente según sexo y grupo etario"}},
    "variants":[
      {"code":"male_17_19","name":"Masculina 17–19","appliesWhen":{"equationSex":"male","ageMin":17,"ageMax":19},"equation":{"expression":"D = 1.1620 − 0.0630·log10(S4)","coefficients":{"c":1.162,"m":0.063}}},
      {"code":"male_20_29","name":"Masculina 20–29","appliesWhen":{"equationSex":"male","ageMin":20,"ageMax":29},"equation":{"expression":"D = 1.1631 − 0.0632·log10(S4)","coefficients":{"c":1.1631,"m":0.0632}}},
      {"code":"male_30_39","name":"Masculina 30–39","appliesWhen":{"equationSex":"male","ageMin":30,"ageMax":39},"equation":{"expression":"D = 1.1422 − 0.0544·log10(S4)","coefficients":{"c":1.1422,"m":0.0544}}},
      {"code":"male_40_49","name":"Masculina 40–49","appliesWhen":{"equationSex":"male","ageMin":40,"ageMax":49},"equation":{"expression":"D = 1.1620 − 0.0700·log10(S4)","coefficients":{"c":1.162,"m":0.07}}},
      {"code":"male_50_72","name":"Masculina 50–72","appliesWhen":{"equationSex":"male","ageMin":50,"ageMax":72},"equation":{"expression":"D = 1.1715 − 0.0779·log10(S4)","coefficients":{"c":1.1715,"m":0.0779}}},
      {"code":"female_16_19","name":"Femenina 16–19","appliesWhen":{"equationSex":"female","ageMin":16,"ageMax":19},"equation":{"expression":"D = 1.1549 − 0.0678·log10(S4)","coefficients":{"c":1.1549,"m":0.0678}}},
      {"code":"female_20_29","name":"Femenina 20–29","appliesWhen":{"equationSex":"female","ageMin":20,"ageMax":29},"equation":{"expression":"D = 1.1599 − 0.0717·log10(S4)","coefficients":{"c":1.1599,"m":0.0717}}},
      {"code":"female_30_39","name":"Femenina 30–39","appliesWhen":{"equationSex":"female","ageMin":30,"ageMax":39},"equation":{"expression":"D = 1.1423 − 0.0632·log10(S4)","coefficients":{"c":1.1423,"m":0.0632}}},
      {"code":"female_40_49","name":"Femenina 40–49","appliesWhen":{"equationSex":"female","ageMin":40,"ageMax":49},"equation":{"expression":"D = 1.1333 − 0.0612·log10(S4)","coefficients":{"c":1.1333,"m":0.0612}}},
      {"code":"female_50_68","name":"Femenina 50–68","appliesWhen":{"equationSex":"female","ageMin":50,"ageMax":68},"equation":{"expression":"D = 1.1339 − 0.0645·log10(S4)","coefficients":{"c":1.1339,"m":0.0645}}}
    ],
    "applicability":{"sexes":["male","female"],"ageMin":16,"ageMax":72,"population":"481 hombres y mujeres estudiados originalmente; rangos efectivos: hombres 17–72, mujeres 16–68.","exclusions":["Fuera del rango específico no se selecciona coeficiente."]},
    "references":[{"authors":"Durnin JVGA, Womersley J","year":1974,"title":"Body fat assessed from total body density and its estimation from skinfold thickness","source":"British Journal of Nutrition","doi":"10.1079/BJN19740060","url":"https://www.cambridge.org/core/journals/british-journal-of-nutrition/article/body-fat-assessed-from-total-body-density-and-its-estimation-from-skinfold-thickness-measurements-on-481-men-and-women-aged-from-16-to-72-years/DAC8BA25856FCEB30E22F60E0AF80D07","evidence":"original"}],
    "validationStatus":"validated","validationNote":"Tabla etaria completa, transformación log10, sitios y unidades definidos para 5B.","methodologicalNotes":["Se usarán los grupos por edad, no la ecuación agregada de todas las edades."],"limitations":"La densidad estimada conserva las limitaciones de la muestra y de la técnica de medición original."
  }$json$::jsonb)
) as v(code, method_version, definition)
where c.code = v.code;

update public.calculation_definitions as c
set method_version = v.method_version,
    definition = v.definition,
    updated_at = now()
from (values
  ('muscle_mass_lee', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"muscle_mass","resultName":"Masa muscular esquelética","methodName":"Lee","method":"Lee et al. 2000","variant":"Modelo 1 antropométrico · candidato","summary":"Modelo antropométrico de masa muscular esquelética con circunferencias corregidas, talla, sexo, edad y término poblacional.","unit":"kg","decimalPlaces":1,
    "inputs":[{"key":"height","label":"Estatura","source":"patient_record","patientField":"height_cm","expectedUnit":"cm"},{"key":"arm_girth","label":"Circunferencia de brazo relajado","source":"consultation_measurement","measurementCode":"relaxed_arm_circumference","expectedUnit":"cm"},{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"mid_thigh_girth","label":"Circunferencia de muslo medio","source":"consultation_measurement","measurementCode":"mid_thigh_circumference","expectedUnit":"cm"},{"key":"thigh_skinfold","label":"Pliegue de muslo anterior","source":"consultation_measurement","measurementCode":"thigh_skinfold","expectedUnit":"mm"},{"key":"calf_girth","label":"Circunferencia máxima de pantorrilla","source":"consultation_measurement","measurementCode":"calf_circumference","expectedUnit":"cm"},{"key":"calf_skinfold","label":"Pliegue de pantorrilla medial","source":"consultation_measurement","measurementCode":"calf_skinfold","expectedUnit":"mm"},{"key":"sex","label":"Sexo para ecuaciones","source":"patient_record","patientField":"equation_sex","expectedUnit":"categoría"},{"key":"age","label":"Edad en esta consulta","source":"patient_derived","derivation":"age_at_consultation","expectedUnit":"años"},{"key":"population_group","label":"Grupo poblacional del modelo Lee","source":"patient_record","patientField":"lee_population_group","expectedUnit":"categoría"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"MM = talla_m·(0.00744·CAG² + 0.00088·CTG² + 0.00441·CCG²) + 2.4·sexo − 0.048·edad + grupo + 7.8","variables":{"CAG":"brazo_relajado_cm − π·(tríceps_mm/10)","CTG":"muslo_medio_cm − π·(muslo_mm/10)","CCG":"pantorrilla_máxima_cm − π·(pantorrilla_mm/10)","sexo":"0 mujer, 1 hombre","grupo":"−2.0 asiático, +1.1 afroamericano, 0 blanco o hispano"},"coefficients":{"arm":0.00744,"thigh":0.00088,"calf":0.00441,"sex":2.4,"age":-0.048,"constant":7.8},"transformations":["Convertir talla de cm a m","Convertir cada pliegue de mm a cm antes de multiplicar por π"]},"variants":[{"code":"model_2","name":"Modelo 2 peso-talla · documentado pero no adoptado","inputs":[{"key":"weight","label":"Peso","source":"consultation_measurement","measurementCode":"weight","expectedUnit":"kg"},{"key":"height","label":"Estatura","source":"patient_record","patientField":"height_cm","expectedUnit":"cm"},{"key":"sex","label":"Sexo para ecuaciones","source":"patient_record","patientField":"equation_sex","expectedUnit":"categoría"},{"key":"age","label":"Edad en esta consulta","source":"patient_derived","derivation":"age_at_consultation","expectedUnit":"años"},{"key":"population_group","label":"Grupo poblacional del modelo Lee","source":"patient_record","patientField":"lee_population_group","expectedUnit":"categoría"}],"equation":{"expression":"MM = 0.244·peso_kg + 7.80·talla_m + 6.6·sexo − 0.098·edad + grupo − 3.3"},"note":"Menor ajuste que el modelo 1 en el estudio original; no seleccionado."}],
    "applicability":{"sexes":["male","female"],"population":"Adultos sanos no obesos (IMC < 30 kg/m²) de la muestra original.","exclusions":["No extrapolar automáticamente a IMC ≥30 ni fuera de los grupos del modelo."]},
    "references":[{"authors":"Lee RC, Wang Z, Heo M, Ross R, Janssen I, Heymsfield SB","year":2000,"title":"Total-body skeletal muscle mass: development and cross-validation of anthropometric prediction models","source":"American Journal of Clinical Nutrition","doi":"10.1093/ajcn/72.3.796","url":"https://pubmed.ncbi.nlm.nih.gov/10966902/","evidence":"original"}],
    "validationStatus":"requires_decision","validationNote":"La ecuación está definida, pero el expediente no dispone de un campo éticamente y semánticamente acordado para el término poblacional del modelo; no se asumirá valor 0.","methodologicalNotes":["Se propone el modelo 1 por su mayor ajuste original, sujeto a aprobar el modelado del término poblacional.","Brazo relajado, muslo medio y pantorrilla máxima son sitios distintos de otros perímetros."],"limitations":"SEE original 2.2 kg; variable poblacional histórica y aplicación sólo en adultos no obesos requieren decisión explícita."
  }$json$::jsonb),
  ('somatotype_endomorphy', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"endomorphy","resultName":"Endomorfia","methodName":"Endomorfia · Heath-Carter","method":"Somatotipo antropométrico Heath-Carter","variant":"Componente endomórfico corregido por talla","summary":"Calcula el componente endomórfico con tríceps, subescapular y supraespinal corregidos por talla.","unit":"componente","decimalPlaces":1,
    "inputs":[{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"subscapular","label":"Pliegue subescapular","source":"consultation_measurement","measurementCode":"subscapular_skinfold","expectedUnit":"mm"},{"key":"supraspinale","label":"Pliegue supraespinal","source":"consultation_measurement","measurementCode":"supraespinale_skinfold","expectedUnit":"mm"},{"key":"height","label":"Estatura","source":"patient_record","patientField":"height_cm","expectedUnit":"cm"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"X=(tríceps+subescapular+supraespinal)·(170.18/talla_cm); endomorfia=−0.7182+0.1451·X−0.00068·X²+0.0000014·X³","conditions":["Si el componente calculado es ≤0, asignar 0.1"]},"variants":[],"applicability":{"population":"Método antropométrico Heath-Carter; requiere mediciones realizadas con sitios consistentes."},
    "references":[{"authors":"Carter JEL","year":2002,"title":"The Heath-Carter Anthropometric Somatotype: Instruction Manual","source":"San Diego State University","url":"https://phentermineclinics.net/wp-content/uploads/2023/09/Heath-CarterManual.pdf","evidence":"technical_manual"}],
    "validationStatus":"validated","validationNote":"Inputs, corrección por talla, polinomio y regla mínima definidos para 5B.","methodologicalNotes":["Usa supraespinal, no suprailíaco ni cresta ilíaca."],"limitations":"Es un componente descriptivo del somatotipo, no una clasificación clínica."
  }$json$::jsonb),
  ('somatotype_mesomorphy', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"mesomorphy","resultName":"Mesomorfia","methodName":"Mesomorfia · Heath-Carter","method":"Somatotipo antropométrico Heath-Carter","variant":"Componente mesomórfico","summary":"Calcula el componente mesomórfico con diámetros óseos, perímetros corregidos y talla.","unit":"componente","decimalPlaces":1,
    "inputs":[{"key":"humerus","label":"Diámetro biepicondilar del húmero","source":"consultation_measurement","measurementCode":"humerus_breadth","expectedUnit":"cm"},{"key":"femur","label":"Diámetro biepicondilar del fémur","source":"consultation_measurement","measurementCode":"femur_breadth","expectedUnit":"cm"},{"key":"flexed_arm","label":"Circunferencia de brazo flexionado y contraído","source":"consultation_measurement","measurementCode":"flexed_arm_circumference","expectedUnit":"cm"},{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"calf_girth","label":"Circunferencia máxima de pantorrilla","source":"consultation_measurement","measurementCode":"calf_circumference","expectedUnit":"cm"},{"key":"calf_skinfold","label":"Pliegue de pantorrilla medial","source":"consultation_measurement","measurementCode":"calf_skinfold","expectedUnit":"mm"},{"key":"height","label":"Estatura","source":"patient_record","patientField":"height_cm","expectedUnit":"cm"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"mesomorfia=0.858·húmero+0.601·fémur+0.188·CAG+0.161·CCG−0.131·talla+4.5","variables":{"CAG":"brazo flexionado y contraído cm − tríceps mm/10","CCG":"pantorrilla máxima cm − pantorrilla medial mm/10"},"conditions":["Si el componente calculado es ≤0, asignar 0.1"],"transformations":["Convertir cada pliegue de mm a cm antes de restarlo; Heath-Carter no multiplica esta corrección por π"]},"variants":[],"applicability":{"population":"Método antropométrico Heath-Carter; requiere protocolo consistente."},
    "references":[{"authors":"Carter JEL","year":2002,"title":"The Heath-Carter Anthropometric Somatotype: Instruction Manual","source":"San Diego State University","url":"https://phentermineclinics.net/wp-content/uploads/2023/09/Heath-CarterManual.pdf","evidence":"technical_manual"}],
    "validationStatus":"validated","validationNote":"Sitios exactos, unidades, correcciones y coeficientes definidos para 5B.","methodologicalNotes":["La corrección Heath-Carter resta el pliegue expresado en cm, sin π; no reutilizar la corrección de Lee."],"limitations":"Es un componente descriptivo del somatotipo y depende de técnica antropométrica consistente."
  }$json$::jsonb),
  ('somatotype_ectomorphy', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"ectomorphy","resultName":"Ectomorfia","methodName":"Ectomorfia · Heath-Carter","method":"Somatotipo antropométrico Heath-Carter","variant":"Componente ectomórfico por HWR","summary":"Calcula el componente ectomórfico mediante la relación talla-raíz cúbica del peso y sus tres tramos.","unit":"componente","decimalPlaces":1,
    "inputs":[{"key":"height","label":"Estatura","source":"patient_record","patientField":"height_cm","expectedUnit":"cm"},{"key":"weight","label":"Peso","source":"consultation_measurement","measurementCode":"weight","expectedUnit":"kg"}],"optionalInputs":[],"dependencies":[],
    "equation":{"expression":"HWR=talla_cm/∛peso_kg; si HWR≥40.75: 0.732·HWR−28.58; si 38.25<HWR<40.75: 0.463·HWR−17.63; si HWR≤38.25: 0.1","conditions":["Si cualquier componente resultara ≤0, asignar 0.1"]},"variants":[],"applicability":{"population":"Método antropométrico Heath-Carter."},
    "references":[{"authors":"Carter JEL","year":2002,"title":"The Heath-Carter Anthropometric Somatotype: Instruction Manual","source":"San Diego State University","url":"https://phentermineclinics.net/wp-content/uploads/2023/09/Heath-CarterManual.pdf","evidence":"technical_manual"}],
    "validationStatus":"validated","validationNote":"Relación ponderal, unidades, tramos y regla mínima definidos para 5B.","methodologicalNotes":[],"limitations":"Es un componente descriptivo del somatotipo, no una clasificación clínica."
  }$json$::jsonb),
  ('somatochart_coordinates', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"somatochart_coordinates","resultName":"Coordenadas de somatocarta","methodName":"Coordenadas de somatocarta · Heath-Carter","method":"Somatocarta bidimensional Heath-Carter","variant":"Coordenadas X/Y","summary":"Ubica el somatotipo a partir de sus tres componentes ya calculados.","unit":"coordenadas","decimalPlaces":1,"inputs":[],"optionalInputs":[],"dependencies":["somatotype_endomorphy","somatotype_mesomorphy","somatotype_ectomorphy"],
    "equation":{"expression":"X = ectomorfia − endomorfia; Y = 2·mesomorfia − (endomorfia + ectomorfia)","variables":{"X":"Eje horizontal","Y":"Eje vertical"}},"variants":[],"applicability":{"population":"Cualquier somatotipo Heath-Carter con los tres componentes disponibles."},
    "references":[{"authors":"Carter JEL","year":2002,"title":"The Heath-Carter Anthropometric Somatotype: Instruction Manual","source":"San Diego State University","url":"https://phentermineclinics.net/wp-content/uploads/2023/09/Heath-CarterManual.pdf","evidence":"technical_manual"}],
    "validationStatus":"validated","validationNote":"Dependencias y ecuaciones X/Y definidas para 5B.","methodologicalNotes":["Las coordenadas son un resultado vectorial; 5B deberá modelar X e Y sin reducirlas a un único número."],"limitations":"No añade categorías ni interpretación clínica."
  }$json$::jsonb)
) as v(code, method_version, definition)
where c.code = v.code;

update public.calculation_definitions as c
set method_version = v.method_version,
    definition = v.definition,
    updated_at = now()
from (values
  ('body_fat_jp3_siri', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_fat_percentage","resultName":"Porcentaje de grasa corporal","methodName":"Jackson & Pollock 3 + Siri","method":"Siri","variant":"Conversión de densidad Jackson & Pollock 3","summary":"Convierte con Siri la densidad producida por Jackson & Pollock 3; conserva la procedencia completa.","unit":"%","decimalPlaces":1,"inputs":[],"optionalInputs":[],"dependencies":["density_jackson_pollock_3"],
    "equation":{"expression":"% grasa = (4.95 / densidad_g_cm3 − 4.50) × 100","variables":{"densidad_g_cm3":"Resultado de Jackson & Pollock 3 en g/cm³"}},"variants":[],"applicability":{"population":"Adultos compatibles con la ecuación de densidad precedente.","exclusions":["No asumir composición constante de la masa libre de grasa en todas las poblaciones."]},
    "references":[{"authors":"Siri WE","year":1961,"title":"Body composition from fluid spaces and density: analysis of methods","source":"Techniques for Measuring Body Composition","url":"https://escholarship.org/uc/item/6mh9f4nf","evidence":"original"},{"authors":"Jackson AS, Pollock ML; Jackson AS, Pollock ML, Ward A","year":1978,"title":"Generalized body-density equations for men and women (1978/1980)","source":"British Journal of Nutrition / Medicine and Science in Sports and Exercise","url":"https://pubmed.ncbi.nlm.nih.gov/7402053/","evidence":"original"}],
    "validationStatus":"validated","validationNote":"Conversión y dependencia explícita definidas para 5B.","methodologicalNotes":["Siri no vuelve a consumir pliegues: consume la densidad trazable del cálculo anterior."],"limitations":"Modelo bicompartimental sujeto a supuestos sobre densidades de grasa y masa libre de grasa."
  }$json$::jsonb),
  ('body_fat_jp7_siri', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_fat_percentage","resultName":"Porcentaje de grasa corporal","methodName":"Jackson & Pollock 7 + Siri","method":"Siri","variant":"Conversión de densidad Jackson & Pollock 7","summary":"Convierte con Siri la densidad producida por Jackson & Pollock 7.","unit":"%","decimalPlaces":1,"inputs":[],"optionalInputs":[],"dependencies":["density_jackson_pollock_7"],"equation":{"expression":"% grasa = (4.95 / densidad_g_cm3 − 4.50) × 100"},"variants":[],"applicability":{"population":"Adultos compatibles con la ecuación de densidad Jackson & Pollock 7."},
    "references":[{"authors":"Siri WE","year":1961,"title":"Body composition from fluid spaces and density: analysis of methods","source":"Techniques for Measuring Body Composition","url":"https://escholarship.org/uc/item/6mh9f4nf","evidence":"original"},{"authors":"Jackson AS, Pollock ML; Jackson AS, Pollock ML, Ward A","year":1978,"title":"Generalized body-density equations for men and women (1978/1980)","source":"British Journal of Nutrition / Medicine and Science in Sports and Exercise","url":"https://www.cambridge.org/core/journals/british-journal-of-nutrition/article/generalized-equations-for-predicting-body-density-of-men/EAB21B1CF3A8360E5F5D43FDB8D4DD17","evidence":"original"}],
    "validationStatus":"validated","validationNote":"Conversión y dependencia explícita definidas para 5B.","methodologicalNotes":["El resultado mantiene el código del método de densidad precedente."],"limitations":"Modelo bicompartimental; hereda además las limitaciones de Jackson & Pollock 7."
  }$json$::jsonb),
  ('body_fat_jp7_brozek', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_fat_percentage","resultName":"Porcentaje de grasa corporal","methodName":"Jackson & Pollock 7 + Brozek","method":"Brozek","variant":"Conversión de densidad Jackson & Pollock 7","summary":"Convierte mediante Brozek la densidad producida por Jackson & Pollock 7, separada de Siri.","unit":"%","decimalPlaces":1,"inputs":[],"optionalInputs":[],"dependencies":["density_jackson_pollock_7"],"equation":{"expression":"% grasa = (4.570 / densidad_g_cm3 − 4.142) × 100"},"variants":[],"applicability":{"population":"Adultos compatibles con la ecuación de densidad precedente."},
    "references":[{"authors":"Brozek J, Grande F, Anderson JT, Keys A","year":1963,"title":"Densitometric analysis of body composition: revision of some quantitative assumptions","source":"Annals of the New York Academy of Sciences","doi":"10.1111/j.1749-6632.1963.tb17079.x","url":"https://nyaspubs.onlinelibrary.wiley.com/doi/10.1111/j.1749-6632.1963.tb17079.x","evidence":"original"},{"authors":"Jackson AS, Pollock ML; Jackson AS, Pollock ML, Ward A","year":1978,"title":"Generalized body-density equations for men and women (1978/1980)","source":"British Journal of Nutrition / Medicine and Science in Sports and Exercise","url":"https://pubmed.ncbi.nlm.nih.gov/7402053/","evidence":"original"}],
    "validationStatus":"validated","validationNote":"Brozek permanece como conversión independiente, con dependencia y coeficientes definidos.","methodologicalNotes":["No es intercambiable silenciosamente con Siri."],"limitations":"Modelo bicompartimental; hereda las limitaciones del método de densidad precedente."
  }$json$::jsonb),
  ('body_fat_durnin_siri', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_fat_percentage","resultName":"Porcentaje de grasa corporal","methodName":"Durnin & Womersley + Siri","method":"Siri","variant":"Conversión de densidad Durnin & Womersley","summary":"Convierte con Siri la densidad producida por Durnin & Womersley.","unit":"%","decimalPlaces":1,"inputs":[],"optionalInputs":[],"dependencies":["density_durnin_womersley"],"equation":{"expression":"% grasa = (4.95 / densidad_g_cm3 − 4.50) × 100"},"variants":[],"applicability":{"population":"Personas dentro del grupo por sexo y edad definido por Durnin & Womersley."},
    "references":[{"authors":"Siri WE","year":1961,"title":"Body composition from fluid spaces and density: analysis of methods","source":"Techniques for Measuring Body Composition","url":"https://escholarship.org/uc/item/6mh9f4nf","evidence":"original"},{"authors":"Durnin JVGA, Womersley J","year":1974,"title":"Body fat assessed from total body density and its estimation from skinfold thickness","source":"British Journal of Nutrition","doi":"10.1079/BJN19740060","url":"https://www.cambridge.org/core/journals/british-journal-of-nutrition/article/body-fat-assessed-from-total-body-density-and-its-estimation-from-skinfold-thickness-measurements-on-481-men-and-women-aged-from-16-to-72-years/DAC8BA25856FCEB30E22F60E0AF80D07","evidence":"original"}],
    "validationStatus":"validated","validationNote":"Conversión y cadena de procedencia definidas para 5B.","methodologicalNotes":[],"limitations":"Modelo bicompartimental; hereda las limitaciones de Durnin & Womersley."
  }$json$::jsonb),
  ('body_fat_faulkner', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_fat_percentage","resultName":"Porcentaje de grasa corporal","methodName":"Faulkner","method":"Fórmula atribuida a Faulkner","variant":"No adoptada","summary":"La literatura reproduce variantes atribuidas a Faulkner, pero la procedencia de la ecuación habitual y sus sitios no pudo confirmarse con seguridad en la fuente original.","unit":"%","decimalPlaces":1,"inputs":[],"optionalInputs":[],"dependencies":[],"equation":{"expression":"No programar hasta confirmar la variante y su fuente primaria."},
    "variants":[{"code":"candidate_four_skinfolds","name":"Candidata habitual de cuatro pliegues · no adoptada","inputs":[{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"subscapular","label":"Pliegue subescapular","source":"consultation_measurement","measurementCode":"subscapular_skinfold","expectedUnit":"mm"},{"key":"supraespinale","label":"Pliegue supraespinal","source":"consultation_measurement","measurementCode":"supraespinale_skinfold","expectedUnit":"mm"},{"key":"abdominal","label":"Pliegue abdominal","source":"consultation_measurement","measurementCode":"abdominal_skinfold","expectedUnit":"mm"}],"equation":{"expression":"Fórmula publicada frecuentemente: % grasa = 5.783 + 0.153·S4; no adoptada por atribución incierta."},"note":"Algunas fuentes sustituyen supraespinal por suprailíaco y otras publican coeficientes diferentes."}],
    "applicability":{"population":"No establecida con seguridad para una variante de producción."},"references":[{"authors":"Canda AS, Esparza F","year":2009,"title":"The Faulkner equation for predicting body fat: the end of a myth","source":"Archivos de Medicina del Deporte","url":"https://www.researchgate.net/publication/26460946_The_faulkner_equation_for_predicting_body_fat_The_end_of_a_myth","evidence":"secondary_scholarly"}],
    "validationStatus":"pending_evidence","validationNote":"Falta confirmar en fuente primaria una ecuación atribuible a Faulkner, sus sitios exactos, población y coeficientes.","methodologicalNotes":["No agregar automáticamente la variante candidata al flujo clínico."],"limitations":"Atribución, población original y equivalencia supraespinal/suprailíaco no resueltas."
  }$json$::jsonb),
  ('body_fat_yuhasz', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"body_fat_percentage","resultName":"Porcentaje de grasa corporal","methodName":"Yuhasz","method":"Yuhasz / adaptaciones posteriores","variant":"Requiere elección explícita","summary":"Existen ecuaciones originales masculinas y adaptaciones posteriores para atletas con diferentes sitios y coeficientes.","unit":"%","decimalPlaces":1,"inputs":[],"optionalInputs":[],"dependencies":[],"equation":{"expression":"No programar hasta adoptar una variante explícita."},
    "variants":[
      {"code":"yuhasz_young_men_1962","name":"Yuhasz 1962 · hombres jóvenes","inputs":[{"key":"chest","label":"Pliegue pectoral","source":"consultation_measurement","measurementCode":"chest_skinfold","expectedUnit":"mm"},{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"subscapular","label":"Pliegue subescapular","source":"consultation_measurement","measurementCode":"subscapular_skinfold","expectedUnit":"mm"},{"key":"suprailiac","label":"Pliegue suprailíaco","source":"consultation_measurement","measurementCode":"suprailiac_skinfold","expectedUnit":"mm"},{"key":"abdominal","label":"Pliegue abdominal/umbilical","source":"consultation_measurement","measurementCode":"abdominal_skinfold","expectedUnit":"mm"},{"key":"thigh","label":"Pliegue de muslo anterior","source":"consultation_measurement","measurementCode":"thigh_skinfold","expectedUnit":"mm"}],"equation":{"expression":"% grasa = 3.641 + 0.0970·S6"},"applicability":{"sexes":["male"],"population":"Hombres jóvenes de la tesis original."}},
      {"code":"yuhasz_adult_men_1962","name":"Yuhasz 1962 · hombres adultos","inputs":[{"key":"chest","label":"Pliegue pectoral","source":"consultation_measurement","measurementCode":"chest_skinfold","expectedUnit":"mm"},{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"subscapular","label":"Pliegue subescapular","source":"consultation_measurement","measurementCode":"subscapular_skinfold","expectedUnit":"mm"},{"key":"suprailiac","label":"Pliegue suprailíaco","source":"consultation_measurement","measurementCode":"suprailiac_skinfold","expectedUnit":"mm"},{"key":"abdominal","label":"Pliegue abdominal/umbilical","source":"consultation_measurement","measurementCode":"abdominal_skinfold","expectedUnit":"mm"},{"key":"thigh","label":"Pliegue de muslo anterior","source":"consultation_measurement","measurementCode":"thigh_skinfold","expectedUnit":"mm"}],"equation":{"expression":"% grasa = 4.975 + 0.1066·S6"},"applicability":{"sexes":["male"],"population":"Hombres adultos de la tesis original."}},
      {"code":"carter_athlete_adaptation","name":"Adaptación de Carter para atletas · no es la variante original genérica","inputs":[{"key":"triceps","label":"Pliegue tricipital","source":"consultation_measurement","measurementCode":"triceps_skinfold","expectedUnit":"mm"},{"key":"subscapular","label":"Pliegue subescapular","source":"consultation_measurement","measurementCode":"subscapular_skinfold","expectedUnit":"mm"},{"key":"supraespinale","label":"Pliegue supraespinal","source":"consultation_measurement","measurementCode":"supraespinale_skinfold","expectedUnit":"mm"},{"key":"abdominal","label":"Pliegue abdominal","source":"consultation_measurement","measurementCode":"abdominal_skinfold","expectedUnit":"mm"},{"key":"thigh","label":"Pliegue de muslo anterior","source":"consultation_measurement","measurementCode":"thigh_skinfold","expectedUnit":"mm"},{"key":"calf","label":"Pliegue de pantorrilla medial","source":"consultation_measurement","measurementCode":"calf_skinfold","expectedUnit":"mm"}],"equation":{"expression":"Coeficientes específicos por sexo publicados como adaptación; requieren decisión de producto."},"applicability":{"population":"Atletas; adaptación posterior."}}
    ],
    "applicability":{"population":"Depende de la variante que se adopte; no existe una variante universal."},"references":[{"authors":"Yuhasz MS","year":1962,"title":"The effects of sports training on body fat in man with predictions of optimal body weight","source":"University of Illinois dissertation","url":"https://www.ideals.illinois.edu/items/57389","evidence":"original"},{"authors":"Canda AS, Esparza F","year":2009,"title":"The Faulkner equation for predicting body fat: the end of a myth","source":"Archivos de Medicina del Deporte","url":"https://www.researchgate.net/publication/26460946_The_faulkner_equation_for_predicting_body_fat_The_end_of_a_myth","evidence":"secondary_scholarly"}],
    "validationStatus":"requires_decision","validationNote":"Debe elegirse entre la ecuación original para hombres y una adaptación posterior para atletas; no se seleccionó silenciosamente.","methodologicalNotes":["Las variantes usan sitios diferentes, en particular suprailíaco frente a supraespinal y pantorrilla."],"limitations":"La población y el sexo aplicable cambian entre variantes."
  }$json$::jsonb),
  ('fat_mass_jp7_siri', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"fat_mass","resultName":"Masa grasa","methodName":"Masa grasa · Jackson & Pollock 7 + Siri","method":"Compartimento derivado","variant":"Procedencia JP7 → Siri","summary":"Deriva masa grasa del peso de la consulta y del porcentaje de grasa producido por Jackson & Pollock 7 + Siri.","unit":"kg","decimalPlaces":1,"inputs":[{"key":"weight","label":"Peso","source":"consultation_measurement","measurementCode":"weight","expectedUnit":"kg"}],"optionalInputs":[],"dependencies":["body_fat_jp7_siri"],"equation":{"expression":"masa_grasa_kg = peso_kg × porcentaje_grasa / 100"},"variants":[],"applicability":{"population":"La misma población para la que resulte aplicable la cadena Jackson & Pollock 7 + Siri."},"references":[{"authors":"Siri WE","year":1961,"title":"Body composition from fluid spaces and density: analysis of methods","source":"Techniques for Measuring Body Composition","url":"https://escholarship.org/uc/item/6mh9f4nf","evidence":"original"}],"validationStatus":"validated","validationNote":"Fórmula y dependencia metodológica exacta definidas.","methodologicalNotes":["No usa un porcentaje de grasa genérico ni seleccionable implícitamente."],"limitations":"Hereda todos los supuestos y límites de la cadena que produjo el porcentaje."
  }$json$::jsonb),
  ('fat_free_mass_jp7_siri', '2.0.0-spec', $json${
    "catalogVersion":2,"resultKey":"fat_free_mass","resultName":"Masa libre de grasa","methodName":"Masa libre de grasa · Jackson & Pollock 7 + Siri","method":"Compartimento derivado","variant":"Procedencia JP7 → Siri","summary":"Deriva masa libre de grasa del peso y de la masa grasa del mismo método.","unit":"kg","decimalPlaces":1,"inputs":[{"key":"weight","label":"Peso","source":"consultation_measurement","measurementCode":"weight","expectedUnit":"kg"}],"optionalInputs":[],"dependencies":["fat_mass_jp7_siri"],"equation":{"expression":"masa_libre_grasa_kg = peso_kg − masa_grasa_kg"},"variants":[],"applicability":{"population":"La misma población para la que resulte aplicable la cadena Jackson & Pollock 7 + Siri."},"references":[{"authors":"Siri WE","year":1961,"title":"Body composition from fluid spaces and density: analysis of methods","source":"Techniques for Measuring Body Composition","url":"https://escholarship.org/uc/item/6mh9f4nf","evidence":"original"}],"validationStatus":"validated","validationNote":"Fórmula y cadena de procedencia exacta definidas.","methodologicalNotes":["Depende de la masa grasa identificada, no de un porcentaje universal."],"limitations":"No equivale a masa muscular; hereda las limitaciones del modelo bicompartimental."
  }$json$::jsonb)
) as v(code, method_version, definition)
where c.code = v.code;

-- Guardrails: all 19 visible anthropometric contracts are complete enough for
-- the interface, and runtime status remains independent from validation.
do $$
declare
  incomplete_count integer;
begin
  select count(*) into incomplete_count
  from public.calculation_definitions
  where is_catalog_visible
    and (
      definition->>'catalogVersion' <> '2'
      or definition->>'validationStatus' not in ('validated','requires_decision','pending_evidence')
      or jsonb_typeof(definition->'inputs') <> 'array'
      or jsonb_typeof(definition->'optionalInputs') <> 'array'
      or jsonb_typeof(definition->'dependencies') <> 'array'
      or jsonb_typeof(definition->'equation') <> 'object'
      or jsonb_typeof(definition->'applicability') <> 'object'
      or jsonb_typeof(definition->'references') <> 'array'
    );
  if incomplete_count <> 0 then
    raise exception 'Objective 5A left % visible calculation contracts incomplete', incomplete_count;
  end if;
end;
$$;
